mudita/mudita-center

- packages/app/src/messages/components/thread-list.component.tsx
Jira: [CP-820]
List Height set to min 100% to display dropdown properly
[CP-820]: https://appnroll.atlassian.net/browse/CP-820?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-820] Messages options menu is not visible

- packages/app/src/renderer/locales/default/en-US.json
Jira: [CP-826]
[CP-826]: https://appnroll.atlassian.net/browse/CP-826?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-826] Copy fix in wrong passcode section

- README.md
Updated README before launching the release
Jira: [CP-XXX]
<details>
</details>
> [CP-XX] Updated README.md

- packages/app/jest.coverage.json
- packages/app/src/feature-flags/features/index.ts
- packages/app/src/main/utils/map-to-release.test.ts
- packages/app/src/main/utils/map-to-release.ts
- packages/app/src/messages/components/thread-details-sidebar-right-header.component.tsx
- packages/app/src/messages/components/thread-details-text-area.component.tsx
> [CP-XXX] Alpha Environment adjusted to daily builds

- packages/app/src/contacts/components/contact-list/contact-list.component.test.tsx
- packages/app/src/messages/components/thread-details.styled.tsx
- packages/app/src/messages/components/thread-row.component.tsx
- packages/app/src/passcode-modal/passcode-modal.test.tsx
Jira: [CP-797]
Fixes after Patryk's review:
- center Conversation name when there is no messages
- fix colors on Send button in messages
<details>
Conversation name
Send button color
</details>
[CP-797]: https://appnroll.atlassian.net/browse/CP-797?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-797] Fixes after the design review

- packages/app/src/contacts/components/contact-import/contact-import-modal.component.tsx
- packages/app/src/contacts/components/contact-import/contact-import-modal.test.tsx
- packages/app/src/contacts/store/contacts.helpers.ts
Jira: [CP-836]
<details>
</details>
[CP-836]: https://appnroll.atlassian.net/browse/CP-836?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-836] I want to see contacts during the import process starting from the second name

- packages/app/package-lock.json
- packages/app/package.json
- packages/app/src/contacts/components/sync-contacts-modal/sync-contacts-modal.component.tsx
- packages/app/src/contacts/components/sync-contacts-modal/sync-contacts.styled.tsx
Jira: [CP-883]
- change version to 1.1.0-rc.2 that includes CP-883
- changed Google button style in contact import
[CP-883]: https://appnroll.atlassian.net/browse/CP-883?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-883] Change Continue with Google button style

- packages/app/src/messages/components/messages/messages.component.tsx
Jira: [CP-891]
- `getViewReceiver` fixed logic to handle `undefined` from `getReceiver` selector
[CP-891]: https://appnroll.atlassian.net/browse/CP-891?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-891] After deleting last message in a thread on Pure, Mudita Center changes to blank

- packages/app/src/renderer/store/index.ts
Jira: [CP-XXX]
`redux-logger` as middleware uncomment
> `redux-logger` as middleware uncomment

- packages/pure/src/device/base-device.ts
Jira: [CP-XXX]
`portBlocked` removed as unused property
> `portBlocked` removed as unused property

- packages/app/src/renderer/models/external-providers/google/google.ts
Jira: [CP-948]
Fix when 0 Google contacts
<details>
</details>
[CP-948]: https://appnroll.atlassian.net/browse/CP-948?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-948] Import contacts from Google when there is no contacts

- packages/app/src/device/reducers/device.reducer.test.ts
- packages/app/src/device/reducers/device.reducer.ts
- packages/app/src/overview/helpers/system-update.hook.tsx
- packages/app/src/renderer/wrappers/base-app.component.tsx
Jira: [CP-852]
Hide modals when device is disconnected
<details>
</details>
[CP-852]: https://appnroll.atlassian.net/browse/CP-852?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-852] Hide modals when disconnected

- packages/app/package-lock.json
- packages/app/package.json
- packages/app/src/data-sync/indexes/base.indexer.ts
- packages/app/src/main/main.ts
- packages/app/webpack.config.main.js
- packages/app/webpack/parts/plugins.js
Jira: [CP-978]
Fix serving static files for `sql.js` module
<details>
</details>
[CP-978]: https://appnroll.atlassian.net/browse/CP-978?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-978] Serve static files for sql.js

- packages/app/src/data-sync/actions/update-all-indexes.action.test.ts
- packages/app/src/data-sync/actions/update-all-indexes.action.ts
- packages/app/src/data-sync/constants/index.ts
- packages/app/src/data-sync/constants/thread.constant.ts
- packages/app/src/data-sync/indexes/index.ts
- packages/app/src/data-sync/indexes/thread.indexer.test.ts
- packages/app/src/data-sync/indexes/thread.indexer.ts
- packages/app/src/data-sync/presenters/index.ts
- packages/app/src/data-sync/presenters/message/message.presenter.test.ts
- packages/app/src/data-sync/presenters/thread/thread.presenter.test.ts
- packages/app/src/data-sync/presenters/thread/thread.presenter.ts
- packages/app/src/data-sync/services/data-sync.service.ts
- packages/app/src/data-sync/types/all-indexes.type.ts
- packages/app/src/data-sync/types/index.ts
- packages/app/src/data-sync/types/message-object.type.ts
- packages/app/src/data-sync/types/thread-object.type.ts
- packages/app/src/renderer/store/index.ts
Jira: [CP-943]
Implement threads part
<details>
</details>
[CP-943]: https://appnroll.atlassian.net/browse/CP-943?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-943] Implement threads part

- packages/app/src/backend/adapters/device-backup/device-backup.adapter.test.ts
- packages/app/src/backend/adapters/device-backup/device-backup.adapter.ts
Jira: [CP-XXX]
<details>
</details>
> Removing device file during backuping locally added (tmp solution)

- packages/app/src/overview/components/restore-modal-dialogs/restore-modal-dialogs.tsx
Jira: [CP-968]
Changed button width. Width from design will be added after buttons UI update task 
<details>
</details>
[CP-968]: https://appnroll.atlassian.net/browse/CP-968?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-968] CONTACT SUPPORT button - label outside the frame

- .huskyrc
> Removing git add . from pre-commit

- .husky/pre-commit
- .huskyrc
- package-lock.json
- package.json
Jira: [CP-505]
Husky update
<details>
</details>
[CP-505]: https://appnroll.atlassian.net/browse/CP-505?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-505] Husky update

- packages/e2e/.gitignore
- packages/e2e/helpers/github.helper.ts
- packages/e2e/package-lock.json
- packages/e2e/package.json
- packages/e2e/wdio.conf.ts
Jira: [CP-938]
<details>
</details>
[CP-938]: https://appnroll.atlassian.net/browse/CP-938?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-938] Implementing JSON reporter and fix latest release check

- packages/app/src/feature-flags/features/index.ts
Jira: [CP-992]
[CP-992]: https://appnroll.atlassian.net/browse/CP-992?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-992] User contacts data present in Center log files

- packages/app/src/api/mudita-center-server/client.ts
- packages/app/src/api/mudita-center-server/mudita-center-server-routes.ts
- packages/app/src/feature-flags/constants/feature.enum.ts
- packages/app/src/feature-flags/features/index.ts
- packages/app/src/main/main.ts
- packages/app/src/overview/components/updating-force-modal-flow/updating-force-modal-flow.component.tsx
- packages/app/src/overview/helpers/system-update.hook.tsx
- packages/app/src/update/listeners/get-production-release.listener.ts
- packages/app/src/update/listeners/index.ts
- packages/app/src/update/requests/download-os-update.request.test.ts
- packages/app/src/update/requests/download-os-update.request.ts
- packages/app/src/update/requests/get-all-releases.request.test.ts
- packages/app/src/update/requests/get-all-releases.request.ts
- packages/app/src/update/requests/index.ts
Jira: [CP-1070]
<details>
</details>
[CP-1070]: https://appnroll.atlassian.net/browse/CP-1070?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1070] Changing release source depending on environment

- packages/app/src/connecting/components/connecting.component.tsx
- packages/app/src/connecting/components/connecting.test.tsx
- packages/app/src/connecting/connecting.container.ts
- packages/app/src/overview/components/overview-screens/pure-overview/pure-overview.component.test.tsx
- packages/app/src/overview/components/overview-screens/pure-overview/pure-overview.component.tsx
- packages/app/src/overview/components/overview/overview.test.tsx
- packages/app/src/overview/overview.container.tsx
- packages/app/src/renderer/components/rest/menu/__snapshots__/menu.test.tsx.snap
- packages/app/src/renderer/components/rest/menu/menu-group-test-ids.enum.ts
- packages/app/src/renderer/components/rest/menu/menu.component.tsx
- packages/app/src/renderer/components/rest/menu/menu.container.tsx
- packages/app/src/renderer/components/rest/menu/menu.test.tsx
- packages/app/src/renderer/locales/default/en-US.json
Jira: [CP-XXX]
- Added sync info on menu
- added error sync modal on Overview
<details>
</details>
> [CP-998] I want to see a sync state

- packages/app/src/backend/adapters/device-backup/device-backup.adapter.ts
- packages/app/src/backend/adapters/device-file-system/device-file-system.adapter.ts
Jira: [CP-1097]
[CP-1097]: https://appnroll.atlassian.net/browse/CP-1097?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1097] Synchronization failed on Windows, MacOS

- packages/app/src/backend/adapters/pure-phone/pure-phone.adapter.ts
Jira: [CP-1093]
Resolving issue related to wrong update state modal after `BellHybrid` has been successfully updated
<details>
</details>
[CP-1093]: https://appnroll.atlassian.net/browse/CP-1093?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1093] Fix wrong update state for harmony

- packages/app/src/overview/components/overview-modals.component.tsx
- packages/app/src/overview/components/overview.modal-dialogs.tsx
Jira: [CP-1104]
Same PR as before to CP-1104, but with new base branch v.1.2.0
<details>
</details>
[CP-1104]: https://appnroll.atlassian.net/browse/CP-1104?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1104] [Harmony] Duplicate text on prompt about low battery

- packages/app/src/data-sync/actions/base-app.action.test.ts
- packages/app/src/data-sync/actions/base-app.action.ts
- packages/app/src/data-sync/constants/event.enum.ts
- packages/app/src/data-sync/reducers/data-sync.reducer.test.ts
- packages/app/src/data-sync/reducers/data-sync.reducer.ts
- packages/app/src/device/actions/set-connection-status.action.test.ts
- packages/app/src/device/actions/set-connection-status.action.ts
Jira: [CP-1118]
Restore data fetching fixed after finish process
[CP-1118]: https://appnroll.atlassian.net/browse/CP-1118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1118] Mudita Center no display data after successful restore data

- packages/app/src/backend/adapters/pure-phone/pure-phone.adapter.ts
- packages/app/src/overview/helpers/system-update.hook.tsx
Jira: [CP-1120]
Increase timeout during update from 3 to 5 minutes
[CP-1120]: https://appnroll.atlassian.net/browse/CP-1120?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1120] Update failed monit on MC v1.2.0-rc.3 Mudita OS 1.1.6 -> PurePhone 1.2.0-rc.3

- packages/app/package-lock.json
- packages/app/package.json
- packages/app/src/backend/adapters/pure-phone/pure-phone.adapter.ts
- packages/app/src/data-sync/actions/base-app.action.test.ts
- packages/app/src/data-sync/actions/base-app.action.ts
- packages/app/src/data-sync/constants/event.enum.ts
- packages/app/src/data-sync/reducers/data-sync.reducer.test.ts
- packages/app/src/data-sync/reducers/data-sync.reducer.ts
- packages/app/src/device/actions/set-connection-status.action.test.ts
- packages/app/src/device/actions/set-connection-status.action.ts
- packages/app/src/overview/helpers/system-update.hook.tsx
> v1.2.0 rc.4

- packages/app/src/backend/adapters/device-base-info/device-base-info.adapter.ts
- packages/app/src/data-sync/actions/update-all-indexes.action.test.ts
- packages/app/src/data-sync/actions/update-all-indexes.action.ts
- packages/app/src/data-sync/constants/event.enum.ts
- packages/app/src/data-sync/constants/ipc-event.constant.ts
- packages/app/src/data-sync/controllers/data-sync.controller.ts
- packages/app/src/data-sync/listeners/cache-data.listener.ts
- packages/app/src/data-sync/listeners/data-sync.listener.ts
- packages/app/src/data-sync/observers/device-connection.observer.test.ts
- packages/app/src/data-sync/observers/device-connection.observer.ts
- packages/app/src/data-sync/requests/index-all.request.ts
- packages/app/src/index-storage/factories/index.factory.ts
- packages/app/src/index-storage/observers/index-storage-loading.observer.test.ts
- packages/app/src/index-storage/observers/index-storage-loading.observer.ts
- packages/app/src/index-storage/services/index-storage.service.ts
- packages/app/src/index-storage/types/index-storage.type.ts
- packages/app/src/outbox/observers/outbox.observer.test.ts
- packages/app/src/outbox/observers/outbox.observer.ts
- packages/app/src/outbox/services/outbox.service.ts
Jira: [CP-1036]
- [watchOutboxEntries process fixed by triggered unique event for self](https://github.com/mudita/mudita-center/pull/672/commits/5e9dc52255024ac2407772c239e942f8946a7c74)
- Error thrown during getIndex fixed
- https://github.com/mudita/mudita-center/pull/672/commits/348354e48548964b4293984aa3334072491a58cc
- https://github.com/mudita/mudita-center/pull/672/commits/41156e4b8435f034d940c51058e8ecabce411236
- [Duplicated event emitters handled by register listener during on bootstraping](https://github.com/mudita/mudita-center/pull/672/commits/f4f0738e6c0bde91827baccffa196a8dae93df9d)
- [Error thrown during reading deprecated cache fixed](https://github.com/mudita/mudita-center/pull/672/commits/48db760566e870c0154973fe1835c66283fc2c58)
- [No triggered Failure …
> [CP-1036] Fix sync logic

- packages/app/package-lock.json
- packages/app/package.json
> v1.3.0-rc.1

- packages/app/src/backend/device-service.ts
- packages/app/src/data-sync/observers/device-connection.observer.test.ts
- packages/app/src/data-sync/observers/device-connection.observer.ts
Jira: [CP-1199]
Handled Harmony device type during device-connection observer
[CP-1199]: https://appnroll.atlassian.net/browse/CP-1199?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1199] I get a prompt about a failed sync momentarily when I connect my device

- packages/pure/src/device/base-device.test.ts
- packages/pure/src/device/mc-usb-device.ts
- packages/pure/src/device/services/device-resolver.service.ts
- packages/pure/src/device/services/usb-device.service.factory.ts
- packages/pure/src/device/services/usb-device.service.ts
Jira: [CP-1156]
<details>
</details>
[CP-1156]: https://appnroll.atlassian.net/browse/CP-1156?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1156] Add DeviceService and DeviceServiceFactory

- packages/app/package-lock.json
- packages/app/package.json
- packages/app/src/backend/device-service.ts
- packages/app/src/data-sync/observers/device-connection.observer.test.ts
- packages/app/src/data-sync/observers/device-connection.observer.ts
> v1.3.0-rc.2

- packages/app/src/data-sync/actions/base-app.action.test.ts
- packages/app/src/data-sync/actions/base-app.action.ts
- packages/app/src/data-sync/constants/event.enum.ts
- packages/app/src/data-sync/reducers/data-sync.reducer.test.ts
- packages/app/src/data-sync/reducers/data-sync.reducer.ts
- packages/app/src/device/actions/set-connection-status.action.test.ts
- packages/app/src/device/actions/set-connection-status.action.ts
- packages/app/src/renderer/wrappers/root-wrapper.tsx
Jira: [CP-1200]
cherry-picked fixes the from missing commit: https://github.com/mudita/mudita-center/pull/665
[CP-1200]: https://appnroll.atlassian.net/browse/CP-1200?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1200] Mudita Center no display data after successful restore data

- packages/app/package-lock.json
- packages/app/package.json
- packages/app/src/data-sync/actions/base-app.action.test.ts
- packages/app/src/data-sync/actions/base-app.action.ts
- packages/app/src/data-sync/constants/event.enum.ts
- packages/app/src/data-sync/reducers/data-sync.reducer.test.ts
- packages/app/src/data-sync/reducers/data-sync.reducer.ts
- packages/app/src/device/actions/set-connection-status.action.test.ts
- packages/app/src/device/actions/set-connection-status.action.ts
- packages/app/src/renderer/wrappers/root-wrapper.tsx
> v1.3.0-rc.3

- packages/app/src/files-manager/components/files-manager/files-manager.component.tsx
- packages/app/src/files-manager/components/files-storage-list-type-col/files-storage-list-type-col-test-ids.enum.ts
- packages/app/src/files-manager/components/files-storage-list-type-col/files-storage-list-type-col.test.tsx
- packages/app/src/files-manager/components/files-storage-list-type-col/files-storage-list-type-col.tsx
- packages/app/src/files-manager/components/files-storage-list/files-storage-list.component.tsx
- packages/pure/src/device/device.types.ts
- packages/pure/src/device/mc-usb-device.ts
Jira: [CP-XXX]
- fix col displaying type/size by switching col content
- type col UI updated
- size col UI updated (`convertBytes` added)
- `undefined` file type added
- Hover state removed from `FilesStorageList:Row`
<details>
previous
current
</details>
> `FilesStorageListTypeCol` implemented

- packages/app/src/messages/components/messages/messages.component.tsx
- packages/app/src/messages/components/messages/messages.test.tsx
Jira: [CP-1239]
<details>
</details>
[CP-1239]: https://appnroll.atlassian.net/browse/CP-1239?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1239] Fix Messages view after removed thread on the Pure

- packages/app/webpack/parts/rules.js
Jira: [CP-1277]
<details>
</details>
[CP-1277]: https://appnroll.atlassian.net/browse/CP-1277?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1277] Fix Module parse failed: Unexpected token

- packages/app/src/backend/adapters/device-backup/device-backup.adapter.ts
- packages/app/src/backend/device-service.ts
Jira: [CP-1237]
<details>
</details>
[CP-1237]: https://appnroll.atlassian.net/browse/CP-1237?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1237] Pure do not connect again after disconnection

- packages/app/src/messages/components/thread-row.component.tsx
Jira: [CP-1113]
Removed production flag on delete button - cannot see changes on daily build
<details>
</details>
[CP-1113]: https://appnroll.atlassian.net/browse/CP-1113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1113] I can delete a single thread from the thread dropdown

- packages/app/src/data-sync/presenters/thread/thread.presenter.ts
- packages/app/src/messages/presenters/thread.presenter.ts
Jira: [CP-1139]
remove Production flag for read/unread state
<details>
</details>
[CP-1139]: https://appnroll.atlassian.net/browse/CP-1139?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1139] I can see which messages are read and unread

- packages/app/src/renderer/locales/default/en-US.json
Jira: [CP-1313]
<details>
</details>
[CP-1313]: https://appnroll.atlassian.net/browse/CP-1313?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1313] Missing plural form for successful deletion pop-up via Selection Manager

- packages/app/src/contacts/components/contacts/contacts.component.tsx
Jira: [CP-1129]
https://user-images.githubusercontent.com/15948014/170232583-7d0f4504-73b6-47e7-8962-19b9793c0864.mov
[CP-1129]: https://appnroll.atlassian.net/browse/CP-1129?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1129] Selection Manager is displayed after clicking delete bulk action

- .github/auto_assign.yml
Just updating the PR autoassigned reviewers.
> Update autoassigned pr reviewers

- packages/app/src/messages/components/messages/messages.component.tsx
- packages/app/src/messages/components/thread-details-messages.component.tsx
- packages/app/src/messages/components/thread-details.component.tsx
- packages/app/src/messages/components/thread-details.test.tsx
Jira: [CP-1316]
https://user-images.githubusercontent.com/15948014/170350365-d8ae754f-2152-4fb7-9501-62927772a34d.mov
[CP-1316]: https://appnroll.atlassian.net/browse/CP-1316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1316] Mark message as read when scrolling down thread

- packages/app/src/messages/components/message-bubble.component.tsx
Jira: [CP-993]
<details>
</details>
[CP-993]: https://appnroll.atlassian.net/browse/CP-993?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-993] Add wrapping word in message bubble

- packages/app/src/renderer/components/rest/header/header.stories.tsx
- packages/app/src/renderer/wrappers/layout-desktop-wrapper.tsx
Jira: [CP-963]
Fix size of conversation tab icon
<details>
</details>
[CP-963]: https://appnroll.atlassian.net/browse/CP-963?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-963] fix conversations tab icon

- packages/e2e/src/specs/overview/check-for-update.e2e.ts
- packages/e2e/src/specs/overview/device-update.e2e.ts
- packages/e2e/wdio.conf.ts
Jira: [CP-1323] 
Let's skip update e2e's until are ready for a run.
[CP-1323]: https://appnroll.atlassian.net/browse/CP-1323?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1323] e2e skip update

- packages/app/src/messages/components/messages/messages.component.tsx
- packages/app/src/messages/components/messages/messages.test.tsx
Jira: [CP-1331] [CP-1332]
[CP-1331]: https://appnroll.atlassian.net/browse/CP-1331?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CP-1332]: https://appnroll.atlassian.net/browse/CP-1332?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1331][CP-1332] New thread disappear during creating a new message

- packages/app/src/templates/components/templates-panel/index.ts
- packages/app/src/templates/components/templates-panel/templates-panel-ids.enum.ts
- packages/app/src/templates/components/templates-panel/templates-panel.component.test.tsx
- packages/app/src/templates/components/templates-panel/templates-panel.component.tsx
- packages/app/src/templates/components/templates-panel/templates-panel.interface.ts
- packages/app/src/templates/components/templates-panel/templates-panel.styled.tsx
Jira: [CP-526]
Implement template panel component UI
<details>
</details>
[CP-526]: https://appnroll.atlassian.net/browse/CP-526?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-526] Implement template panel component

- .gitignore
- packages/e2e/.gitignore
Jira: [CP-1321]
Removing `tmp` folder from `gitignore`
<details>
</details>
[CP-1321]: https://appnroll.atlassian.net/browse/CP-1321?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1321] Remove tmp from gitignore

- packages/app/src/messages/components/messages/messages.component.tsx
Jira: [CP-1331] [CP-1332] [CP-1337]
<details>
</details>
[CP-1331]: https://appnroll.atlassian.net/browse/CP-1331?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CP-1332]: https://appnroll.atlassian.net/browse/CP-1332?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CP-1337]: https://appnroll.atlassian.net/browse/CP-1337?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1331][CP-1332][CP-1337] New conversation logic fixed

- packages/e2e/package-lock.json
- packages/e2e/package.json
Jira: [CP-1321]
Downgrade `chromedriver` version to `80.0.2`
<details>
</details>
[CP-1321]: https://appnroll.atlassian.net/browse/CP-1321?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1321] Downgrade chromedriver version

- packages/e2e/src/specs/contacts/contacts-in-app-navigation.e2e.ts
- packages/e2e/src/specs/messages/messages-in-app-navigation.e2e.ts
- packages/e2e/src/specs/news/news-in-app-navigation.e2e.ts
- packages/e2e/src/specs/overview/overview-in-app-navigation.e2e.ts
- packages/e2e/src/specs/settings/settings-in-app-navigation.e2e.ts
Jira: [CP-1321]
Restoring awaiting for device connection timeout in E2E tests
<details>
</details>
[CP-1321]: https://appnroll.atlassian.net/browse/CP-1321?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1321] E2E Restoring connection timeouts

- packages/app/package-lock.json
- packages/app/package.json
- packages/app/webpack/parts/rules.js
> v1.3.1-rc.1

- packages/app/src/renderer/locales/default/en-US.json
- packages/app/src/templates/components/templates-list/templates-list.component.tsx
- packages/app/src/templates/components/templates/templates.component.test.tsx
- packages/app/src/templates/components/templates/templates.component.tsx
- packages/app/src/ui/components/info-popup/info-popup.component.tsx
Jira: [CP-964]
* fix dropdown label text
* fix info popup number of deleted templates message (issue after tests from CP-967)
<details>
</details>
[CP-964]: https://appnroll.atlassian.net/browse/CP-964?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-964] fix delete message

- .gitignore
- packages/app/src/data-sync/presenters/template/template.presenter.test.ts
- packages/app/src/data-sync/presenters/template/template.presenter.ts
- packages/app/src/data-sync/types/template-object.type.ts
Jira: [CP-XXX]
- `Templates` as `undefined` handled in the data-sync 
- `gitignore` updated
> `Templates` as `undefined` handled in the data-sync

- .gitignore
- packages/app/package-lock.json
- packages/app/package.json
- packages/app/src/data-sync/presenters/template/template.presenter.test.ts
- packages/app/src/data-sync/presenters/template/template.presenter.ts
- packages/app/src/data-sync/types/template-object.type.ts
> v1.4.0-rc.1

- packages/app/src/messages/components/messages/messages.component.tsx
Jira: [CP-1368]
[CP-1368]: https://appnroll.atlassian.net/browse/CP-1368?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1368] Content of the newly compiled message disappears while sending previous message

- packages/app/src/__deprecated__/renderer/utils/hooks/useTableSelect.ts
Jira: [CP-1371]
[CP-1371]: https://appnroll.atlassian.net/browse/CP-1371?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1371] Selection manager remains visible if check-marked contact deleted via drop-down instead of Delete from Selection Manager

- packages/app/src/data-sync/presenters/thread/thread.presenter.ts
- packages/app/src/feature-flags/constants/feature.enum.ts
- packages/app/src/feature-flags/features/index.ts
- packages/app/src/messages/components/thread-row.component.tsx
- packages/app/src/messages/presenters/thread.presenter.ts
Jira: [CP-1369]
- release blocker was handled by removing the mark/unread epic from the 1.4.0 scrope
[CP-1369]: https://appnroll.atlassian.net/browse/CP-1369?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1369] Messages - mark/unread epic moved to 1.5.0 scope

- packages/app/src/contacts/components/contacts/contacts.component.tsx
Jira: [CP-1371] 
- tmp solution: selection manager resetting after choosing dropdown action (to avoid bugs)
- target solution: https://appnroll.atlassian.net/browse/CP-53
[CP-1371]: https://appnroll.atlassian.net/browse/CP-1371?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1371] Selection manager remains visible if check-marked contact deleted via drop-down instead of Delete from Selection Manager - vol.2

- packages/app/src/__deprecated__/renderer/models/calls/get-pretty-caller.ts
- packages/app/src/messages/components/messages/messages.test.tsx
Jira: [CP-1373]
this is not the best solution. However, the target solution requires changes in OS API. The tech task will be created at the end of the sprint.
[CP-1373]: https://appnroll.atlassian.net/browse/CP-1373?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1373] Sending off a message for a thread which is not on top of the list will close Thread view

- packages/app/package-lock.json
- packages/app/package.json
- packages/app/src/messages/components/messages/is-thread-number-equal.helper.ts
- packages/app/src/messages/components/messages/is-thread-number-equal.test.ts
- packages/app/src/messages/components/messages/messages.component.tsx
- packages/app/src/messages/components/thread-row.component.tsx
v1.4.0 rc.3
**Scope**
- [CP-1373](https://appnroll.atlassian.net/browse/CP-1373) - fix (vol.3)
- one more feature flag conditional added to hides read/unread
- on the video attached in [CP-1373](https://appnroll.atlassian.net/browse/CP-1373) I noticed that status was changing and I don't know why so I do that just to be sure
> v1.4.0 rc.3

- packages/app/src/feature-flags/features/index.ts
- packages/app/src/messages/components/message-bubble/message-bubble.component.tsx
- packages/app/src/messages/components/message-bubble/message-bubble.styled.tsx
- packages/app/src/messages/components/thread-details-messages.component.tsx
> flag features updated

- packages/app/src/messages/components/message-bubble/message-bubble.component.tsx
Jira: [CP-1137]
- Disabling resend functionality for inbox messages
<details>
</details>
[CP-1137]: https://appnroll.atlassian.net/browse/CP-1137?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1137] Disable resend functionality for inbox messages

- packages/app/src/templates/components/templates-select-modal/templates-select-modal.component.tsx
Jira: [CP-XXX]
Fix circular dependency error on master.
Connected to CP-966. 
<details>
</details>
> Fix circular dependency error

- packages/app/package-lock.json
- packages/app/package.json
- packages/app/src/data-sync/presenters/thread/thread.presenter.test.ts
- packages/app/src/data-sync/presenters/thread/thread.presenter.ts
- packages/app/src/overview/components/overview-screens/pure-overview/pure-overview.component.test.tsx
- packages/app/src/overview/components/overview-screens/pure-overview/pure-overview.component.tsx
v1.4.2 rc.1
[CP-1444](https://appnroll.atlassian.net/browse/CP-1444) - fixed
> v1.4.2 rc.1

- package-lock.json
- package.json
- packages/app/package-lock.json
- packages/app/package.json
- packages/app/src/__deprecated__/renderer/components/core/input-text/input-text.component.tsx
- packages/app/src/__deprecated__/renderer/components/core/input-text/input-text.interface.ts
- packages/app/src/__deprecated__/renderer/components/rest/calls/call-details.component.tsx
- packages/app/src/contacts/components/contact-details/contact-details.component.tsx
- packages/e2e/package-lock.json
- packages/e2e/package.json
- packages/e2e/tsconfig.json
- packages/pure/package-lock.json
- packages/pure/package.json
Jira: [CP-906]
<details>
</details>
[CP-906]: https://appnroll.atlassian.net/browse/CP-906?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-906] bump typescript to newest version

- packages/app/src/messages/components/messages/messages.component.tsx
Jira: [CP-1455]
Fixing new conversation draft functionality
<details>
</details>
[CP-1455]: https://appnroll.atlassian.net/browse/CP-1455?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1455] Fix new conversation draft functionality

- packages/app/src/data-sync/constants/contact.constant.ts
- packages/app/src/data-sync/indexes/contact.indexer.ts
- packages/app/src/data-sync/presenters/contact/contact.presenter.test.ts
- packages/app/src/data-sync/presenters/contact/contact.presenter.ts
- packages/app/src/data-sync/types/contact-object.type.ts
Jira: [CP-1414]
Fixing contact favoured functionality 
<details>
</details>
[CP-1414]: https://appnroll.atlassian.net/browse/CP-1414?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1414] Fix contact favoured functionality

- packages/app/src/messages/components/thread-list.component.tsx
Jira: [CP-994]
<details>
</details>
[CP-994]: https://appnroll.atlassian.net/browse/CP-994?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-994] Remove focus line on messages details

- packages/app/scripts/download-configuration.ts
Jira: [N/A]
Clean up download configuration script
<details>
</details>
> Clean up/download configuration script

- packages/app/src/__deprecated__/renderer/wrappers/base-app.component.tsx
- packages/app/src/contacts/reducers/contacts.reducer.test.ts
- packages/app/src/contacts/reducers/contacts.reducer.ts
- packages/app/src/core/actions/change-location.action.test.ts
- packages/app/src/core/actions/change-location.action.ts
- packages/app/src/core/actions/index.ts
- packages/app/src/core/constants/event.constant.ts
- packages/app/src/core/hooks/index.ts
- packages/app/src/core/hooks/use-router-listener.hook.ts
- packages/app/src/core/hooks/use-router-listener.test.ts
- packages/app/src/messages/reducers/messages.interface.ts
- packages/app/src/messages/reducers/messages.reducer.test.ts
- packages/app/src/messages/reducers/messages.reducer.ts
Jira: [CP-1491]
Fixing resetting selections after tab has been changed
<details>
</details>
[CP-1491]: https://appnroll.atlassian.net/browse/CP-1491?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1491] Fixing selection resetting after location has been changed

- packages/app/src/messages/components/message-bubble/message-bubble.component.tsx
- packages/app/src/messages/components/message-bubble/message-bubble.test.tsx
Jira: [CP-1499]
Allowing resend only failed messages
<details>
</details>
[CP-1499]: https://appnroll.atlassian.net/browse/CP-1499?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1499] Allow resending only failed messages

- packages/app/src/help/components/answer/answer.component.tsx
- packages/app/src/settings/components/about/shared.tsx
Jira: [CP-949]
<details>
</details>
[CP-949]: https://appnroll.atlassian.net/browse/CP-949?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-949] Number of characters per line should be less than 80 characters

- packages/app/jest.coverage.json
- packages/app/src/contacts/helpers/contacts.helpers.ts
- packages/app/src/messages/components/messages/messages.component.tsx
- packages/app/src/messages/components/messages/messages.interface.ts
- packages/app/src/messages/components/messages/messages.test.tsx
- packages/app/src/messages/components/thread-details-sidebar.component.tsx
- packages/app/src/messages/components/thread-details.test.tsx
- packages/app/src/messages/helpers/map-to-raw-number.test.tsx
- packages/app/src/messages/helpers/map-to-raw-number.tsx
- packages/app/src/messages/messages.container.tsx
- packages/app/src/messages/services/message.service.ts
Jira: [CP-1402] [CP-1486] [CP-1501]
- Fixed issues with `phone number` in message page
- [c9e3760 - Missing space for New Conversation fixed](https://github.com/mudita/mudita-center/pull/881/commits/c9e37609c4ba964b72925e9a4fa0b81c00c18a4d)
- [67a2c04 - Managing phone number with dialing codes was implemented correctly](https://github.com/mudita/mudita-center/pull/881/commits/67a2c0479719854165471290bf70953ae13aa721)
For test please use Pure_1.3.0-rc.8
[CP-1402]: https://appnroll.atlassian.net/browse/CP-1402?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CP-1486]: https://appnroll.atlassian.net/browse/CP-1486?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CP-1501]: …
> [CP-1402][CP-1486][CP-1501] Fixed issues with `phone number` in message page

- packages/app/src/contacts/helpers/convert-contacts/map-contacts-to-v-card-strings.test.ts
- packages/app/src/contacts/helpers/convert-contacts/map-contacts-to-v-card-strings.ts
> Export with empty full name fixed

- packages/app/src/contacts/components/contact-simple-list/contact-simple-list.component.tsx
- packages/app/src/contacts/components/contact-simple-list/contact-simple-list.interface.ts
- packages/app/src/contacts/components/contact-simple-list/contact-simple-list.styled.tsx
- packages/app/src/contacts/components/contact-simple-list/contact-simple-list.test.tsx
- packages/app/src/contacts/components/contacts-select-modal/contacts-select-modal.component.tsx
- packages/app/src/contacts/data-structures/contacts-hash-table.structure.test.tsx
- packages/app/src/contacts/data-structures/contacts-hash-table.structure.ts
- packages/app/src/contacts/data-structures/favourite-contacts-hash-table.structure.test.ts
- packages/app/src/contacts/data-structures/favourite-contacts-hash-table.structure.ts
- packages/app/src/contacts/data-structures/index.ts
- packages/app/src/contacts/selectors/contacts-hash.selector.test.ts
- packages/app/src/contacts/selectors/favourite-contacts-hash.selector.ts
- packages/app/src/contacts/selectors/index.ts
Jira: [CP-1488]
Adding Favourite section to contact selection modal
<details>
</details>
[CP-1488]: https://appnroll.atlassian.net/browse/CP-1488?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1488] Display favorites section in contacts select modal

- packages/app/src/__deprecated__/renderer/constants/menu-elements.ts
Jira: [N/A]
Enable files manager functionality for Harmony
<details>
</details>
> Fix/enable files manager functionality for Harmony

- packages/app/src/files-manager/actions/get-files.action.test.ts
- packages/app/src/files-manager/actions/get-files.action.ts
- packages/app/src/files-manager/components/files-manager/files-manager.component.tsx
- packages/app/src/files-manager/components/files-manager/files-manager.interface.tsx
- packages/app/src/files-manager/components/files-manager/files-manager.test.tsx
- packages/app/src/files-manager/constants/device-directory.constant.ts
- packages/app/src/files-manager/controllers/files-manager.controller.ts
- packages/app/src/files-manager/files-manager.container.tsx
- packages/app/src/files-manager/requests/get-files.request.ts
- packages/app/src/files-manager/services/file-manager.service.test.ts
- packages/app/src/files-manager/services/file-manager.service.ts
Jira: [CP-682]
Enabling users to see the relaxation audio from Harmony
<details>
</details>
[CP-682]: https://appnroll.atlassian.net/browse/CP-682?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-682] Enabling users to see the relaxation audio from Harmony

- packages/app/src/templates/actions/index.ts
- packages/app/src/templates/actions/select-items.action.test.ts
- packages/app/src/templates/actions/select-items.action.ts
- packages/app/src/templates/components/templates-list/templates-list.component.test.tsx
- packages/app/src/templates/components/templates-list/templates-list.component.tsx
- packages/app/src/templates/components/templates-list/templates-list.interface.ts
- packages/app/src/templates/components/templates-panel/templates-panel.component.test.tsx
- packages/app/src/templates/components/templates-panel/templates-panel.component.tsx
- packages/app/src/templates/components/templates-panel/templates-panel.interface.ts
- packages/app/src/templates/components/templates/templates.component.test.tsx
- packages/app/src/templates/components/templates/templates.component.tsx
- packages/app/src/templates/components/templates/templates.interface.ts
- packages/app/src/templates/constants/event.enum.ts
- packages/app/src/templates/reducers/template.interface.ts
- packages/app/src/templates/reducers/template.reducer.test.ts
- packages/app/src/templates/reducers/template.reducer.ts
- packages/app/src/templates/template.container.tsx
Jira: [CP-1491]
Adding selection functionality to templates
<details>
</details>
[CP-1491]: https://appnroll.atlassian.net/browse/CP-1491?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1491] Fix templates selection

- packages/app/src/messages/components/messages/messages.component.tsx
- packages/app/src/ui/components/modal-dialog/modal-dialog.component.tsx
Jira: [CP-1505]
- add modal overlay click
- add hiding messageDeletingConfirmation modal on close
<details>
</details>
[CP-1505]: https://appnroll.atlassian.net/browse/CP-1505?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1505] Clicking anywhere except on DELETE button freezes MC on Delete confirmation pop-up

- packages/app/src/__deprecated__/backend/adapters/pure-phone/pure-phone.adapter.ts
Jira: [CP-XXX]
Increase timeout during update from 5 to 10 minutes
PS this is the second time when the update timeout has been increased. It's a high probability, that this configuration should be moved to contentful.
> Increase timeout during update from 5 to 10 minutes

- packages/app/src/overview/components/overview-screens/harmony-overview/harmony-overview.component.tsx
- packages/app/src/overview/components/overview-screens/pure-overview/pure-overview.component.test.tsx
- packages/app/src/overview/components/overview-screens/pure-overview/pure-overview.component.tsx
- packages/app/src/overview/components/updating-force-modal-flow/updating-force-modal-flow.component.test.tsx
- packages/app/src/overview/components/updating-force-modal-flow/updating-force-modal-flow.component.tsx
- packages/app/src/overview/components/updating-force-modal-flow/updating-force-modal-flow.enum.ts
- packages/app/src/overview/components/updating-force-modal-flow/updating-force-modal-flow.interface.ts
- packages/app/src/overview/overview.container.tsx
Jira: [CP-1503]
Scope:
* Now forced OS update (for outdates versions) works fine
* Small refactor of `UpdatingForceModalFlow` (move interfaces, enums to external files)
Testing notes included in the Jira task
<details>
</details>
[CP-1503]: https://appnroll.atlassian.net/browse/CP-1503?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1503] fix pure force update for outdated OS

- packages/app/src/overview/components/overview-screens/harmony-overview/harmony-overview.component.test.tsx
- packages/app/src/overview/components/overview-screens/harmony-overview/harmony-overview.component.tsx
Jira: [CP-1517]
A PR related to https://github.com/mudita/mudita-center/pull/891, but this one fixes force update of Harmony. Testing notes included in the Jira task.
<details>
</details>
[CP-1517]: https://appnroll.atlassian.net/browse/CP-1517?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1517] fix harmony force update on outdated os

- packages/app/src/templates/components/templates-select-modal/templates-select-modal.component.tsx
- packages/app/src/templates/components/templates-select-modal/templates-select-modal.styled.tsx
Jira: [CP-1509]
<details>
</details>
[CP-1509]: https://appnroll.atlassian.net/browse/CP-1509?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1509] The Use template dedicated window lacks scrollbar

- packages/app/src/core/models/base.model.ts
- packages/app/src/messages/models/thread.model.ts
Jira: [CP-1404]
Removing message after has been thread removed
<details>
</details>
[CP-1404]: https://appnroll.atlassian.net/browse/CP-1404?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1504] Removing message after has been thread removed

- packages/app/src/messages/components/messages/messages.component.tsx
Jira: [CP-1500]
<details>
</details>
[CP-1500]: https://appnroll.atlassian.net/browse/CP-1500?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1500] No confirmation pop-up when clicking on Detele thread button

- packages/app/src/__deprecated__/renderer/locales/default/en-US.json
- packages/app/src/messages/components/thread-details-text-area.component.tsx
Jira: [CP-1487]
<details>
</details>
[CP-1487]: https://appnroll.atlassian.net/browse/CP-1487?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1487] Add tooltip to attach template and attach contact

- packages/app/jest.coverage.json
- packages/app/src/ui/components/modal-dialog/modal-dialog.component.tsx
Jira: [CP-1505]
I added closing on click outside the modal but we didn't have this feature in the previous versions. Removed
<details>
</details>
[CP-1505]: https://appnroll.atlassian.net/browse/CP-1505?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1505] fix overlay click

- packages/app/src/__deprecated__/renderer/components/core/button/button.config.ts
- packages/app/src/__deprecated__/renderer/components/core/button/button.styled.elements.tsx
- packages/app/src/__deprecated__/renderer/components/core/button/tests/__snapshots__/button.test.tsx.snap
- packages/app/src/__deprecated__/renderer/components/rest/header/__snapshots__/header.test.tsx.snap
- packages/app/src/__deprecated__/renderer/components/rest/header/__snapshots__/tab.test.tsx.snap
- packages/app/src/__deprecated__/renderer/components/rest/header/tab.component.tsx
- packages/app/src/__deprecated__/renderer/styles/theming/theme.ts
Jira: [CP-1511]
<details>
</details>
[CP-1511]: https://appnroll.atlassian.net/browse/CP-1511?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1511] fix icon conversation tab button

- packages/app/src/__deprecated__/renderer/components/core/text/text.component.tsx
- packages/app/src/messages/components/thread-row-name/index.ts
- packages/app/src/messages/components/thread-row-name/thread-row-name-test-ids.ts
- packages/app/src/messages/components/thread-row-name/thread-row-name.component.tsx
- packages/app/src/messages/components/thread-row-name/thread-row-name.interface.ts
- packages/app/src/messages/components/thread-row-name/thread-row-name.test.tsx
- packages/app/src/messages/components/thread-row.component.tsx
Jira: [CP-1513]
Just displays `#1` or `#2` when contact has secondary phone number. See attached screen.
<details>
</details>
[CP-1513]: https://appnroll.atlassian.net/browse/CP-1513?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1513] display number designation for new messages

- packages/app/src/__deprecated__/renderer/components/core/button/button.styled.elements.tsx
- packages/app/src/__deprecated__/renderer/components/rest/header/__snapshots__/header.test.tsx.snap
- packages/app/src/__deprecated__/renderer/components/rest/header/__snapshots__/tab.test.tsx.snap
- packages/app/src/__deprecated__/renderer/styles/theming/theme.ts
Jira: [CP-XXX]
Quick fix for removing "autorem" from snapshot
connected to CP-1511
<details>
</details>
> Fix auto width

- packages/app/package-lock.json
- packages/app/package.json
- packages/app/src/data-sync/presenters/contact/contact.presenter.test.ts
- packages/app/src/data-sync/presenters/contact/contact.presenter.ts
- packages/app/src/data-sync/types/contact-object.type.ts
Jira: [CP 1515]
- Added supports for `contact_groups` & `contact_match_groups` for `contacts` table
> [CP 1515] Sync issue 1.5.0 RC1 + Pure 1.3.0

- packages/app/src/messages/components/messages/messages.component.tsx
Jira: [CP-1502]
Fixes problem that appears after deleting thread and quickly going to "new message" form and opening any modal (e.g. browse contacts or attach template). See attached movie
<details>
https://user-images.githubusercontent.com/41268731/183906336-774fc946-4d0d-4c34-a974-481e47182d36.mov
</details>
[CP-1502]: https://appnroll.atlassian.net/browse/CP-1502?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1502] fix problem with auto closing windows

- packages/app/src/messages/repositories/thread.repository.test.ts
- packages/app/src/messages/repositories/thread.repository.ts
- packages/app/src/outbox/services/message-entry-handler.service.test.ts
- packages/app/src/outbox/services/message-entry-handler.service.ts
- packages/app/src/outbox/services/outbox.factory.ts
Jira: [CP-1521]
Fixing missing phone number in message outbox service
<details>
</details>
[CP-1521]: https://appnroll.atlassian.net/browse/CP-1521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1521] Fix missing phone number

- packages/app/src/device-file-system/commands/file-delete.command.test.ts
- packages/app/src/device-file-system/commands/file-delete.command.ts
- packages/app/src/device-file-system/constants/error.enum.ts
- packages/app/src/files-manager/actions/base.action.test.ts
- packages/app/src/files-manager/actions/base.action.ts
- packages/app/src/files-manager/actions/delete-files.action.test.ts
- packages/app/src/files-manager/actions/delete-files.action.ts
- packages/app/src/files-manager/components/delete-files-modals/delete-files-modals.component.tsx
- packages/app/src/files-manager/components/delete-files-modals/delete-files-modals.interface.ts
- packages/app/src/files-manager/components/delete-files-modals/delete-files-modals.test.tsx
- packages/app/src/files-manager/components/files-manager/files-manager.component.tsx
- packages/app/src/files-manager/components/files-manager/files-manager.interface.tsx
- packages/app/src/files-manager/components/files-manager/files-manager.test.tsx
- packages/app/src/files-manager/components/files-storage-list/files-storage-list.styled.tsx
- packages/app/src/files-manager/components/files-storage/files-storage.component.tsx
- packages/app/src/files-manager/components/files-storage/files-storage.interface.ts
- packages/app/src/files-manager/components/files-storage/files-storage.test.tsx
- packages/app/src/files-manager/constants/controller.constant.ts
- packages/app/src/files-manager/constants/errors.enum.ts
- packages/app/src/files-manager/constants/event.enum.ts
- packages/app/src/files-manager/controllers/files-manager.controller.ts
- packages/app/src/files-manager/files-manager.container.tsx
- packages/app/src/files-manager/files-manager.module.ts
- packages/app/src/files-manager/reducers/files-manager.interface.ts
- packages/app/src/files-manager/reducers/files-manager.reducer.test.ts
- packages/app/src/files-manager/reducers/files-manager.reducer.ts
- packages/app/src/files-manager/requests/delete-files.request.ts
- packages/app/src/files-manager/services/file-manager.service.test.ts
- packages/app/src/files-manager/services/file-manager.service.ts
- packages/app/src/ui/components/info-popup/info-popup.component.tsx
Jira: [CP-1532]
[CP-1532]: https://appnroll.atlassian.net/browse/CP-1532?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1532] Files deleting logic implemented

- packages/app/src/__deprecated__/renderer/locales/default/en-US.json
- packages/app/src/files-manager/components/files-manager-panel/files-manager-panel-ids.enum.ts
- packages/app/src/files-manager/components/files-manager-panel/files-manager-panel.component.test.tsx
- packages/app/src/files-manager/components/files-manager-panel/files-manager-panel.component.tsx
- packages/app/src/files-manager/components/files-manager-panel/files-manager-panel.interface.ts
- packages/app/src/files-manager/components/files-manager-panel/files-manager-panel.styled.tsx
- packages/app/src/files-manager/components/files-manager-search-input/files-manager-search-input.test.tsx
- packages/app/src/files-manager/components/files-manager-search-input/files-manager-search-input.tsx
- packages/app/src/files-manager/components/files-manager/files-manager.component.tsx
- packages/app/src/files-manager/components/files-manager/files-manager.test.tsx
- packages/app/src/files-manager/components/files-storage-list/files-storage-list-test-ids.enum.ts
- packages/app/src/files-manager/components/files-storage-list/files-storage-list.component.tsx
- packages/app/src/files-manager/components/files-storage-list/files-storage-list.test.tsx
- packages/app/src/files-manager/components/files-storage/files-storage.component.tsx
- packages/app/src/files-manager/components/files-storage/files-storage.interface.ts
- packages/app/src/files-manager/components/files-storage/files-storage.test.tsx
- packages/app/src/files-manager/helpers/is-file-match.helper.test.ts
- packages/app/src/files-manager/helpers/is-file-match.helper.ts
- packages/app/src/files-manager/helpers/use-files-filter.hook.test.ts
- packages/app/src/files-manager/helpers/use-files-filter.hook.ts
Jira: [CP-684]
I want to search files - implemented
[CP-684]: https://appnroll.atlassian.net/browse/CP-684?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-684] I want to search files - implemented

- packages/app/src/__deprecated__/renderer/constants/menu-elements.ts
Jira: [CP-XXX]
`MenuFilesManager` hides for Harmony
> `MenuFilesManager` hides for Harmony

- packages/app/src/__deprecated__/renderer/models/external-providers/outlook/outlook.helpers.ts
- packages/app/src/__deprecated__/renderer/models/external-providers/outlook/outlook.interface.ts
- packages/app/src/__deprecated__/renderer/models/external-providers/outlook/outlook.ts
Jira: [CP-1516]
- Import from outlook fixed by pagination handled
[CP-1516]: https://appnroll.atlassian.net/browse/CP-1516?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1516] Import from outlook fixed by pagination handled

- packages/app/src/contacts/components/contact-panel/contact-panel.component.tsx
- packages/app/src/contacts/components/contact-panel/contact-panel.test.tsx
- packages/app/src/contacts/contacts.container.tsx
- packages/app/src/contacts/reducers/contacts.interface.ts
- packages/app/src/contacts/reducers/contacts.reducer.test.ts
- packages/app/src/contacts/reducers/contacts.reducer.ts
Jira: [CP-1525]
Fixing selection manager on `contact` view
<details>
</details>
[CP-1525]: https://appnroll.atlassian.net/browse/CP-1525?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1525] Fix contacts selection manager

- packages/app/src/search/mediators/searcher.mediator.test.ts
- packages/app/src/search/mediators/searcher.mediator.ts
- packages/app/src/search/search.module.ts
- packages/app/src/search/searchers/contact.searcher.test.ts
- packages/app/src/search/searchers/contact.searcher.ts
- packages/app/src/search/searchers/index.ts
- packages/app/src/search/searchers/message.searcher.test.ts
- packages/app/src/search/searchers/template.searcher.test.ts
- packages/app/src/search/searchers/template.searcher.ts
- packages/app/src/search/searchers/thread.searcher.test.ts
- packages/app/src/search/searchers/thread.searcher.ts
Jira: [CP-1551]
Containes implementation of:
- Thread searcher
- Contact searcher
- Template searcher
<details>
</details>
[CP-1551]: https://appnroll.atlassian.net/browse/CP-1551?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1551] Implements additional searchers

- packages/app/src/__deprecated__/renderer/utils/form-validators.test.tsx
- packages/app/src/__deprecated__/renderer/utils/form-validators.ts
- packages/app/src/contacts/components/contact-edit/contact-edit.component.tsx
- packages/app/src/contacts/components/contact-list/contact-list.styled.tsx
- packages/app/src/contacts/components/contact-simple-list-item-avatar/contact-simple-list-item-avatar.styled.tsx
Jira: [CP-1524]
Scope (see attached screen and video):
* add validation message during editing already existing contact with long name
* show shortened version of the veeeery long contact that appears on the contact list or browse/attach contacts
<details>
https://user-images.githubusercontent.com/41268731/188099918-3b201913-48ae-4eb4-9807-5f7359bb9bde.mov
</details>
[CP-1524]: https://appnroll.atlassian.net/browse/CP-1524?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [Cp-1524] long contact improvements after QA

- packages/app/src/data-sync/presenters/thread/thread.presenter.ts
Jira: [N/A]
- Fixing unexpected `undefined` in threads presenter
<details>
</details>
> Fix/unexpected `undefined` in threads presenter

- packages/app/src/__deprecated__/renderer/components/core/input-search/input-search.component.tsx
Jira: [CP-1582]
<details>
</details>
[CP-1582]: https://appnroll.atlassian.net/browse/CP-1582?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1582] Remove See all button when empty search results

- packages/app/src/contacts/components/contacts/contacts.component.tsx
Jira: [CP-1576]
<details>
</details>
[CP-1576]: https://appnroll.atlassian.net/browse/CP-1576?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1576] remove selection manager when adding new contact

- packages/app/src/messages/components/messages/messages.component.tsx
Jira: [CP-1545]
refresh activeThread
<details>
</details>
[CP-1545]: https://appnroll.atlassian.net/browse/CP-1545?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1545] Mark as unread button does not work if used on a message which was unread

- .env.example
- packages/app/src/__deprecated__/main/main.ts
- packages/app/src/__deprecated__/renderer/store/index.ts
- packages/app/src/core/application.module.ts
Just to improve dev experience
> Allow to turn off loggers in dev mode

- packages/app/src/contact-support/actions/send-ticket.action.test.ts
- packages/app/src/contact-support/actions/send-ticket.action.ts
Jira: [CP-1441]
Ticket description field formatting
<details>
</details>
[CP-1441]: https://appnroll.atlassian.net/browse/CP-1441?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1441] Ticket description formatting

- packages/app/src/data-sync/presenters/contact/contact.presenter.test.ts
- packages/app/src/data-sync/presenters/contact/contact.presenter.ts
Jira: [CP-1554]
Scope:
* allow to sync contacts that does not have phone number defined
<details>
</details>
[CP-1554]: https://appnroll.atlassian.net/browse/CP-1554?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1554] sync properly contacts without any number

- packages/app/src/feature-flags/constants/feature.enum.ts
- packages/app/src/feature-flags/features/index.ts
- packages/app/src/overview/components/overview-screens/harmony-overview/harmony-overview.component.test.tsx
- packages/app/src/overview/components/overview-screens/harmony-overview/harmony-overview.component.tsx
- packages/app/src/overview/components/overview-screens/pure-overview/pure-overview.component.test.tsx
- packages/app/src/overview/components/overview-screens/pure-overview/pure-overview.component.tsx
Jira: [CP-1540]
<details>
</details>
[CP-1540]: https://appnroll.atlassian.net/browse/CP-1540?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1540] add feature flag for force update process

- packages/app/src/__deprecated__/main/main.ts
- packages/app/src/contacts/backend/export-contacts.ts
Jira: [CP-1347]
Scope:
* adds file extension to exported contacts file on Linux system 
https://user-images.githubusercontent.com/41268731/189132763-47a949ae-cc90-4933-8d8e-8cae32e36f66.mov
<details>
</details>
[CP-1347]: https://appnroll.atlassian.net/browse/CP-1347?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1374] exported contacts file now have extention in Linux

- packages/app/src/__deprecated__/backend/adapters/device-backup/device-backup-adapter.class.ts
- packages/app/src/__deprecated__/backend/adapters/device-backup/device-backup-fake.adapter.ts
- packages/app/src/__deprecated__/backend/adapters/device-backup/device-backup.adapter.ts
- packages/app/src/__deprecated__/backend/device-backup-service/device-backup-service.ts
- packages/app/src/data-sync/services/data-sync.service.ts
- packages/app/src/feature-flags/constants/feature.enum.ts
- packages/app/src/feature-flags/features/index.ts
- packages/pure/src/endpoints/backup.types.ts
Jira: [CP-1485]
- Implementing backup categories
Current functionality is disabled due to OS part unavailability.
<details>
</details>
[CP-1485]: https://appnroll.atlassian.net/browse/CP-1485?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1485] Implementing backup categories

- packages/app/src/messages/components/messages/messages.component.tsx
Jira: [CP-1583]
add activeSearchDropdown state
<details>
</details>
[CP-1583]: https://appnroll.atlassian.net/browse/CP-1583?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1583] Thread remains highlighted when typing another query in Search message bar

- packages/app/src/__deprecated__/renderer/components/core/input-search/input-search.component.tsx
- packages/app/src/__deprecated__/renderer/components/core/input-search/input-search.test.tsx
Jira: [CP-1585]
Scrolling to the active element in the search result list
<details>
</details>
[CP-1585]: https://appnroll.atlassian.net/browse/CP-1585?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1585] Scrolling to the active element in the search result list

- packages/app/src/contacts/components/contact-panel/contact-panel.component.tsx
Jira: [CP-1593]
<details>
</details>
[CP-1593]: https://appnroll.atlassian.net/browse/CP-1593?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-1593 Remove reseting rows on canceling contact delete

- packages/app/src/contacts/helpers/map-vcfs-to-contacts/contact-with-email-list.vcf
- packages/app/src/contacts/helpers/map-vcfs-to-contacts/map-vcfs-to-contacts.test.ts
- packages/app/src/contacts/helpers/map-vcfs-to-contacts/map-vcfs-to-contacts.ts
- packages/app/src/contacts/presenters/contact.presenter.test.ts
- packages/app/src/contacts/presenters/contact.presenter.ts
- packages/app/src/contacts/services/contact.service.test.ts
- packages/pure/src/endpoints/contact.types.ts
Jira: [CP-1591]
Improve contacts importing
<details>
</details>
[CP-1591]: https://appnroll.atlassian.net/browse/CP-1591?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1591] Fix list of emails assertion during contacts import

- packages/app/src/data-sync/presenters/thread/thread.presenter.test.ts
- packages/app/src/data-sync/presenters/thread/thread.presenter.ts
- packages/app/src/data-sync/types/thread-object.type.ts
Jira: [CP-1602]
Scope:
* solves a problem with a situation when user has messages, but does not have contacts (before a fix - it was not showing any message thread, while it should)
<details>
</details>
[CP-1602]: https://appnroll.atlassian.net/browse/CP-1602?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1602] messages are shown even if user has no contacts

- packages/app/src/contacts/components/contacts/contacts.component.tsx
Jira: [CP-1592]
<details>
</details>
[CP-1592]: https://appnroll.atlassian.net/browse/CP-1592?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1592] Reset addedContactCount when closing import

- packages/app/src/contacts/components/contact-list/contact-list.styled.tsx
- packages/app/src/contacts/components/virtualized-contact-list-item/virtualized-contact-list-item.component.tsx
- packages/app/src/contacts/components/virtualized-contact-list-item/virtualized-contact-list-item.test.tsx
Jira: [CP-1577]
<details>
</details>
[CP-1577]: https://appnroll.atlassian.net/browse/CP-1577?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1577] fix long phone numbers display

- packages/app/src/messages/reducers/messages.reducer.test.ts
- packages/app/src/messages/reducers/messages.reducer.ts
Jira: [CP-1603]
Scope:
* clear "error" property on start of the new action
* add missing tests for some reducer actions
<details>
</details>
[CP-1603]: https://appnroll.atlassian.net/browse/CP-1603?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1603]: clear error on pending actions, add missing message reducer tests

- packages/app/package.json
Jira: [CP-XXX]
<details>
</details>
> Bump app version to 1.5.3-rc.2

- packages/app/src/__deprecated__/renderer/components/core/input-search/input-search.component.tsx
Jira: [CP-1623]
* fix navigation by a keyboard that was stopping
* fix scrolling behavior 
Also, I have a recommendation to change the search dropdown component, so that there will be no scroll, only 8 first results. What do you think about it?  
<details>
</details>
[CP-1623]: https://appnroll.atlassian.net/browse/CP-1623?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1623] fix search dropdown scrolling

- packages/app/src/messages/components/messages/messages.component.tsx
- packages/app/src/templates/components/templates/templates.component.tsx
Jira: [CP-1359]
Change after Michał's suggestion, that deleting states shouldn't depend on notifications.
<details>
</details>
[CP-359]: https://appnroll.atlassian.net/browse/CP-359?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CP-1359]: https://appnroll.atlassian.net/browse/CP-1359?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1359] fix dependencies of deleting states

- packages/app/src/__deprecated__/renderer/components/rest/data-modal/data.modals.tsx
Jira: [CP-1628]
<details>
</details>
[CP-1628]: https://appnroll.atlassian.net/browse/CP-1628?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1628] Remove x button on deleting contact modal

- packages/app/src/__deprecated__/backend/adapters/device-backup/device-backup.adapter.ts
- packages/app/src/__deprecated__/backend/device-backup-service/device-backup-service.ts
- packages/app/src/backup/services/backup-create.service.ts
- packages/pure/src/endpoints/backup.types.ts
Jira: [CP-1426]
Adding backup category to status request
<details>
</details>
[CP-1426]: https://appnroll.atlassian.net/browse/CP-1426?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1426] Adding backup category to sync status request

- packages/app/src/__deprecated__/backend/device-service.ts
Jira: [CP-1644]
<details>
</details>
[CP-1644]: https://appnroll.atlassian.net/browse/CP-1644?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1644] Fix infinity loop in phone lock requests

- packages/app/src/__deprecated__/backend/device-service.ts
> CP-1644 - to 1.6.0

- packages/app/src/messages/components/message-bubble/message-bubble.component.tsx
- packages/app/src/messages/components/message-bubble/message-bubble.test.tsx
Jira: [CP-1609]
<details>
</details>
[CP-1609]: https://appnroll.atlassian.net/browse/CP-1609?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1609] remove dropdown when message sending

- packages/app/src/overview/components/backup-modal-dialogs/backup-modal-dialogs.tsx
Jira: [CP-1625]
We had prepared text for description but did not use it in the right place. 
<details>
</details>
[CP-1625]: https://appnroll.atlassian.net/browse/CP-1625?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1625] fix backup failure modal description

- packages/app/src/crash-dump/actions/download-crash-dump.action.test.ts
- packages/app/src/crash-dump/actions/download-crash-dump.action.ts
Jira: [CP-1640]
<details>
</details>
[CP-1640]: https://appnroll.atlassian.net/browse/CP-1640?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1640] add formatting to crash dump message

- packages/app/src/__deprecated__/renderer/wrappers/app-update-step-modal/app-update-step-modal.component.tsx
Jira: [CP-1673]
[CP-1673]: https://appnroll.atlassian.net/browse/CP-1673?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1673] Force Mudita Center update doesn't works

- packages/app/src/backup/actions/start-backup-device.action.test.ts
- packages/app/src/backup/types/create-device-backup.type.ts
- packages/app/src/data-sync/services/data-sync.service.ts
Jira: [CP-1392]
Fix device file system service
<details>
</details>
[CP-1392]: https://appnroll.atlassian.net/browse/CP-1392?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1392] Fixing device files system service

- packages/app/src/overview/components/update-os-modals/checking-updates-modal/checking-updates-modal.component.tsx
- packages/app/src/overview/components/update-os-modals/checking-updates-modal/checking-updates-modal.interface.ts
- packages/app/src/overview/components/update-os-modals/dev-update-modal/dev-update-modal.component.tsx
- packages/app/src/overview/components/update-os-modals/dev-update-modal/dev-update-modal.inteface.ts
- packages/app/src/overview/components/update-os-modals/downloading-update-cancelled-modal/downloading-update-cancelled-modal.component.tsx
- packages/app/src/overview/components/update-os-modals/downloading-update-cancelled-modal/downloading-update-cancelled-modal.interface.ts
- packages/app/src/overview/components/update-os-modals/downloading-update-finished-modal/downloading-update-finished-modal.component.tsx
- packages/app/src/overview/components/update-os-modals/downloading-update-finished-modal/downloading-update-finished-modal.interface.ts
- packages/app/src/overview/components/update-os-modals/downloading-update-interrupted-modal/downloading-update-interrupted-modal.component.tsx
- packages/app/src/overview/components/update-os-modals/downloading-update-interrupted-modal/downloading-update-interrupted-modal.interface.ts
- packages/app/src/overview/components/update-os-modals/downloading-update-modal/downloading-update-modal.component.tsx
- packages/app/src/overview/components/update-os-modals/downloading-update-modal/downloading-update-modal.interface.ts
- packages/app/src/overview/components/update-os-modals/too-low-battery-modal/too-low-battery-modal.component.tsx
- packages/app/src/overview/components/update-os-modals/too-low-battery-modal/too-low-battery-modal.interface.ts
- packages/app/src/overview/components/update-os-modals/update-available-modal/update-available-modal.component.tsx
- packages/app/src/overview/components/update-os-modals/update-available-modal/update-available-modal.interface.ts
- packages/app/src/overview/components/update-os-modals/update-not-available-modal/update-not-available-modal.component.tsx
- packages/app/src/overview/components/update-os-modals/update-not-available-modal/update-not-available-modal.interface.ts
- packages/app/src/overview/components/update-os-modals/updating-failure-with-help-modal/updating-failure-with-help-modal.component.tsx
- packages/app/src/overview/components/update-os-modals/updating-failure-with-help-modal/updating-failure-with-help-modal.interface.ts
- packages/app/src/overview/components/update-os-modals/updating-spinner-modal/updating-spinner-modal.component.tsx
- packages/app/src/overview/components/update-os-modals/updating-spinner-modal/updating-spinner-modal.interface.ts
- packages/app/src/overview/components/update-os-modals/updating-success-modal/updating-success-modal.component.tsx
- packages/app/src/overview/components/update-os-modals/updating-success-modal/updating-success-modal.interface.ts
Jira: [CP-1717]
Scope:
* add missing props for update os modals (mostly test ids)
* added to reduce the size of the upcoming PR's
<details>
</details>
[CP-1717]: https://appnroll.atlassian.net/browse/CP-1717?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1717] add missing props to update os modals

- packages/app/src/__deprecated__/renderer/wrappers/root-wrapper.tsx
- packages/app/src/modals-manager/components/modals-manager.component.tsx
- packages/app/src/overview/components/update-os-modals/downloading-update-interrupted-modal/downloading-update-interrupted-modal.component.tsx
- packages/app/src/update/components/update-os-interrupted-flow/index.ts
- packages/app/src/update/components/update-os-interrupted-flow/update-os-interrupted-flow-test-ids.ts
- packages/app/src/update/components/update-os-interrupted-flow/update-os-interrupted-flow.component.tsx
- packages/app/src/update/components/update-os-interrupted-flow/update-os-interrupted-flow.container.tsx
- packages/app/src/update/components/update-os-interrupted-flow/update-os-interrupted-flow.interface.ts
- packages/app/src/update/components/update-os-interrupted-flow/update-os-interrupted-flow.test.tsx
- packages/app/src/update/listeners/device-attached.listener.ts
- packages/app/src/update/listeners/device-detached.listener.ts
- packages/app/src/update/listeners/index.ts
- packages/app/src/update/selectors/already-downloaded-releases.selector.test.ts
- packages/app/src/update/selectors/already-downloaded-releases.selector.ts
- packages/app/src/update/selectors/index.ts
Jira: [CP-1686]
Scope:
* handle situation when cable is disconnected during downloading os update (see attached movie)
<details>
<summary><b>Movie</b>
</summary>
https://user-images.githubusercontent.com/41268731/207374482-d9c024fb-dc01-4b8c-9a81-efee8f417fe3.mov
</details>
[CP-1686]: https://appnroll.atlassian.net/browse/CP-1686?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1686] handle cable disconnection during os download

- packages/app/src/__deprecated__/api/mudita-center-server/client.ts
- packages/app/src/__deprecated__/main/functions/create-download-listener-registrar.ts
- packages/app/src/update/actions/start-update-os/start-update-os.action.ts
- packages/app/src/update/dto/release-manifest.object.ts
- packages/app/src/update/presenters/github-release.presenter.test.ts
- packages/app/src/update/presenters/github-release.presenter.ts
- packages/app/src/update/services/releases.service.test.ts
Jira: [CP-1686]
Scope:
* do not delete release after downloading it
* fix problem with mapping between OsRelease and ReleaseManifest (invalid type for "size")
<details>
</details>
[CP-1686]: https://appnroll.atlassian.net/browse/CP-1686?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1686] downloads are not deleted immediately

- packages/app/src/overview/components/overview-screens/harmony-overview/harmony-overview.component.tsx
- packages/app/src/overview/components/overview-screens/pure-overview/pure-overview.component.tsx
- packages/app/src/overview/components/update-os-modals/downloading-update-finished-modal/downloading-update-finished-modal.component.tsx
- packages/app/src/update/services/device-update.service.ts
Jira: [CP-1732] [CP-1747]
[CP-1732]: https://appnroll.atlassian.net/browse/CP-1732?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CP-1747]: https://appnroll.atlassian.net/browse/CP-1747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1732][CP-1747] Handle undefined device during on the update process

- packages/app/src/files-manager/constants/device-directory.constant.ts
Jira: [CP-1758]
Music path updated
[CP-1758]: https://appnroll.atlassian.net/browse/CP-1758?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1758] Music path updated

- packages/app/src/device/types/mudita-os/serialport-request.type.ts
- packages/app/src/metadata/listeners/set-value.listener.ts
- packages/app/src/metadata/requests/set-value.request.ts
- packages/app/src/update/actions/start-update-os/start-update-os.action.ts
- packages/app/src/update/services/device-update.service.test.ts
- packages/app/src/update/services/device-update.service.ts
- packages/app/src/update/update.module.ts
Jira: [CP-XXX]
UDM update flow handled
> UDM update flow handled

- packages/app/src/__deprecated__/renderer/wrappers/base-app.component.tsx
- packages/app/src/device/reducers/device.reducer.test.ts
- packages/app/src/device/reducers/device.reducer.ts
Jira: [CP-1686]
Scope:
* handle properly base-app states
<details>
</details>
[CP-1686]: https://appnroll.atlassian.net/browse/CP-1686?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1686] fixes for base-app states

- packages/app/src/data-sync/observers/device-connection.observer.test.ts
- packages/app/src/data-sync/observers/device-connection.observer.ts
- packages/app/src/device-manager/services/device-manager.service.ts
- packages/app/src/device/constants/controller.constant.ts
- packages/app/src/device/controllers/device.controller.ts
- packages/app/src/device/requests/set-updating.request.ts
- packages/app/src/device/services/device.service.ts
- packages/app/src/update/actions/start-update-os/start-update-os.action.ts
- packages/app/src/update/services/device-update.service.ts
Jira: [CP-XXX]
Handle sync process during updating
> Handle sync process during updating

- packages/app/src/feature-flags/features/index.ts
- packages/app/src/settings/static/default-app-configuration.json
Jira: [CP-XXX]
Force update flag disabled until handle CP-1708
> Force update flag disabled until handle CP-1708

- packages/app/scripts/download-configuration.ts
- packages/app/src/__deprecated__/api/mudita-center-server/mudita-center-server-routes.ts
- packages/app/src/settings/services/configuration.service.ts
Jira: [CP-1788]
[CP-1788]: https://appnroll.atlassian.net/browse/CP-1788?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1788] Handle Version as query params for ConfigurationService

- packages/app/src/backup/services/backup-create.service.test.ts
- packages/app/src/backup/services/backup-create.service.ts
Jira: [CP-1764]
<details>
</details>
[CP-1764]: https://appnroll.atlassian.net/browse/CP-1764?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1764] Fixed logic to check `free` value in backup validation

- packages/app/src/backup/services/backup-create.service.test.ts
- packages/app/src/backup/services/backup-create.service.ts
> [CP-1764] Fixed logic to by updating BackupInProgress state when error is return

- packages/app/src/__deprecated__/renderer/components/rest/menu/menu.container.tsx
- packages/app/src/__deprecated__/renderer/locales/default/en-US.json
- packages/app/src/__deprecated__/renderer/wrappers/base-app.component.tsx
- packages/app/src/connecting/components/connecting-error.enum.tsx
- packages/app/src/connecting/components/connecting.component.tsx
- packages/app/src/connecting/components/connecting.test.tsx
- packages/app/src/connecting/connecting.container.ts
- packages/app/src/overview/components/overview-screens/harmony-overview/harmony-overview.component.interface.ts
- packages/app/src/overview/components/overview-screens/harmony-overview/harmony-overview.component.test.tsx
- packages/app/src/overview/components/overview-screens/harmony-overview/harmony-overview.component.tsx
- packages/app/src/overview/components/overview-screens/helpers/use-update-flow-state.hook.tsx
- packages/app/src/overview/components/overview-screens/helpers/use-update-flow-state.test.tsx
- packages/app/src/overview/components/overview-screens/pure-overview/pure-overview.component.test.tsx
- packages/app/src/overview/components/overview-screens/pure-overview/pure-overview.component.tsx
- packages/app/src/overview/components/overview-screens/pure-overview/pure-overview.interface.ts
- packages/app/src/overview/components/overview/overview.test.tsx
- packages/app/src/overview/components/update-os-modals/force-update-available-modal/force-update-available-modal.component.tsx
- packages/app/src/overview/components/update-os-modals/force-update-available-modal/force-update-available-modal.interface.ts
- packages/app/src/overview/components/update-os-modals/force-update-available-modal/force-update-available-modal.stories.tsx
- packages/app/src/overview/components/update-os-modals/force-update-available-modal/force-update-available-modal.styled.tsx
- packages/app/src/overview/components/update-os-modals/force-update-available-modal/index.ts
- packages/app/src/overview/components/update-os-modals/too-low-battery-modal/too-low-battery-modal.component.tsx
- packages/app/src/overview/components/update-os-modals/updating-failure-with-help-modal/updating-failure-with-help-modal.component.tsx
- packages/app/src/overview/overview.container.tsx
- packages/app/src/update/actions/check-for-force-update-need/check-for-force-update-need.action.test.ts
- packages/app/src/update/actions/check-for-force-update-need/check-for-force-update-need.action.ts
- packages/app/src/update/constants/event.constant.ts
- packages/app/src/update/reducers/update-os.interface.ts
- packages/app/src/update/reducers/update-os.reducer.test.ts
- packages/app/src/update/reducers/update-os.reducer.ts
Jira: [CP-1708]
Scope:
* small improvements to modals (way of closing them) and added new modal ("ForceUpdateAvailableModal")
* checking for force update need and loading data necessary for displaying "Update the MuditaOS on your device."
<details>
</details>
[CP-1708]: https://appnroll.atlassian.net/browse/CP-1708?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Cp 1708 force update loading data

- packages/app/src/settings/controllers/configuration.controller.ts
- packages/app/src/settings/services/configuration.service.ts
Scope:
* mock app configuration to perform SOSU tests (more details in https://appnroll.slack.com/archives/C03MGGEQ3NE/p1674550703973869 and in https://appnroll.atlassian.net/browse/CP-1801)
<details>
</details>
> Add tmp and mocked app configuration (for SOSU tests)

- packages/app/src/__deprecated__/renderer/components/core/modal/modal.styled.elements.tsx
Jira: [CP-1720]
Minor changes in close modal dialog button styles
<details>
</details>
[CP-1720]: https://appnroll.atlassian.net/browse/CP-1720?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1720] change close modal button styles

- packages/app/src/__deprecated__/renderer/svg/contact-google.svg
- packages/app/src/__deprecated__/renderer/svg/mudita_logo.svg
Jira: [CP-1724]
Remove incorrect tooltips
<details>
</details>
[CP-1724]: https://appnroll.atlassian.net/browse/CP-1724?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1724] remove incorrect tooltips

- packages/app/src/data-sync/observers/device-connection.observer.test.ts
- packages/app/src/data-sync/observers/device-connection.observer.ts
Jira: [CP-1793]
- This solution is a smelly compromise to handle OS that does not handle the sync process.
- The process will be improved and refined with the OS team when will occur again
[CP-1793]: https://appnroll.atlassian.net/browse/CP-1793?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1793][Sequential update] [Pure] Sync failed at re-connection after interrupted SOSU then Update failed pop-up despite the process continues

- packages/app/src/device/modules/mudita-os/adapters/serial-port-device.adapters.ts
- packages/app/src/device/types/mudita-os/request-config.type.ts
- packages/app/src/outbox/observers/outbox.observer.test.ts
- packages/app/src/outbox/observers/outbox.observer.ts
- packages/app/src/update/services/device-update.service.ts
Jira: [CP-1794]
Additionally as part of this PR:
- [Outbox logic turn off for Mudita Harmony](https://github.com/mudita/mudita-center/commit/6b596a7f1f4ee99fdc128a3ae22ef7bc43a92535)
[CP-1794]: https://appnroll.atlassian.net/browse/CP-1794?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1794] [Update] Harmony update 1.8.0 -> 1.9.0 fails in Center (daily 17.01.2023/12.01.2023)

- packages/app/src/device-file-system/services/device-file-system.service.ts
- packages/app/src/device-log/services/device-log.service.ts
Jira: [CP-1799]
[CP-1799]: https://appnroll.atlassian.net/browse/CP-1799?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1799] [Help] Sending a report to Support without connected device is not working

- packages/app/package-lock.json
- packages/app/package.json
- packages/app/src/update/services/releases.service.ts
> v1.7.0-rc.1

- packages/app/src/messages/components/thread-details.styled.tsx
Jira: [CP-1716]
update styles for messages
<details>
</details>
[CP-1716]: https://appnroll.atlassian.net/browse/CP-1716?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1716] update styles for MessagesSidebar

- packages/app/src/__deprecated__/renderer/utils/create-freshdesk-ticket/create-freshdesk-ticket.ts
- packages/app/src/__deprecated__/renderer/utils/create-freshdesk-ticket/create-freshdesk-ticket.types.ts
- packages/app/src/__deprecated__/renderer/utils/create-freshdesk-ticket/map-device-type-to-product.helper.test.ts
- packages/app/src/__deprecated__/renderer/utils/create-freshdesk-ticket/map-device-type-to-product.helper.ts
- packages/app/src/contact-support/actions/send-ticket.action.test.ts
- packages/app/src/contact-support/actions/send-ticket.action.ts
- packages/app/src/contact-support/requests/send-ticket.request.test.ts
- packages/app/src/crash-dump/actions/send-crash-dump-data.action.ts
Jira: [CP-1780]
Add product type to Freshdesk ticket based on a connected device. 
<details>
</details>
[CP-1780]: https://appnroll.atlassian.net/browse/CP-1780?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1780] add a product field to Freshdesk ticket

- packages/app/src/contacts/helpers/contacts.helpers.ts
Handle eslint warnings in contacts.helpers.ts
> Handle eslint warnings in contacts.helpers.ts

- packages/app/package-lock.json
- packages/app/package.json
- packages/app/src/feature-flags/features/index.ts
- packages/app/src/settings/controllers/configuration.controller.ts
- packages/app/src/settings/services/configuration.service.ts
- packages/app/src/settings/static/default-app-configuration.json
> v1.7.0-rc.2

- packages/app/src/update/actions/check-for-force-update-need/check-for-force-update-need.action.ts
Jira: [CP-XXX]
fix ui for daily builds
<details>
</details>
> fix ui for daily builds

- packages/app/src/contacts/components/contacts/contacts.component.tsx
Jira: [CP-1830]
close contact details after contact deletion
<details>
</details>
[CP-1830]: https://appnroll.atlassian.net/browse/CP-1830?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1830] close contact details after contact deletion

- packages/app/src/messages/components/message-bubble/message-bubble.component.tsx
Jira: [CP-1826]
show dropdown menu for single message
<details>
</details>
[CP-1826]: https://appnroll.atlassian.net/browse/CP-1826?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1826] show dropdown menu for single message

- packages/app/src/update/actions/start-update-os/start-update-os.action.ts
Jira: [CP-1812]
[CP-1812]: https://appnroll.atlassian.net/browse/CP-1812?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1812] sequential update vs. EULA popup

- packages/app/package-lock.json
- packages/app/package.json
> v1.7.0 rc.3

- .github/auto_assign.yml
> Auto-assign reviewers updated

- packages/app/src/backup/services/sync-backup-create.service.ts
- packages/app/src/data-sync/reducers/data-sync.interface.ts
- packages/app/src/data-sync/reducers/data-sync.reducer.test.ts
- packages/app/src/data-sync/reducers/data-sync.reducer.ts
- packages/app/src/overview/components/backup/backup.component.tsx
- packages/app/src/overview/components/backup/backup.stories.tsx
- packages/app/src/overview/components/backup/backup.test.tsx
- packages/app/src/overview/components/overview-screens/pure-overview/overview-content.component.tsx
- packages/app/src/overview/components/overview-screens/pure-overview/pure-overview.component.test.tsx
- packages/app/src/overview/components/overview-screens/pure-overview/pure-overview.component.tsx
- packages/app/src/overview/components/overview-screens/pure-overview/pure-overview.interface.ts
- packages/app/src/overview/components/overview/overview.test.tsx
- packages/app/src/overview/overview.container.tsx
Jira: [CP-1800]
block a backup process until synchronization ends
<details>
</details>
[CP-1800]: https://appnroll.atlassian.net/browse/CP-1800?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> block a backup process until synchronization ends

- packages/app/src/update/actions/start-update-os/start-update-os.action.test.ts
- packages/app/src/update/actions/start-update-os/start-update-os.action.ts
Jira: [CP-1778]
- Missed trackers of the updating process added to the project
[CP-1778]: https://appnroll.atlassian.net/browse/CP-1778?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1778] Missed trackers of the updating process added to the project

- packages/app/src/messages/components/thread-list-test-ids.enum.ts
- packages/app/src/messages/components/thread-row.component.tsx
add data-testid for the last message in a thread for testing purposes
> add data-testid for last message in thread

- packages/app/src/__deprecated__/renderer/components/rest/menu/menu.container.tsx
- packages/app/src/__deprecated__/renderer/wrappers/base-app.component.tsx
Jira: [CP-1802]
Show the welcome screen if device was disconnected after backup fails
[CP-1802]: https://appnroll.atlassian.net/browse/CP-1802?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> show welcome screen if device was disconnected

- packages/app/src/__deprecated__/renderer/components/core/icon-button-with-tooltip/tooltip-content.style.ts
- packages/app/src/__deprecated__/renderer/components/core/icon-button-with-tooltip/tooltip-primary-content.component.tsx
- packages/app/src/__deprecated__/renderer/components/core/icon-button-with-tooltip/tooltip-secondary-content.component.tsx
- packages/app/src/overview/components/backup-modal-dialogs/backup-modal-dialogs.tsx
Jira: [CP-1696]
<details>
</details>
[CP-1696]: https://appnroll.atlassian.net/browse/CP-1696?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> add tooltip if file path is too long in backup success modal

- packages/app/src/files-manager/components/files-storage-list/files-storage-list.component.tsx
- packages/app/src/files-manager/components/files-storage-list/files-storage-list.styled.tsx
- packages/app/src/files-manager/components/files-storage-list/files-storage-list.test.tsx
Jira: [CP-1642](https://appnroll.atlassian.net/browse/CP-1642)
- added virtualization for file-storage-list
[CP-1642]: https://appnroll.atlassian.net/browse/CP-1642?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1642] Improve Files Manager list performance

- packages/app/src/__deprecated__/renderer/constants/menu-elements.ts
- packages/app/src/files-manager/components/files-manager-panel/files-manager-panel.component.test.tsx
- packages/app/src/files-manager/components/files-manager-panel/files-manager-panel.component.tsx
- packages/app/src/files-manager/components/files-storage-list/files-storage-list.component.tsx
- packages/app/src/files-manager/constants/device-directory.constant.ts
Jira: [CP-XXX]
<details>
</details>
> Files Manager for Mudita Harmony enabled

- packages/app/src/overview/helpers/is-version-greater.test.ts
- packages/app/src/overview/helpers/is-version-greater.ts
- packages/app/src/settings/actions/load-settings.action.test.ts
- packages/app/src/settings/actions/load-settings.action.ts
Jira: [CP-1862]
[CP-1862]: https://appnroll.atlassian.net/browse/CP-1862?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1862] Mudita Center displays a force update to 1.7.0 when the application is already updated to 1.7.0

- packages/app/src/__deprecated__/renderer/components/rest/menu/menu.container.tsx
- packages/app/src/__deprecated__/renderer/wrappers/root-wrapper.tsx
- packages/app/src/application/hooks/use-application-listeners.hook.ts
- packages/app/src/application/listeners/agreement-status.listener.ts
Jira: [CP-1078]
- Removed memory leak with emitters
[CP-1078]: https://appnroll.atlassian.net/browse/CP-1078?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1078] Handle memory leak after disconnect device

- packages/app/src/__deprecated__/renderer/components/rest/menu/menu.component.tsx
- packages/app/src/__deprecated__/renderer/components/rest/menu/menu.container.tsx
- packages/app/src/backup/services/sync-backup-create.service.ts
Jira: [CP-1800]
catching connection error during backup sync
<details>
</details>
[CP-1800]: https://appnroll.atlassian.net/browse/CP-1800?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> catching connection error during backup sync

- packages/app/src/outbox/services/message-entry-handler.service.test.ts
- packages/app/src/outbox/services/message-entry-handler.service.ts
Jira: [CP-1827]
- fixed bug with showing wrong latest message in Threads :)
[CP-1827]: https://appnroll.atlassian.net/browse/CP-1827?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1827] [Messages] Message deleted on Pure is still visible on messages list

- packages/app/src/messages/components/messages/messages.component.tsx
Jira: [CP-1829]
- added fixes for those two bugs :)
[CP-1829]: https://appnroll.atlassian.net/browse/CP-1829?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1829] [Messages] New (empty) thread cannot be deleted + an issue with selection manager

- packages/app/package-lock.json
- packages/app/package.json
> v2.0.0-rc.1

- packages/app/package-lock.json
- packages/app/package.json
- packages/app/src/feature-flags/features/index.ts
> v2.0.0 rc.3

- packages/app/src/feature-flags/features/index.ts
- packages/app/src/templates/components/templates/templates.component.tsx
- packages/app/src/templates/helpers/templates-order.helpers.test.ts
- packages/app/src/templates/helpers/templates-order.helpers.ts
Jira: [CP-1916]
<details>
</details>
[CP-1916]: https://appnroll.atlassian.net/browse/CP-1916?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1916] [Messages] Changed template order doesn't follow user input

- packages/app/src/__deprecated__/renderer/svg/info.svg
- packages/app/src/overview/components/update-os-modals/downloading-update-finished-modal/downloading-update-finished-modal.component.tsx
- packages/app/src/overview/components/update-os-modals/force-update-available-modal/force-update-available-modal.component.tsx
- packages/app/src/overview/components/update-os-modals/update-available-modal/update-available-modal.component.tsx
- packages/app/src/overview/components/update-os-modals/update-not-available-modal/update-not-available-modal.component.tsx
- packages/app/src/overview/components/update-os-modals/updating-success-modal/updating-success-modal.component.tsx
- packages/app/src/ui/components/modal-dialog/modal-dialog.component.tsx
Jira: [CP-1860]
- bugfix with CloseButton margin
- changed info icons for update modals
- changed info svg
[CP-1860]: https://appnroll.atlassian.net/browse/CP-1860?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1860] Graphic on the update info shows Pure despite having Harmony connected

- packages/app/src/__deprecated__/renderer/locales/default/en-US.json
- packages/app/src/contacts/components/contacts/contacts.component.test.tsx
- packages/app/src/contacts/components/contacts/contacts.component.tsx
- packages/app/src/contacts/components/contacts/delete-contacts-popup/delete-contacts-popup.component.tsx
- packages/app/src/contacts/reducers/contacts.interface.ts
- packages/app/src/contacts/reducers/contacts.reducer.test.ts
- packages/app/src/contacts/reducers/contacts.reducer.ts
- packages/app/src/contacts/selectors/contacts-delete-count.selector.test.ts
- packages/app/src/contacts/selectors/contacts-delete-count.selector.ts
- packages/app/src/files-manager/components/files-manager/files-manager.component.tsx
- packages/app/webpack.config.main.js
Jira: [CP-1662]
** 
Fix inconsistent status popup behaviour for delete operation in contacts and files manager views.
Also added small change in webpack config to prevent sync crashes on Windows.
**
<details>
</details>
[CP-1662]: https://appnroll.atlassian.net/browse/CP-1662?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1662] Inconsistent status popup behaviour for delete operation

- packages/app/src/update/services/device-update.service.ts
[CP-1947]
<details>
</details>
[CP-1947]: https://appnroll.atlassian.net/browse/CP-1947?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1947] Update failed on Harmony with full memory - generic fail popup

- packages/app/src/files-manager/reducers/files-manager.reducer.ts
Jira: [CP-1944]
<details>
</details>
[CP-1944]: https://appnroll.atlassian.net/browse/CP-1944?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1944] [Files manager] Neverending files upload

- packages/app/src/device-info/presenters/device-info.presenter.ts
- packages/app/src/device-info/services/device-info.service.ts
Jira: [CP-1949]
<details>
</details>
[CP-1949]: https://appnroll.atlassian.net/browse/CP-1949?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1949] [Files manager] Invalid values of declared memory

- packages/app/package-lock.json
- packages/app/package.json
> v2.0.0-rc.4

- packages/app/src/files-manager/components/files-storage-list/files-storage-list.component.tsx
- packages/app/src/files-manager/components/files-storage-list/files-storage-list.styled.tsx
- packages/app/src/files-manager/components/files-storage-list/files-storage-list.test.tsx
- packages/app/src/files-manager/components/files-storage/files-storage.component.tsx
Jira: [CP-1940]
<details>
</details>
[CP-1940]: https://appnroll.atlassian.net/browse/CP-1940?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1940] [File manager] Selection manager is available for search result list

- packages/app/src/core/types/request-response.interface.ts
- packages/app/src/device/modules/device.ts
- packages/app/src/device/modules/mudita-os/presenters/response.presenter.ts
- packages/app/src/device/strategies/pure.strategy.ts
- packages/app/src/messages/components/messages/messages.component.tsx
Jira: [CP-1948]
- workaround for adding new contact without primary phone number
- workaround for importing contacts without primary phone number
- removed some eslint-disables, you're welcome :)
[CP-1948]: https://appnroll.atlassian.net/browse/CP-1948?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1948] Wrong modal is displayed when phone without accepted EULA is connected

- packages/app/src/__deprecated__/main/main.ts
Jira: [CP-1594]
- added property for brower window options :)
[CP-1594]: https://appnroll.atlassian.net/browse/CP-1594?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1594] [Windows] [Linux] Toolbar is available for separate MC windows

- .env.example
- packages/app/package-lock.json
- packages/app/package.json
- packages/app/src/update/services/releases.service.ts
> v2.0.0 rc.7

- packages/e2e/src/helpers/messages.helper.ts
- packages/e2e/src/page-objects/messages-conversation.page.ts
- packages/e2e/src/specs/messages/messages-send.e2e.ts
Jira: [CP-1900]
https://appnroll.atlassian.net/browse/CP-1900
added as additional scenario in messages-send
<details>
</details>
[CP-1900]: https://appnroll.atlassian.net/browse/CP-1900?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1900][E2E][Messages] Re-send a message with failed send status

- packages/app/src/update/services/releases.service.ts
Jira: [CP-1957]
[CP-1957]: https://appnroll.atlassian.net/browse/CP-1957?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1957] [Center] [Tech] Add feature toggle to .env to set releases environment - vol2

- packages/app/package-lock.json
- packages/app/package.json
> v2.0.0-rc.8

- packages/app/src/__deprecated__/renderer/locales/default/en-US.json
- packages/app/src/overview/components/status/status.component.tsx
Jira: [CP-1969]
[CP-1969]: https://appnroll.atlassian.net/browse/CP-1969?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1969][Center] The user is informed of Harmony's no charge when it is connected to the PC.

- packages/app/src/__deprecated__/main/main.ts
Jira: [CP-1976]
<details>
</details>
[CP-1976]: https://appnroll.atlassian.net/browse/CP-1976?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1976] Application does not close all its windows (help, gmail/homtail import, Licence, SAR, etc.)

- packages/app/src/__deprecated__/renderer/components/core/input-checkbox/input-checkbox-with-tooltip.tsx
- packages/app/src/__deprecated__/renderer/components/core/input-checkbox/input-checkbox.component.tsx
- packages/app/src/__deprecated__/renderer/components/core/tooltip/element-with-tooltip.component.tsx
- packages/app/src/__deprecated__/renderer/components/rest/visible-checkbox/visible-checkbox.tsx
- packages/app/src/messages/components/thread-list.component.tsx
- packages/app/src/messages/components/thread-row.component.tsx
Jira: [CP-1306]
- added tooltip to checkboxes
- added fix for tooltip for threads cause of bug with will-change: transform property used in virtualized-react list
[CP-1306]: https://appnroll.atlassian.net/browse/CP-1306?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1306] Add tooltip to checkbox

- packages/app/src/__deprecated__/main/main.ts
Jira: [CP-1975]
<details>
</details>
[CP-1975]: https://appnroll.atlassian.net/browse/CP-1975?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1975] Device not responding modal appears if 2nd app instance is launched (Linux/Mac)

- packages/app/src/__deprecated__/renderer/locales/default/en-US.json
- packages/app/src/__deprecated__/renderer/utils/form-validators.test.tsx
- packages/app/src/__deprecated__/renderer/utils/form-validators.ts
- packages/app/src/contacts/actions/create-new-contacts.action.test.ts
- packages/app/src/contacts/actions/create-new-contacts.action.ts
- packages/app/src/contacts/components/contacts/contacts.component.tsx
- packages/app/src/contacts/services/contact.service.ts
…Name entry in MC Contacts (#1185)
Jira: [CP-1973]
Cherry picked https://github.com/mudita/mudita-center/commit/10034a9d8ff4f2c6a4e34b96810e931a32f0cef7
<details>
</details>
[CP-1973]: https://appnroll.atlassian.net/browse/CP-1973?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1973] [Contacts] 'No name' contact appears on contact list after an attempt to save contact without a number

- packages/app/src/__deprecated__/renderer/models/external-providers/google/google.ts
- packages/app/src/__deprecated__/renderer/models/external-providers/outlook/outlook.ts
- packages/app/src/contacts/actions/closeWindow.action.test.ts
- packages/app/src/contacts/actions/closeWindow.action.ts
- packages/app/src/contacts/components/contacts/contacts.component.test.tsx
- packages/app/src/contacts/components/contacts/contacts.component.tsx
- packages/app/src/contacts/components/contacts/contacts.interface.ts
- packages/app/src/contacts/components/contacts/contacts.stories.tsx
- packages/app/src/contacts/constants/event.enum.ts
- packages/app/src/contacts/contacts.container.tsx
Jira: [CP-1680]
- bugfix for opening another authorization window during import process, which make possible to do parallel import
- now, closing modal with import methods closes also windows for google and outlook opened before :)
[CP-1680]: https://appnroll.atlassian.net/browse/CP-1680?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1680] [Contacts] Parallel contact upload Gmail/Outlook - fix

- packages/app/src/templates/components/templates/templates.component.tsx
- packages/app/src/ui/hooks/loading-state.hook.tsx
Jira: [CP-1971]
- fixed unwanted disappearance of delete confirmation modal
**Questions**
- What do you think about changes in file loading-state.hook.tsx function resetState? Should it be declarative instead of imperative?
[CP-1971]: https://appnroll.atlassian.net/browse/CP-1971?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1971] [Messages][Templates] status popup disapearance also causes modal to disappear

- packages/app/src/__deprecated__/renderer/components/core/input-checkbox/input-checkbox.component.tsx
- packages/app/src/contacts/components/virtualized-contact-list-item/virtualized-contact-list-item.component.tsx
Jira: [CP-1306]
- added fix for incorrect tooltips showing opposite messages
[CP-1306]: https://appnroll.atlassian.net/browse/CP-1306?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1306] [FIX] Add tooltip to checkbox

- packages/app/package-lock.json
- packages/app/package.json
Jira: [CP-XXX]
<details>
</details>
> v2.0.1-rc.2

- packages/app/src/__deprecated__/renderer/components/core/input-checkbox/input-checkbox.component.tsx
- packages/app/src/__deprecated__/renderer/components/core/selection-manager/selection-manager.component.tsx
- packages/app/src/__deprecated__/renderer/components/core/tooltip/element-with-tooltip.component.tsx
- packages/app/src/__deprecated__/renderer/locales/default/en-US.json
- packages/app/src/overview/components/overview-screens/helpers/use-update-flow-state.hook.tsx
- packages/app/src/settings/components/backup/__snapshots__/backup-ui.test.tsx.snap
- packages/app/src/update/constants/check-for-update-state.constant.ts
- packages/app/src/update/reducers/update-os.reducer.ts
Jira: [CP-1306]
- fix of translation messages
- fix of showing tooltip after window switch
[CP-1306]: https://appnroll.atlassian.net/browse/CP-1306?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1306] [FIX2] Add tooltip to checkbox

- packages/app/package-lock.json
- packages/app/package.json
> v2.0.1-rc.3

- packages/app/src/templates/components/templates/templates.component.tsx
Jira: [CP-1971]
- fix of not disappearing status
[CP-1971]: https://appnroll.atlassian.net/browse/CP-1971?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1971] [FIX] [Messages][Templates] status popup disapearance also causes modal to disappear

- .env.example
- packages/app/src/__deprecated__/renderer/store/index.ts
- packages/app/src/core/application.module.ts
- packages/app/src/feature-flags/constants/feature.enum.ts
- packages/app/src/feature-flags/features/index.ts
Jira: [CP-XXX]
- Removed feature flags not used in the project
- Updated documentation on [Release process in steps](https://appnroll.atlassian.net/wiki/spaces/CP/pages/1543405752/Git+workflow+for+the+Mudita+Center+project.#Release-process-in-steps) for distribution sections of dedicated packages for standard and force tests Mudita Center update
- Added a new environment variable to help manage the feature about the updating Application to a prerelease
⚠️ Please remember to change your env variable after merge this PR 🙏  ⚠️
> Added MUDITA_CENTER_PRERELEASE_ENABLED env variable

- packages/app/src/messages/components/messages-search-results/messages-search-results-item.component.tsx
- packages/app/src/messages/components/messages-search-results/messages-search-results.component.tsx
Jira: [CP-XXX]
<details>
</details>
> add phoneNumber to messages search results itrem

- packages/app/src/contacts/selectors/get-contact-by-phone-number.selector.ts
- packages/app/src/messages/actions/base.action.test.ts
- packages/app/src/messages/actions/base.action.ts
- packages/app/src/messages/helpers/create-fake-contact.ts
- packages/app/src/messages/helpers/threads.helpers.test.ts
- packages/app/src/messages/helpers/threads.helpers.ts
- packages/app/src/messages/messages.container.tsx
- packages/app/src/messages/selectors/filtered-threads.selector.ts
- packages/app/src/messages/selectors/get-phone-number-by-id.selector.ts
Jira: [CP-XXX]
<details>
</details>
> [CP-1873] [TODO] removed dead code

- packages/app/src/messages/components/receiver-input-search/receiver-input-search.helpers.tsx
Jira: [CP-XXX]
<details>
</details>
> [CP-1873] [TODO] receiver-input-search.helpers.tsx

- packages/app/src/contacts/components/contact-simple-list-item-phone-selection/contact-simple-list-item-phone-selection.component.tsx
- packages/app/src/contacts/components/contact-simple-list-item-phone-selection/contact-simple-list-item-phone-selection.interface.ts
- packages/app/src/contacts/components/contact-simple-list/contact-simple-list.interface.ts
- packages/app/src/contacts/components/contacts-select-modal/contacts-select-modal.interface.ts
- packages/app/src/messages/components/messages/messages.component.tsx
Jira: [CP-XXX]
<details>
</details>
> [CP-1873] [TODO] contact-simple-list-item-phone-selection.component.tsx

- packages/app/src/data-sync/presenters/message/message.presenter.ts
- packages/app/src/messages/components/messages/messages.component.tsx
- packages/app/src/messages/components/new-message-form.component.tsx
- packages/app/src/messages/selectors/get-phone-number-by-id.selector.ts
- packages/app/src/outbox/services/contact-entry-handler.service.ts
Jira: [CP-XXX]
<details>
</details>
> [CP-1873] [TODO] message.component.tsx for new message

- packages/app/src/contacts/actions/create-new-contacts.action.ts
- packages/app/src/contacts/components/contacts/contacts.component.tsx
- packages/app/src/contacts/components/contacts/contacts.interface.ts
- packages/app/src/contacts/services/contact.service.ts
- packages/app/src/device/types/mudita-os/serialport-request.type.ts
Jira: [CP-864]
<details>
</details>
[CP-864]: https://appnroll.atlassian.net/browse/CP-864?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
>  [CP-864] Error messages in wrong input

- packages/app/src/__deprecated__/seeds/messages.ts
- packages/app/src/device/types/mudita-os/serialport-request.type.ts
- packages/app/src/messages/actions/add-new-message.action.test.ts
- packages/app/src/messages/components/messages-search-results/messages-search-results-item.component.tsx
- packages/app/src/messages/components/messages/messages.component.tsx
- packages/app/src/messages/components/new-message-form.component.tsx
- packages/app/src/messages/dto/message.object.ts
- packages/app/src/messages/dto/new-message.object.ts
- packages/app/src/messages/presenters/message.presenter.test.ts
- packages/app/src/messages/presenters/message.presenter.ts
- packages/app/src/messages/services/message.service.test.ts
- packages/app/src/messages/services/message.service.ts
Jira: [CP-XXX]
<details>
</details>
> [CP-1873] [TOOD] packages/app/src/messages/presenters/message.presenter.ts

- packages/app/src/contacts/actions/edit-contact.action.ts
- packages/app/src/contacts/services/contact.service.ts
- packages/app/src/outbox/services/contact-entry-handler.service.ts
- packages/app/src/phone-numbers/services/phone-number.service.ts
Jira: [CP-1873]
[CP-1873]: https://appnroll.atlassian.net/browse/CP-1873?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1873] Edit contact fix

- packages/app/src/__deprecated__/api/mudita-center-server/client.ts
- packages/app/src/update/actions/check-for-update/check-for-update.action.ts
- packages/app/src/update/controllers/releases.controller.ts
- packages/app/src/update/dto/get-releases-by-version-input.object.ts
- packages/app/src/update/requests/get-all-releases.request.ts
- packages/app/src/update/requests/get-latest-release.request.ts
- packages/app/src/update/services/releases.service.ts
Jira: [CP-1990]
<details>
</details>
[CP-1990]: https://appnroll.atlassian.net/browse/CP-1990?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1990] Implement the logic for filtering Mudita employees from the collected MuditaOS download events

- packages/app/src/__deprecated__/renderer/wrappers/app-update-step-modal/app-update.modals.tsx
Jira: [CP-2022]
<details>
</details>
[CP-2022]: https://appnroll.atlassian.net/browse/CP-2022?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2022]  I want to be able to read and accept the privacy policy of the Mudita Center app before updating it

- packages/app/src/update/reducers/update-os.reducer.ts
Jira: [CP-2044]
[CP-2044]: https://appnroll.atlassian.net/browse/CP-2044?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2044][Update] Modal disappears after uploading update package to the device despite process continue

- packages/app/src/__deprecated__/main/main.ts
Jira: [CP-2069]
Disabled all reload keyboard shortcuts for MC
[CP-2069]: https://appnroll.atlassian.net/browse/CP-2069?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2069] Update modal disappears after using ctrl + r shortcut.

- .github/auto_assign.yml
`dkarski` removed from reviewers
> `dkarski` removed from reviewers

- packages/app/src/core/application.module.ts
Jira: [CP-2083]
[CP-2083]: https://appnroll.atlassian.net/browse/CP-2083?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2083] Missing Crash modal from Pure 1.7.1

- packages/app/package-lock.json
- packages/app/package.json
Jira: [CP-XXX]
<details>
</details>
> 2.0.2-rc.2

- packages/app/src/contacts/reducers/contacts.reducer.ts
- packages/app/src/messages/reducers/messages.reducer.ts
Jira: [CP-2001]
[CP-2001]: https://appnroll.atlassian.net/browse/CP-2001?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2001][Contacts] [Messages] Selection manager is not aware the item was removed from the list

- packages/app/package.json
- packages/app/scripts/set-build-year.js
Jira: [CP-2037]
<details>
</details>
[CP-2037]: https://appnroll.atlassian.net/browse/CP-2037?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2037] Outdated date in About section of Mudita Center

- packages/app/package-lock.json
- packages/app/package.json
Jira: [CP-XXX]
<details>
</details>
> v2.0.2-rc.4

- packages/app/package-lock.json
- packages/app/package.json
Jira: [CP-XXX]
<details>
</details>
> update version to v2.1.0-rc.1

- packages/app/src/settings/components/about/about-ui.component.tsx
- packages/app/src/settings/components/about/about.component.tsx
- packages/app/src/settings/components/about/about.test.tsx
Jira: [CP-2002]
<details>
</details>
[CP-2002]: https://appnroll.atlassian.net/browse/CP-2002?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2002] [Settings] Mudita Center app update status changes based on Internet availability

- packages/app/package-lock.json
- packages/app/package.json
Jira: [CP-XXX]
<details>
</details>
> update version to 2.1.0-rc.2

- packages/app/src/data-sync/presenters/thread/thread.presenter.ts
- packages/app/src/messages/helpers/threads.helpers.ts
- packages/app/src/messages/presenters/message.presenter.ts
- packages/app/src/messages/presenters/thread.presenter.ts
- packages/app/src/messages/selectors/get-receiver.selector.test.ts
- packages/app/src/messages/selectors/get-receivers.selector.test.ts
Jira: [CP-2096]
<details>
</details>
[CP-2096]: https://appnroll.atlassian.net/browse/CP-2096?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2096] It is not currently possible to add a contact with a prefix to a phone using the Mudita Center

- packages/app/src/__deprecated__/renderer/wrappers/root-wrapper.tsx
Jira: [CP-2115]
**this shoud fix issue with too much rerendering throughout the whole app**
<details>
</details>
[CP-2115]: https://appnroll.atlassian.net/browse/CP-2115?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2115][Update] connecting device during Center update triggers new Center update modal and 

- packages/app/package-lock.json
- packages/app/package.json
Jira: [CP-XXX]
<details>
</details>
> update to 2.1.0-rc.3

- packages/app/src/overview/components/update-os-modals/not-enough-space-modal/not-enough-space-modal.component.tsx
- packages/app/src/update/services/device-update.service.test.ts
- packages/app/src/update/services/device-update.service.ts
Jira: [CP-XXX]
<details>
</details>
> [CP-2146] Device cannot be updated at the edge of full memory usage

- packages/app/src/settings/services/configuration.service.test.ts
- packages/app/src/settings/services/configuration.service.ts
Jira: [CP-2011]
<details>
</details>
[CP-2011]: https://appnroll.atlassian.net/browse/CP-2011?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2011] MC daily cannot be started in offline mode

- packages/app/src/__deprecated__/renderer/locales/default/en-US.json
- packages/app/src/overview/components/backup-modal-dialogs/backup-modal-dialogs.tsx
Jira: [CP-2008]
<details>
</details>
[CP-2008]: https://appnroll.atlassian.net/browse/CP-2008?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2008] Backup - process sometimes is unsuccesfull due to full storage according to modal it displays

- packages/app/package-lock.json
- packages/app/package.json
Jira: [CP-XXX]
<details>
</details>
> v2.2.0-rc.1 to v2.2.0

- packages/app/package-lock.json
- packages/app/package.json
- packages/app/src/feature-flags/features/index.ts
Jira: [CP-XXX]
<details>
</details>
> v2.2.0-rc.2 to v2.2.0

- packages/app/package-lock.json
- packages/app/package.json
Jira: [CP-XXX]
<details>
</details>
> v2.2.0-rc.4 to v2.2.0

- packages/app/package-lock.json
- packages/app/package.json
Jira: [CP-XXX]
<details>
</details>
> v2.2.0-rc.5 to v2.2.0

- packages/app/package-lock.json
- packages/app/package.json
Jira: [CP-XXX]
<details>
</details>
> 2.2.0-rc.6 to 2.2.0

- packages/app/package-lock.json
- packages/app/package.json
Jira: [CP-XXX]
<details>
</details>
> 2.2.0-rc.7 to 2.2.0

- packages/app/src/device-file-system/commands/file-upload.command.ts
- packages/app/src/files-manager/services/file-manager.service.ts
Jira: [CP-2148]
<details>
</details>
[CP-2148]: https://appnroll.atlassian.net/browse/CP-2148?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2148][Files Manager] Center doesn't stops uploading files after device disconecting

- packages/app/package-lock.json
- packages/app/package.json
Jira: [CP-XXX]
<details>
</details>
> V2.2.0 rc.8 to v2.2.0

- packages/app/package-lock.json
- packages/app/package.json
Jira: [CP-XXX]
<details>
</details>
> v2.2.0-rc.9 to v2.2.0

- packages/app/package-lock.json
- packages/app/src/news/reducers/index.ts
- packages/app/src/news/reducers/news.helper.ts
- packages/app/src/news/reducers/news.reducer.ts
Jira: [CP-2193]
<details>
</details>
[CP-2193]: https://appnroll.atlassian.net/browse/CP-2193?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2193] [Mudita News] First article has a space before its title

- packages/app/package-lock.json
- packages/app/package.json
> v2.2.1 to main

- packages/app/package-lock.json
- packages/app/package.json
> main to test

- CHANGELOG.md
> CHANGELOG.md added to 2.2.2

- packages/app/src/__deprecated__/renderer/locales/default/en-US.json
[CP-XXX] pendingUploadModalTextInfo key - translation updated
> [CP-XXX] pendingUploadModalTextInfo key - translation updated

- .github/auto_assign.yml
Jira: [CP-XXX]
Update/auto_assign.yml
> [CP-XXX] Update/auto_assign.yml

- CHANGELOG.md
Jira: [CP-XXX]
<details>
</details>
> Update changelog for release 2.2.3

- packages/app/src/__deprecated__/main/main.ts
JIRA Reference: [CP-101]
- 
[CP-101]: https://appnroll.atlassian.net/browse/CP-101?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-101] Windows titles updated - TEST

- packages/app/src/__deprecated__/main/main.ts
This reverts commit 3db49588410037ce3ff01bfb0b390219dc0dd90a.
- 
> Revert "[CP-101] Windows titles updated - TEST (#1465)"

- packages/app/src/__deprecated__/main/main.ts
- packages/app/src/contacts/components/contact-details/contact-details.component.tsx
(fake) Release v2.3.0 - develop to stage
> (fake) Release v2.3.0 - develop to stage

- .github/workflows/nexus-dev.yml
> Nexus (#1473)

- .github/workflows/nexus-dev.yml
> Nexus (#1477)

- packages/app/src/__deprecated__/main/main.ts
- packages/app/src/contacts/components/contact-details/contact-details.component.tsx
(fake) Release v2.4.0 - develop to stage
> (fake) Release v2.4.0 - develop to stage 

- packages/app/package-lock.json
- packages/app/package.json
(fake) Release v2.4.0 - to stage
> (fake) Release v2.4.0 - to stage 

- .github/workflows/nexus-dev.yml
- .github/workflows/nexus-production.yml
- .github/workflows/nexus-staging.yml
> Nexus (#1488)

- .github/workflows/nexus-development.yml
- .github/workflows/nexus-pre-production.yml
- .github/workflows/nexus-production.yml
> [CP-XXX] Nexus* updated

- .github/workflows/nexus-development.yml
- .github/workflows/nexus-pre-production.yml
- .github/workflows/nexus-production.yml
> [CP-XXX] Nexus* updated (#1498)

- .github/workflows/nexus-pre-production.yml
- .github/workflows/nexus-production.yml
> [CP-XXX] Nexus* updated - trigger strategy updated

- .github/workflows/nexus-development.yml
- .github/workflows/nexus-pre-production.yml
- .github/workflows/nexus-production.yml
> Nexus internal (#1506)

- .github/workflows/nexus-pre-production.yml
- packages/app/package-lock.json
- packages/app/package.json
(fake) Release v2.5.0 - to stage
> (fake) Release v2.5.0 - to stage 

- .github/workflows/nexus-development.yml
- .github/workflows/nexus-pre-production.yml
- .github/workflows/nexus-production.yml
> [CP-XXX] Nexus files refactored

- .github/workflows/nexus-development.yml
- .github/workflows/nexus-pre-production.yml
- .github/workflows/nexus-production.yml
> [CP-XXX] Nexus files refactored (#1512)

- .github/workflows/nexus-development.yml
- .github/workflows/nexus-pre-production.yml
> [CP-XXX] Modified publication strategy for dev & pre-prod

- .github/workflows/nexus-development.yml
- .github/workflows/nexus-pre-production.yml
> [CP-XXX] Modified publication strategy for dev & pre-prod (#1515)

- CHANGELOG.md
> update changelog for 2.2.4

- packages/app/src/update/reducers/update-os.reducer.test.ts
- packages/app/src/update/reducers/update-os.reducer.ts
> fix updateCheck state after update process

- .github/workflows/nexus-development.yml
- .github/workflows/nexus-pre-production.yml
- .github/workflows/nexus-production.yml
> dev double names fix

- .github/workflows/nexus-development.yml
Fixed problems with name convention
Extract steps for more clear view
> Final development build

- .github/workflows/nexus-development.yml
> feature version fix

- packages/app/package-lock.json
- packages/app/package.json
- packages/app/scripts/downloadFonts.js
- packages/app/src/__deprecated__/renderer/app.tsx
- packages/e2e/package-lock.json
- packages/e2e/package.json
- quickstart.md
JIRA Reference: [CP-2195]
- Adjusted configuration for ARM architecture
- Fixed an issue when running a project as a newcomer without an access to official fonts (GT Pressura)
[CP-2195]: https://appnroll.atlassian.net/browse/CP-2195?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2195] Fixed ARM and newcomer's related issues

- packages/app/src/__deprecated__/main/main.ts
JIRA Reference: [CP-2241]
-
[CP-2241]: https://appnroll.atlassian.net/browse/CP-2241?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2241] Disallow open new window during click news link

- packages/app/src/__deprecated__/renderer/wrappers/help-app.component.tsx
JIRA Reference: [CP-2241]
-
[CP-2241]: https://appnroll.atlassian.net/browse/CP-2241?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2241] Context Menu disabled in the Help window

- packages/app/src/__deprecated__/renderer/components/core/table/table.component.tsx
JIRA Reference: [CP-2241]
-
[CP-2241]: https://appnroll.atlassian.net/browse/CP-2241?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2241] Item auto height fixed for Template Item

- .github/workflows/nexus-development.yml
- .github/workflows/nexus-pre-production.yml
- .github/workflows/nexus-production.yml
- CHANGELOG.md
- packages/app/package-lock.json
- packages/app/package.json
- packages/app/src/__deprecated__/renderer/components/core/tooltip/element-with-tooltip.component.tsx
- packages/app/src/device-manager/services/device-manager.service.test.ts
- packages/app/src/device-manager/services/device-resolver.service.test.ts
- packages/app/src/device/constants/product-identifier.constant.ts
- packages/app/src/device/descriptors/mudita-pure.descriptor.ts
- packages/app/src/settings/static/default-app-configuration.json
> v2.2.5-rc.3 to v2.2.5

- packages/app/src/__deprecated__/main/main.ts
- packages/app/src/contacts/components/virtualized-contact-list/virtualized-contact-list.component.tsx
JIRA Reference: [CP-2276]
-
[CP-2276]: https://appnroll.atlassian.net/browse/CP-2276?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2276] Adding Title Bar for Google Import

- CHANGELOG.md
> 2.2.5 update changelog

- .github/workflows/nexus-development.yml
- .github/workflows/nexus-pre-production.yml
- .github/workflows/nexus-production.yml
- CHANGELOG.md
- packages/app/package-lock.json
- packages/app/package.json
- packages/app/src/device-manager/services/device-manager.service.test.ts
- packages/app/src/device-manager/services/device-resolver.service.test.ts
- packages/app/src/device/constants/product-identifier.constant.ts
- packages/app/src/device/descriptors/mudita-pure.descriptor.ts
- packages/app/src/settings/static/default-app-configuration.json
> 2.2.5 main to stage

- packages/app/src/__deprecated__/renderer/wrappers/base-app.component.tsx
- packages/app/src/connecting/components/error-connecting-modal.tsx
- packages/app/src/overview/components/device-preview/device-preview.component.tsx
JIRA Reference: [CP-2274]
-
[CP-2274]: https://appnroll.atlassian.net/browse/CP-2274?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2274] Fix device connection issue and unresponsive behavior - v2

- packages/app/src/__deprecated__/main/main.ts
- packages/app/src/core/application.module.ts
- packages/app/src/core/types/module.type.ts
- packages/app/src/file-system/constants/controller.constant.ts
- packages/app/src/file-system/constants/error.constant.ts
- packages/app/src/file-system/constants/index.ts
- packages/app/src/file-system/controllers/dialog-file-system.controller.ts
- packages/app/src/file-system/controllers/index.ts
- packages/app/src/file-system/dto/get-paths-input.object.ts
- packages/app/src/file-system/dto/index.ts
- packages/app/src/file-system/file-system.module.ts
- packages/app/src/file-system/requests/get-paths.request.ts
- packages/app/src/file-system/requests/index.ts
- packages/app/src/file-system/services/file-system-dialog.service.test.ts
- packages/app/src/file-system/services/file-system-dialog.service.ts
- packages/app/src/file-system/services/index.ts
- packages/app/src/files-manager/actions/upload-file.action.test.ts
- packages/app/src/files-manager/actions/upload-file.action.ts
- packages/app/src/files-manager/components/files-manager/files-manager.component.tsx
JIRA Reference: [CP-2272]
-
[CP-2272]: https://appnroll.atlassian.net/browse/CP-2272?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2272] Fix: File upload window now opens in last-used location. 

- .github/workflows/nexus-mass-update.yml
- packages/app/package-lock.json
- packages/app/package.json
JIRA Reference: [CP-2210]
-
[CP-2210]: https://appnroll.atlassian.net/browse/CP-2210?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2210] Add Mass Update Envivorment to workflows

- .github/workflows/nexus-mass-update.yml
- .github/workflows/nexus-production-with-os-rc.yml
- packages/app/package-lock.json
- packages/app/package.json
JIRA Reference: [CP-2210]
-
[CP-2210]: https://appnroll.atlassian.net/browse/CP-2210?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2210] Add Production With OS RC Envivorment to workflows #1594

- .github/workflows/nexus-development.yml
- .github/workflows/nexus-feature-branch.yml
JIRA Reference: [CP-2210]
-
[CP-2210]: https://appnroll.atlassian.net/browse/CP-2210?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2210] Modified Development Envivorment workflows

- .github/workflows/nexus-pre-production-latest.yml
- .github/workflows/nexus-pre-production.yml
- packages/app/package-lock.json
- packages/app/package.json
JIRA Reference: [CP-2210]
-
[CP-2210]: https://appnroll.atlassian.net/browse/CP-2210?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2210] Add Pre production as latest Envivorment to workflows

- libs/core/__deprecated__/renderer/store/reducers.ts
- libs/core/app-initialization/actions/redirect-to-discovery.action.ts
- libs/core/app-initialization/components/app-initialization.component.tsx
- libs/core/app-initialization/constants/event.constant.ts
- libs/core/app-initialization/hooks/use-device-connected-effect.ts
- libs/core/app-initialization/hooks/use-initializing-app-effects.ts
- libs/core/core/application.module.ts
- libs/core/device-manager/actions/base.action.ts
- libs/core/device-manager/actions/handle-device-connected.action.ts
- libs/core/device-manager/constants/event.constant.ts
- libs/core/device-manager/helpers/map-to-device.ts
- libs/core/device-manager/listeners/device-connected.listener.ts
- libs/core/device-manager/reducers/device-manager.interface.ts
- libs/core/device-manager/reducers/device-manager.reducer.ts
- libs/core/device-manager/selectors/device-manager-state.selector.ts
- libs/core/device-manager/selectors/is-active-device-set.selector.ts
- libs/core/device-manager/selectors/is-device-list-empty.selector.ts
- libs/core/device-manager/services/device-manager.service.ts
JIRA Reference: [CP-2334]
-
[CP-2334]: https://appnroll.atlassian.net/browse/CP-2334?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2334] Decomposition: Create Device Manager Lib

- libs/core/__deprecated__/main/functions/get-app-settings.ts
- libs/core/__deprecated__/main/functions/register-news-listener/register-news-listener.ts
- libs/core/__deprecated__/main/store/help.ts
- libs/core/__deprecated__/main/utils/get-app-path.ts
- libs/core/__deprecated__/renderer/register-app-context-menu.ts
JIRA Reference: [CP-2328]
-
[CP-2260]: https://appnroll.atlassian.net/browse/CP-2260?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CP-2328]: https://appnroll.atlassian.net/browse/CP-2328?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2328] Fix app path construction for compatibility

- libs/core/device/reducers/device.interface.ts
- libs/core/feature-flags/features/index.ts
- libs/core/overview/components/overview-screens/harmony-overview/harmony-overview.component.interface.ts
- libs/core/overview/components/overview-screens/harmony-overview/harmony-overview.component.test.tsx
- libs/core/overview/components/overview-screens/harmony-overview/harmony-overview.component.tsx
- libs/core/overview/components/overview-screens/harmony-overview/overview-content.component.tsx
JIRA Reference: [CP-1962]
-
[CP-1962]: https://appnroll.atlassian.net/browse/CP-1962?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1962] I want to be able to identify my Harmony  by color - v2

- libs/core/backup/actions/load-backup-data.action.ts
- libs/core/settings/actions/load-settings.action.ts
- libs/core/settings/selectors/get-settings-state.selector.ts
JIRA Reference: [CP-2392]
-
[CP-2392]: https://appnroll.atlassian.net/browse/CP-2392?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2392][Multidevice] After reopening the app it does not see existing backups 

- libs/core/device-manager/actions/deactivate-device.action.ts
JIRA Reference: [CP-2372]
-
[CP-2372]: https://appnroll.atlassian.net/browse/CP-2372?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2372][Multidevice] OS update information is globally set

- libs/core/backup/actions/base.action.ts
- libs/core/backup/constants/event.enum.ts
- libs/core/backup/reducers/backup.reducer.ts
- libs/core/contacts/actions/base.action.ts
- libs/core/contacts/constants/event.enum.ts
- libs/core/contacts/reducers/contacts.reducer.ts
- libs/core/contacts/services/contact.service.ts
- libs/core/device-manager/actions/deactivate-device.action.ts
- libs/core/files-manager/actions/base.action.ts
- libs/core/files-manager/constants/event.enum.ts
- libs/core/files-manager/reducers/files-manager.reducer.ts
- libs/core/messages/actions/base.action.ts
- libs/core/messages/constants/event.enum.ts
- libs/core/messages/reducers/messages.reducer.ts
JIRA Reference: [CP-2393]
-
[CP-2393]: https://appnroll.atlassian.net/browse/CP-2393?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2393][Multidevice] Deleting modal does not disappear on reconnecting USB while deleting contacts - v2

- libs/core/discovery-device/components/available-device-list.component.tsx
- libs/core/discovery-device/components/available-device-list.container.tsx
- libs/core/discovery-device/components/configured-devices-discovery.component.tsx
JIRA Reference: [CP-2397]
-
[CP-2397]: https://appnroll.atlassian.net/browse/CP-2397?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2397][Multidevice] empty Select device screen 

- libs/core/__deprecated__/renderer/locales/default/en-US.json
- libs/core/device-initialization/components/eula-agreement/eula-agreement.container.tsx
- libs/core/eula-agreement/components/agreement-modal/agreement-modal.component.tsx
- libs/core/eula-agreement/components/agreement-modal/agreement-modal.interface.ts
JIRA Reference: [CP-2164]
-
[CP-2164]: https://appnroll.atlassian.net/browse/CP-2164?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2164][Multidevice]  I want to choose and open  one of the available devices

- libs/core/device/actions/get-onboarding-status.action.ts
JIRA Reference: [CP-2423]
-
[CP-2423]: https://appnroll.atlassian.net/browse/CP-2423?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2423][Multidevice] EULA modal keeps reloading

- libs/core/device-manager/actions/handle-device-detached.action.ts
- libs/core/device/actions/get-onboarding-status.action.ts
- libs/core/update/components/update-os-interrupted-flow/update-os-interrupted-flow.component.tsx
- libs/core/update/components/update-os-interrupted-flow/update-os-interrupted-flow.container.tsx
- libs/core/update/components/update-os-interrupted-flow/update-os-interrupted-flow.test.tsx
JIRA Reference: [CP-2400]
-
[CP-2400]: https://appnroll.atlassian.net/browse/CP-2400?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2400][Multidevice] Disconnected device during OS update - after failed modal, Center acts like device was connected

- libs/core/device-initialization/actions/start-initializing-device/initialize-mudita-pure.ts
- libs/core/device/actions/get-unlock-status.action.ts
- libs/core/device/actions/handle-communication-error.action.ts
- libs/core/device/actions/load-device-data.action.ts
- libs/core/device/constants/event.enum.ts
JIRA Reference: [CP-2436]
-
[CP-2436]: https://appnroll.atlassian.net/browse/CP-2436?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2436][Multidevice] Passcode locked and closing passcode modal

- libs/core/device/modules/mudita-os/presenters/response.presenter.ts
JIRA Reference: [CP-2426]
-
[CP-2426]: https://appnroll.atlassian.net/browse/CP-2426?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2426][Multidevice] Unhandled Pure error during connection

- libs/core/device-initialization/actions/start-initializing-device/initialize-mudita-harmony.ts
- libs/core/device-initialization/components/eula-agreement/eula-agreement.container.tsx
- libs/core/device/actions/get-onboarding-status.action.ts
- libs/core/device/modules/mudita-os/presenters/response.presenter.ts
JIRA Reference: [CP-2164]
-
[CP-2164]: https://appnroll.atlassian.net/browse/CP-2164?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2164] EULA / Onboard strategy updated

- libs/core/__deprecated__/renderer/components/rest/menu/menu-bottom.component.tsx
- libs/core/device-initialization/actions/start-initializing-device/initialize-mudita-harmony.ts
- libs/core/device-initialization/components/eula-agreement/eula-agreement.container.tsx
- libs/core/device/actions/get-onboarding-status.action.ts
- libs/core/device/modules/mudita-os/presenters/response.presenter.ts
JIRA Reference: [CP-2162]
-
[CP-2162]: https://appnroll.atlassian.net/browse/CP-2162?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2162] Change strategy to display "Select Device" button

- libs/core/__deprecated__/renderer/components/rest/menu/menu-bottom.component.tsx
- libs/core/device-initialization/actions/start-initializing-device/initialize-mudita-harmony.ts
- libs/core/device-initialization/components/eula-agreement/eula-agreement.container.tsx
- libs/core/device-manager/controllers/device-manager.controller.ts
- libs/core/device-manager/reducers/device-manager.reducer.ts
- libs/core/device/actions/get-onboarding-status.action.ts
- libs/core/device/modules/mudita-os/presenters/response.presenter.ts
JIRA Reference: [CP-2456]
-
[CP-2456]: https://appnroll.atlassian.net/browse/CP-2456?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2456][Multidevice] Device selection screen does not show serial number for Harmony 1.8.2

- libs/core/__deprecated__/renderer/components/rest/menu/menu-bottom.component.tsx
- libs/core/core/hooks/use-device-connected-effect.ts
- libs/core/device-initialization/actions/start-initializing-device/initialize-mudita-harmony.ts
- libs/core/device-initialization/actions/start-initializing-device/initialize-mudita-pure.ts
- libs/core/device-initialization/components/eula-agreement/eula-agreement.container.tsx
- libs/core/device-manager/controllers/device-manager.controller.ts
- libs/core/device-manager/reducers/device-manager.reducer.ts
- libs/core/device/actions/get-onboarding-status.action.ts
- libs/core/device/actions/get-unlock-status.action.ts
- libs/core/device/actions/handle-communication-error.action.ts
- libs/core/device/actions/load-device-data.action.ts
- libs/core/device/constants/event.enum.ts
- libs/core/device/constants/unknown-serial-number.constant.ts
- libs/core/device/modules/mudita-os/presenters/response.presenter.ts
- libs/core/files-manager/actions/delete-files.action.test.ts
- libs/core/files-manager/actions/delete-files.action.ts
- libs/core/files-manager/actions/get-files.action.test.ts
- libs/core/files-manager/actions/get-files.action.ts
- libs/core/files-manager/actions/upload-file.action.test.ts
- libs/core/files-manager/components/files-manager/files-manager.component.tsx
- libs/core/files-manager/components/files-manager/get-spaces.helper.test.ts
- libs/core/files-manager/components/files-manager/use-disk-space-categories.hook.ts
- libs/core/files-manager/components/files-manager/use-spaces/get-spaces.helper.ts
- libs/core/files-manager/components/files-manager/use-spaces/spaces.interface.ts
- libs/core/files-manager/components/files-manager/use-spaces/use-spaces.hook.ts
- libs/core/files-manager/components/files-summary/files-summary.component.tsx
- libs/core/files-manager/reducers/files-manager.reducer.ts
JIRA Reference: [CP-2162]
- https://github.com/mudita/mudita-center/pull/1679
- https://github.com/mudita/mudita-center/pull/1680
- https://github.com/mudita/mudita-center/pull/1681
- https://github.com/mudita/mudita-center/pull/1682
- https://github.com/mudita/mudita-center/pull/1683
- https://github.com/mudita/mudita-center/pull/1678
[CP-2162]: https://appnroll.atlassian.net/browse/CP-2162?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2162][Multidevice] Multidevice Support Fixes

- libs/core/__deprecated__/renderer/locales/default/en-US.json
- libs/core/__mocks__/react-router-dom.js
- libs/core/core/components/apps/base-app/base-app.component.tsx
- libs/core/device-select/components/device-select-drawer.component.tsx
- libs/core/discovery-device/components/configured-devices-discovery.component.tsx
- libs/core/discovery-device/hooks/use-no-new-devices-detected.hook.ts
- libs/core/modals-manager/actions/base.action.ts
- libs/core/modals-manager/components/connecting-loader-modal.container.tsx
- libs/core/modals-manager/components/modals-manager.component.tsx
- libs/core/modals-manager/constants/event.enum.ts
- libs/core/modals-manager/constants/modal-layers.enum.ts
- libs/core/modals-manager/hooks/use-modal-observer.hook.ts
- libs/core/modals-manager/reducers/modals-manager.interface.ts
- libs/core/modals-manager/reducers/modals-manager.reducer.ts
- libs/core/modals-manager/selectors/is-any-other-modal-present.selector.ts
- libs/core/modals-manager/selectors/no-modals-show.selector.ts
- libs/core/ui/components/loader-modal/loader-modal.component.tsx
- libs/core/ui/components/modal-dialog/modal-dialog.component.tsx
JIRA Reference: [CP-2163]
-
[CP-2163]: https://appnroll.atlassian.net/browse/CP-2163?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2163] Connecting Loader Modal feature

- libs/core/__deprecated__/renderer/components/rest/menu/menu-bottom.component.tsx
- libs/core/__mocks__/react-router-dom.js
- libs/core/core/hooks/use-device-connected-effect.ts
- libs/core/core/hooks/use-device-detached-effect.ts
- libs/core/modals-manager/components/connecting-loader-modal.container.tsx
JIRA Reference: [CP-2166]
-
[CP-2166]: https://appnroll.atlassian.net/browse/CP-2166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2166] Handle auto connecting after detach device

- libs/core/contacts/actions/import-contact.action.test.ts
- libs/core/contacts/actions/import-contact.action.ts
- libs/core/contacts/components/contacts/contacts.component.tsx
- libs/core/contacts/components/contacts/contacts.interface.ts
- libs/core/contacts/contacts.container.tsx
- Fix import contacts during switch device
> [CP-XXX] Fix import contacts during switch device

- libs/generic-view/feature/src/lib/generic-modals.tsx
- libs/generic-view/feature/src/lib/recursive-layout.tsx
- libs/generic-view/store/src/lib/selectors/active-device-features.ts
- libs/generic-view/store/src/lib/selectors/active-device.ts
JIRA Reference: [CP-2470]
-
[CP-2470]: https://appnroll.atlassian.net/browse/CP-2470?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2470] Improved caching for generic components

- libs/device/feature/src/lib/api-config/api-config-error.ts
- libs/device/feature/src/lib/api-config/api-config.service.ts
- libs/device/feature/src/lib/api-features/api-features.service.ts
- libs/device/feature/src/lib/api-features/get-overview-data.request.ts
- libs/device/feature/src/lib/menu/menu.service.ts
- libs/device/feature/src/lib/outbox/outbox.service.ts
- libs/device/models/src/lib/api-config/api-config.test.ts
- libs/device/models/src/lib/api-config/api-config.ts
- libs/device/models/src/lib/menu/menu-config.test.ts
- libs/device/models/src/lib/menu/menu-config.ts
- libs/device/models/src/lib/outbox/outbox.test.ts
- libs/device/models/src/lib/outbox/outbox.ts
- libs/device/models/src/lib/overview/overview-config.test.ts
- libs/device/models/src/lib/overview/overview-config.ts
- libs/device/models/src/lib/overview/overview-data.test.ts
- libs/device/models/src/lib/overview/overview-data.ts
- libs/generic-view/store/src/lib/features/get-overview-data.actions.ts
- package-lock.json
- package.json
JIRA Reference: [CP-2466]
-
[CP-2466]: https://appnroll.atlassian.net/browse/CP-2466?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2466] API response validators

- libs/core/device-initialization/actions/initialize-mudita-pure.action.ts
> [CP-XXX] Sync Cache Fixed

- libs/core/crash-dump/components/crash-dump/crash-dump.component.test.tsx
- libs/core/crash-dump/components/crash-dump/crash-dump.component.tsx
- libs/core/device-initialization/components/devices-initialization-modal-flows/handle-initialize-device.helper.ts
- libs/core/device-initialization/components/devices-initialization-modal-flows/mudita-harmony-initialization-modal-flow.tsx
- libs/core/device-initialization/components/devices-initialization-modal-flows/mudita-pure-initialization-modal-flow.tsx
JIRA Reference: [CP-2390]
-
[CP-2390]: https://appnroll.atlassian.net/browse/CP-2390?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2390][Multidevice] Weird Center bahavior - it started automatically shows passcode modal closing it

- libs/core/crash-dump/components/crash-dump/crash-dump.component.test.tsx
- libs/core/crash-dump/components/crash-dump/crash-dump.component.tsx
- libs/core/device-initialization/components/devices-initialization-modal-flows/handle-initialize-device.helper.ts
- libs/core/device-initialization/components/devices-initialization-modal-flows/mudita-harmony-initialization-modal-flow.tsx
- libs/core/device-initialization/components/devices-initialization-modal-flows/mudita-pure-initialization-modal-flow.tsx
- libs/core/device/actions/unlock-device.action.ts
- libs/shared/utils/src/index.ts
- libs/shared/utils/src/lib/delay.ts
JIRA Reference: [CP-2481]
-
[CP-2481]: https://appnroll.atlassian.net/browse/CP-2481?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2481][Multidevice] Pure passcode input sometimes is failed on first attempt

- CHANGELOG.md
> [CP-XXX] 2.2.8 - CHANGELOG.md updated

- libs/core/device-initialization/components/devices-initialization-modal-flows/api-device-initialization-modal-flow.tsx
JIRA Reference: [CP-2550]
-
[CP-2550]: https://appnroll.atlassian.net/browse/CP-2550?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2550] "Show connected devices"  button is duplicated

- packages/app/src/contacts/actions/edit-contact.action.test.ts
- packages/app/src/contacts/actions/edit-contact.action.ts
- packages/app/src/contacts/components/contacts/contacts.component.tsx
- packages/app/src/contacts/components/contacts/contacts.interface.ts
- packages/app/src/contacts/contacts.container.tsx
- packages/app/src/contacts/helpers/contacts.helpers.ts
- packages/app/src/contacts/services/contact.service.ts
- packages/app/src/notification/filters/is-notification-outbox-message.ts
- packages/app/src/notification/types/notification.interface.ts
JIRA Reference: [CP-2156]
- re-open PR https://github.com/mudita/mudita-center/pull/1598
- Minor logic fixes to handle correctly edit/new action with duplicates https://github.com/mudita/mudita-center/pull/1724/commits/eb26b2213fdf4ac029e95c140939dc06ee53a21f
- Refresh data fixed after Edit Action
- Fix blank screen issue caused by incorrect type handling due to an alias https://github.com/mudita/mudita-center/pull/1724/commits/8ee76ee57779e71453e8f5549ef549e15fff640d
[CP-2156]: …
> [CP-2156][Contacts] Edit does not seem to validate the contact number and neverending sync in progress 

- libs/generic-view/store/src/lib/views/reducer.ts
> CP-2490 fix long connection

- .stylelintrc.js
- libs/generic-view/theme/src/lib/generic-theme-provider.tsx
- libs/generic-view/ui/src/lib/interactive/modal/modal-base.tsx
- libs/generic-view/ui/src/lib/interactive/modal/modal-helpers.tsx
- libs/generic-view/ui/src/lib/predefined/backup/backup-features.tsx
JIRA Reference: [CP-2490]
-
[CP-2490]: https://appnroll.atlassian.net/browse/CP-2490?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2558] Modal styles improvements

- libs/core/app-initialization/hooks/use-initializing-app-effects.ts
- libs/core/app-initialization/selectors/is-app-initialization-finished.selector.ts
- libs/core/modals-manager/actions/check-app-requires-serial-port-group-to-show.action.ts
> [CP-XXX] App Initialized Setter fixed

- .github/workflows/e2e-feature-branch.yml
- apps/mudita-center-e2e/package.json
- package.json
JIRA Reference: [CP-2658]
-Changed package.json jobs and github actions workflow to go straight to mudita-center-e2e folder for CI/CD suite of tests
[CP-2658]: https://appnroll.atlassian.net/browse/CP-2658?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-2658 Edit workflow yml to use npm run e2e:test:cicd

- libs/core/__deprecated__/renderer/components/core/button/button.styled.elements.tsx
- libs/core/__deprecated__/renderer/components/core/button/tests/__snapshots__/button.test.tsx.snap
- libs/core/__deprecated__/renderer/components/rest/menu/__snapshots__/menu.test.tsx.snap
JIRA Reference: [CP-2583]
-
[CP-2583]: https://appnroll.atlassian.net/browse/CP-2583?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2583] Unexpected animated Menu items in Mudita Center

- libs/device/feature/src/lib/api-features/api-features.service.ts
- libs/device/feature/src/lib/api-features/get-feature-configuration.request.ts
- libs/device/feature/src/lib/api-features/index.ts
- libs/generic-view/store/src/lib/features/get-generic-config.actions.ts
- libs/generic-view/views/src/index.ts
- libs/generic-view/views/src/lib/mc-features/mc-import-contacts-button.ts
JIRA Reference: [CP-2673]
-
[CP-2673]: https://appnroll.atlassian.net/browse/CP-2673?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2673] add generator

- libs/core/__deprecated__/renderer/locales/default/en-US.json
- libs/generic-view/ui/src/lib/interactive/input/checkbox-input.tsx
- libs/generic-view/ui/src/lib/predefined/import-contacts/import-contacts-list.tsx
JIRA Reference: [CP-2695]
-
[CP-2695]: https://appnroll.atlassian.net/browse/CP-2695?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2695] Select all contacts

- libs/core/__deprecated__/renderer/locales/default/en-US.json
- libs/generic-view/store/src/lib/selectors/import-contacts-selector.ts
- libs/generic-view/ui/src/lib/helpers/divider.tsx
- libs/generic-view/ui/src/lib/predefined/import-contacts/import-contacts-list.tsx
- libs/generic-view/ui/src/lib/predefined/import-contacts/import-contacts.tsx
JIRA Reference: [CP-2702]
-
[CP-2702]: https://appnroll.atlassian.net/browse/CP-2702?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
>  [CP-2702] Implemented search input on contacts list

- apps/mudita-center-e2e/.gitignore
- apps/mudita-center-e2e/src/helpers/screenshot.helper.ts
JIRA Reference: [CP-2667](https://appnroll.atlassian.net/browse/CP-2667)
- Add screenshot helper for E2E tests making PNG shot of view or element 
[CP-2667]: https://appnroll.atlassian.net/browse/CP-2667?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2667] Add screenshot helper for E2E tests

- libs/core/onboarding/components/onboarding-troubleshooting/onboarding-troubleshooting-ui-test-ids.tsx
- libs/core/onboarding/components/onboarding-troubleshooting/onboarding-troubleshooting-ui.component.tsx
- libs/core/onboarding/components/onboarding/onboarding-ui-test-ids.ts
- libs/core/onboarding/components/onboarding/onboarding-ui.component.tsx
JIRA Reference: [CP-2724]
-
[CP-2724]: https://appnroll.atlassian.net/browse/CP-2724?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> add data-testid for onboarding

- .github/auto_assign.yml
JIRA Reference: [CP-2725]
-
[CP-2725]: https://appnroll.atlassian.net/browse/CP-2725?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add Mateusz Bolewski as new reviewer in github actions

- .github/workflows/e2e-development.yml
- .github/workflows/e2e-feature-branch.yml
- .github/workflows/e2e-pre-production.yml
- .github/workflows/e2e-production.yml
- .github/workflows/nexus-feature-branch.yml
- .github/workflows/nexus-mass-update.yml
- .github/workflows/nexus-pre-production-latest.yml
- .github/workflows/nexus-production-with-os-rc.yml
JIRA Reference: [CP-2690]
-
[CP-2690]: https://appnroll.atlassian.net/browse/CP-2690?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2690] Added yml e2e job for development, release-candidates and main branch

- .github/workflows/e2e-production.yml
JIRA Reference: [CP-2727]
-
[CP-2727]: https://appnroll.atlassian.net/browse/CP-2727?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2727] e2e-production.yml fixed

- apps/mudita-center/package-lock.json
- apps/mudita-center/package.json
- libs/core/__deprecated__/renderer/constants/menu-elements.ts
- libs/core/onboarding/components/onboarding/onboarding-ui.component.tsx
- package-lock.json
- package.json
v2.3.0-rc.1
- 8e5e80506d490362f70b2f296a210436dbb8eb65 - deviceNames removed from onboarding
- ffdb6d81fd5a9c3013e04045c3d7573690312fc9 - Onboarding element removed from navigation
> v2.3.0-rc.1

- libs/generic-view/ui/src/lib/interactive/form/form.tsx
- libs/generic-view/ui/src/lib/interactive/form/input/checkbox-input.tsx
- libs/generic-view/ui/src/lib/interactive/form/input/radio-input.tsx
- libs/generic-view/ui/src/lib/interactive/form/input/search-input.tsx
- libs/generic-view/ui/src/lib/interactive/form/input/text-input.tsx
- libs/generic-view/ui/src/lib/interactive/interactive.ts
- libs/generic-view/ui/src/lib/predefined/backup-restore/backup-restore-password.tsx
- libs/generic-view/ui/src/lib/predefined/backup-restore/backup-restore-select.tsx
- libs/generic-view/ui/src/lib/predefined/backup/backup-password.tsx
- libs/generic-view/ui/src/lib/predefined/import-contacts/import-contacts-list.tsx
JIRA Reference: [CP-2728]
-
[CP-2728]: https://appnroll.atlassian.net/browse/CP-2728?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2728] Refactored Form related components to dot notation

- .github/workflows/e2e-development.yml
- .github/workflows/e2e-feature-branch.yml
- .github/workflows/e2e-pre-production.yml
- .github/workflows/e2e-production.yml
- .github/workflows/nexus-development.yml
- .github/workflows/nexus-feature-branch.yml
- .github/workflows/nexus-mass-update.yml
- .github/workflows/nexus-pre-production-latest.yml
- .github/workflows/nexus-pre-production.yml
- .github/workflows/nexus-production-with-os-rc.yml
- .github/workflows/nexus-production.yml
- libs/core/desktop/desktop.service.ts
- libs/core/modals-manager/actions/check-app-requires-serial-port-group-to-show.action.ts
JIRA Reference: [CP-2775]
-
[CP-2775]: https://appnroll.atlassian.net/browse/CP-2775?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2775] Allow USB port access not displayed - Manage Serial Port Access not works

- libs/core/crash-dump/components/crash-dump/crash-dump.component.test.tsx
- libs/core/crash-dump/components/crash-dump/crash-dump.component.tsx
JIRA Reference: [CP-2765]
-
[CP-2765]: https://appnroll.atlassian.net/browse/CP-2765?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2765] Selecting device and disconnecting it during checking connection causes a crash dump procedure in MC

- libs/generic-view/store/src/lib/imports/import-contacts-from-external-source.action.ts
JIRA Reference: [CP-2795]
-
[CP-2795]: https://appnroll.atlassian.net/browse/CP-2795?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2795] add note to contacts google import

- libs/core/contacts/components/contacts/contacts.component.tsx
JIRA Reference: [CP-2809]
-
[CP-2809]: https://appnroll.atlassian.net/browse/CP-2809?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2809] Improper error appears when user wants to Save the eiditing process for deleted contact

- apps/mudita-center/package-lock.json
- apps/mudita-center/package.json
- libs/core/__deprecated__/renderer/wrappers/app-update-step-modal/app-update-step-modal.component.tsx
- libs/core/app-initialization/selectors/is-app-update-process-passed.selector.ts
- libs/core/app-initialization/selectors/should-app-update-flow-visible.selector.ts
- libs/core/contacts/components/contacts/contacts.component.tsx
- libs/core/settings/actions/base.action.ts
- libs/core/settings/actions/load-settings.action.test.ts
- libs/core/settings/actions/load-settings.action.ts
- package-lock.json
- package.json
> v2.3.0-rc.3

- LICENSE.md
- apps/mudita-center/package.json
JIRA Reference: [CP-2821]
-
[CP-2821]: https://appnroll.atlassian.net/browse/CP-2821?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2821] Outdated Copyright on macOS

- libs/core/__deprecated__/renderer/components/core/input-search/input-search.component.tsx
JIRA Reference: [CP-2830]
-
[CP-2830]: https://appnroll.atlassian.net/browse/CP-2830?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2830] Grey highlight is faster than the scroll tool on the right side of the contact search list

- libs/core/__deprecated__/renderer/components/core/modal/modal.styled.elements.tsx
- libs/core/device-select/components/device-select-drawer.component.tsx
- libs/core/device-select/components/drawer-device.component.tsx
JIRA Reference: [CP-2802]
-
[CP-2802]: https://appnroll.atlassian.net/browse/CP-2802?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2802] Incorrect MDS UI Implementation in Devices Drawer

- libs/core/app-initialization/selectors/is-app-update-process-passed.selector.ts
JIRA Reference: [CP-2867] [CP-2868]
-
[CP-2867]: https://appnroll.atlassian.net/browse/CP-2867?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CP-2868]: https://appnroll.atlassian.net/browse/CP-2868?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2867][CP-2868]

- apps/mudita-center/package-lock.json
- apps/mudita-center/package.json
- libs/core/app-initialization/selectors/is-app-update-process-passed.selector.ts
- package-lock.json
- package.json
> v2.3.0-rc.5

- libs/core/settings/store/migrations/002-privacy-policy-accepted.migration.ts
JIRA Reference: [CP-2877]
-
[CP-2877]: https://appnroll.atlassian.net/browse/CP-2877?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2877] 2.3.0 - Accept Privacy Policy after opening the MC .

- apps/mudita-center-e2e/src/page-objects/mc-update-modal.page.ts
- apps/mudita-center-e2e/src/page-objects/settings.page.ts
- apps/mudita-center-e2e/src/specs/settings/mc-version-check-for-updates-offline.e2e.ts
- apps/mudita-center-e2e/src/specs/settings/mc-version-check-for-updates.e2e.ts
- apps/mudita-center-e2e/src/test-filenames/consts/test-filenames.const.ts
- apps/mudita-center-e2e/wdio.conf.ts
JIRA Reference: [CP-2293](https://appnroll.atlassian.net/browse/CP-2293)
- Open Settings
- Click About
- Check for updates
[CP-2293]: https://appnroll.atlassian.net/browse/CP-2293?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2293] [E2E][Settings][About] Check for updates (offline)

- apps/mudita-center-e2e/src/specs/news/news-check-online.e2e.ts
- libs/core/core/components/apps/base-app/base-app.component.tsx
> [CP-XXX] Fix lint after resolve conflicts during rebase with main

- apps/mudita-center-e2e/src/page-objects/modal-privacy-policy.page.ts
- apps/mudita-center-e2e/src/specs/settings/privacy-policy.e2e.ts
- apps/mudita-center-e2e/src/test-filenames/consts/test-filenames.const.ts
- apps/mudita-center-e2e/wdio.conf.ts
JIRA Reference: [CP-2296](https://appnroll.atlassian.net/browse/CP-2296)
- Open Settings
- Click About
- Click Privacy Policy
- Verify contents
- Scroll down
- Close modal 
[CP-2296]: https://appnroll.atlassian.net/browse/CP-2296?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2296] [E2E][Settings][About] Privacy Policy

- apps/mudita-center-e2e/src/specs/news/news-check-online.e2e.ts
JIRA Reference: [CP-2876]
- Removed logs from News-Check-Online test
[CP-2876]: https://appnroll.atlassian.net/browse/CP-2876?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-2876 Removed logs

- .github/workflows/nexus-mock-development.yml
JIRA Reference: [CP-2906]
-
[CP-2906]: https://appnroll.atlassian.net/browse/CP-2906?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2906] add mock build for development branch

- .github/workflows/nexus-mock-pre-production.yml
JIRA Reference: [CP-2911]
-
[CP-2911]: https://appnroll.atlassian.net/browse/CP-2911?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> add mock build for RC

- .github/workflows/nexus-mock-pre-production.yml
- .github/workflows/nexus-mock-production.yml
JIRA Reference: [CP-2916]
-
[CP-2916]: https://appnroll.atlassian.net/browse/CP-2916?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2916] Add mock production build

- libs/electron/application-updater/src/lib/application-updater.module.ts
> Fix mock updater

- libs/shared/http-client/src/lib/http-client.factory.ts
> disable HttpClientService for axios.create

- libs/generic-view/ui/src/lib/blocks/block-box.tsx
- libs/generic-view/ui/src/lib/predefined/overview-os-version.tsx
- libs/generic-view/utils/src/lib/models/api-fc.types.ts
JIRA Reference: [CP-2945]
-
[CP-2945]: https://appnroll.atlassian.net/browse/CP-2945?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2945] add data-testid for overview update section

- .github/workflows/nexus-mock-pre-production.yml
- .github/workflows/nexus-mock-production.yml
- apps/mudita-center/package-lock.json
- apps/mudita-center/package.json
- libs/core/__deprecated__/renderer/constants/menu-elements.ts
- libs/core/feature-flags/constants/feature.enum.ts
- libs/core/feature-flags/features/index.ts
- package-lock.json
> v2.3.1-rc.1

- apps/mudita-center/package-lock.json
- apps/mudita-center/package.json
- libs/core/device-select/components/device-select-drawer.component.tsx
- package-lock.json
> 2.3.1-rc.2

- .github/workflows/nexus-mock-development.yml
> [CP-2940] Allow Opening of Developer Tools in Mock Environment - vol.2

- .github/workflows/nexus-mock-development.yml
- libs/e2e-mock/server/README.md
JIRA Reference: [CP-2749]
-
[CP-2749]: https://appnroll.atlassian.net/browse/CP-2749?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2749] Update readme.md

- .github/workflows/nexus-development.yml
- .github/workflows/nexus-feature-branch.yml
- .github/workflows/nexus-mass-update.yml
- .github/workflows/nexus-mock-development.yml
- .github/workflows/nexus-mock-pre-production.yml
- .github/workflows/nexus-mock-production.yml
- .github/workflows/nexus-pre-production-latest.yml
- .github/workflows/nexus-pre-production.yml
- .github/workflows/nexus-production-with-os-rc.yml
- .github/workflows/nexus-production.yml
> [CP-XXX] Skip sign for windows

- libs/generic-view/ui/src/lib/predefined/about-data-box.tsx
> Add data-testid to about data row

- libs/core/__deprecated__/renderer/locales/default/en-US.json
- libs/help/models/src/lib/help-data.types.ts
- libs/help/ui/src/lib/article-page.tsx
- libs/help/ui/src/lib/components/article-external-links.tsx
JIRA Reference: [CP-2988]
-
[CP-2988]: https://appnroll.atlassian.net/browse/CP-2988?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2988] (6/6) I want to open a link to a similar article on the Mudita Customer Support site

- .github/workflows/nexus-development.yml
- .github/workflows/nexus-feature-branch.yml
- .github/workflows/nexus-mass-update.yml
- .github/workflows/nexus-mock-development.yml
- .github/workflows/nexus-mock-pre-production.yml
- .github/workflows/nexus-mock-production.yml
- .github/workflows/nexus-pre-production-latest.yml
- .github/workflows/nexus-pre-production.yml
- .github/workflows/nexus-production-with-os-rc.yml
- .github/workflows/nexus-production.yml
- apps/mudita-center/package-lock.json
- apps/mudita-center/package.json
- libs/core/__deprecated__/renderer/constants/menu-elements.ts
- libs/core/device-select/components/device-select-drawer.component.tsx
- libs/core/feature-flags/constants/feature.enum.ts
- libs/core/feature-flags/features/index.ts
- package-lock.json
> Release v2.3.1 - to stage

- .github/workflows/nexus-development.yml
- .github/workflows/nexus-feature-branch.yml
- .github/workflows/nexus-mass-update.yml
- .github/workflows/nexus-mock-development.yml
- .github/workflows/nexus-mock-pre-production.yml
- .github/workflows/nexus-mock-production.yml
- .github/workflows/nexus-pre-production-latest.yml
- .github/workflows/nexus-pre-production.yml
- .github/workflows/nexus-production-with-os-rc.yml
- .github/workflows/nexus-production.yml
> Skip sign for windows

- libs/generic-view/views/src/lib/mc-overview/mc-overview.ts
> Fix restore for API Devices

- libs/core/app-initialization/actions/start-initializing-app.ts
> CP-XXX: Handle Tracick Request Timeout Issue vol.2

- libs/core/contacts/actions/authorize.action.test.ts
- libs/core/contacts/actions/authorize.action.ts
> fix google auth for pure

- libs/generic-view/ui/src/lib/data-rows/text-formatted.tsx
JIRA Reference: [CP-3016]
https://github.com/user-attachments/assets/0dec8a6f-41fa-42ba-aebc-cde8dee6d12d
[CP-3016]: https://appnroll.atlassian.net/browse/CP-3016?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3016] Improved text styling in formatted text component

- libs/device/models/src/lib/import-contacts/unified-contact.ts
- libs/generic-view/store/src/lib/imports/contacts-mappers/pure/map-pure-api.ts
JIRA Reference: [CP-2992]
-
[CP-2992]: https://appnroll.atlassian.net/browse/CP-2992?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2992] Added missing contact fields to data migration process

- apps/mudita-center-e2e/src/consts/regex-const.ts
- apps/mudita-center-e2e/src/page-objects/about-kompakt.page.ts
- apps/mudita-center-e2e/src/page-objects/menu.page.ts
- apps/mudita-center-e2e/src/page-objects/modal-sar.page.ts
- apps/mudita-center-e2e/src/page-objects/overview-kompakt.page.ts
- apps/mudita-center-e2e/src/specs/overview/kompakt-about.ts
- apps/mudita-center-e2e/src/test-filenames/consts/test-filenames.const.ts
- apps/mudita-center-e2e/wdio.conf.ts
JIRA Reference: [CP-2754](https://appnroll.atlassian.net/browse/CP-2754)
-
[CP-2754]: https://appnroll.atlassian.net/browse/CP-2754?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2754] [API Device][Kompakt] About your Kompakt

- libs/core/discovery-device/components/device-list-item.component.tsx
- libs/core/discovery-device/components/device-list.component.tsx
> add data-testids for select device page

- libs/core/__deprecated__/renderer/locales/default/en-US.json
- libs/generic-view/ui/src/lib/predefined/backup/backup-features.tsx
> remove call logs placeholder in backup

- apps/mudita-center-e2e/src/page-objects/drawer.page.ts
- apps/mudita-center-e2e/src/specs/stress-tests/device-drawer-stress-test.ts
- apps/mudita-center-e2e/src/test-filenames/consts/test-filenames.const.ts
- apps/mudita-center-e2e/wdio.conf.ts
JIRA Reference: [CP-2919]
Open App
Connect 1st Kompakt
Connect 2nd Kompakt
Wait until Device drawer shows up 
Verify Device Drawer devices
Connect 3rd Kompakt
Verify Device Drawer devices
Connect 4th Kompakt, Connect 5th Kompakt, Connect 6th Kompakt
Verify Device Drawer devices (Names and serial numbers) and UI and scroll
Click 6th Kompakt 
Verify Overview - and a new Serial Number
Click Show Connected Devices
Disconnect all Kompakts
Verify Welcome Page Screen is displayed
[CP-2919]: https://appnroll.atlassian.net/browse/CP-2919?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-2919 [API Device][Multidevice] Device drawer - stress test

- libs/core/messages/components/receiver-input-search/receiver-input-search.component.tsx
- libs/generic-view/store/src/lib/imports/reducer.ts
- libs/help/ui/src/lib/components/article-warning.tsx
- libs/help/ui/src/lib/components/articles-list.tsx
- libs/help/ui/src/lib/components/category-tabs.tsx
- libs/help/ui/src/lib/components/search-results.tsx
- libs/help/ui/src/lib/components/search.tsx
- libs/help/ui/src/lib/test-ids.ts
JIRA Reference: [CP-3070]
-
[CP-3070]: https://appnroll.atlassian.net/browse/CP-3070?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3070] Help improvements for E2E

- package-lock.json
- package.json
> [CP-XXX] Remove version field from root package.json

- libs/device/feature/src/lib/file-manager/file-manager.service.ts
JIRA Reference: [CP-3086]
-
[CP-3086]: https://appnroll.atlassian.net/browse/CP-3086?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3086] RC: Fixed chunks joining for backup files

- libs/device/feature/src/lib/file-manager/file-manager.service.ts
JIRA Reference: [CP-3086]
-
[CP-3086]: https://appnroll.atlassian.net/browse/CP-3086?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3086] Fixed chunks joining for backup files

- apps/mudita-center/package-lock.json
- apps/mudita-center/package.json
- libs/core/core/hooks/use-device-connected-effect.ts
- libs/core/device-initialization/components/devices-initialization-modal-flows/api-device-initialization-modal-flow.tsx
- libs/device/feature/src/lib/file-manager/file-manager.service.ts
- libs/generic-view/store/src/lib/hooks/use-locked-device-handler.ts
- libs/generic-view/store/src/lib/selectors/api-error.ts
- libs/generic-view/store/src/lib/selectors/is-device-locked-error.selector.ts
- libs/generic-view/store/src/lib/views/reducer.ts
- libs/generic-view/ui/src/lib/predefined/backup/backup-password.tsx
- package-lock.json
- package.json
> Release v2.4.0 - to stage

- libs/core/contact-support/components/contact-support-modal-success.component.tsx
- libs/e2e-test-ids/.eslintrc.json
- libs/e2e-test-ids/README.md
- libs/e2e-test-ids/project.json
- libs/e2e-test-ids/src/e2e-test-ids.ts
- libs/e2e-test-ids/src/index.ts
- libs/e2e-test-ids/tsconfig.json
- libs/e2e-test-ids/tsconfig.lib.json
- libs/generic-view/theme/src/lib/generic-theme-provider.tsx
- libs/generic-view/ui/src/lib/interactive/modal/helpers/modal-close-button.tsx
- nx.json
- tsconfig.base.json
JIRA Reference: [CP-3093]
<details>
<summary>Show images</summary>
</details>
[CP-3093]: https://appnroll.atlassian.net/browse/CP-3093?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3093] Add data-testid to Success modal for Contact Support Form sending

- libs/e2e-test-ids/src/e2e-test-ids.ts
- libs/generic-view/ui/src/lib/predefined/backup/backup-features.tsx
JIRA Reference: [CP-3119]
-
[CP-3119]: https://appnroll.atlassian.net/browse/CP-3119?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3119] Added data testid to Create Backup Action

- libs/e2e-test-ids/src/e2e-test-ids.ts
- libs/generic-view/ui/src/lib/predefined/backup/backup-features.tsx
JIRA Reference: [CP-3132]
-
[CP-3132]: https://appnroll.atlassian.net/browse/CP-3132?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3132] Added data testid to Cancel Backup Action

- libs/generic-view/feature/src/lib/setup-component.tsx
JIRA Reference: [CP-3004]
-
[CP-3004]: https://appnroll.atlassian.net/browse/CP-3004?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3004] Refactored layout propagation for generic components

- .github/workflows/e2e-feature-branch.yml
> Cp e2e - Windows/Linux fix for self-hosted

- libs/e2e-mock/responses/src/lib/default-responses.ts
JIRA Reference: [CP-3150]
fixed typo 
-
[CP-3150]: https://appnroll.atlassian.net/browse/CP-3150?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-3150 fixed typo contacts to contact

- libs/generic-view/models/src/lib/form-checkbox-input.ts
- libs/generic-view/ui/src/lib/interactive/form/input/checkbox-input.tsx
- libs/generic-view/ui/src/lib/predefined/data-migration/components/features-selector.tsx
- libs/generic-view/ui/src/lib/predefined/import-contacts/import-contacts-list.tsx
JIRA Reference: [CP-3004]
-
[CP-3004]: https://appnroll.atlassian.net/browse/CP-3004?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3004] Added more sizes to checkbox-input

- libs/generic-view/feature/src/lib/use-dev-views/views/contacts-view.ts
- libs/generic-view/ui/src/lib/interactive/form/input/checkbox-input.tsx
- libs/generic-view/ui/src/lib/table/table.tsx
JIRA Reference: [CP-3143]
<details>
<summary>Screenshot</summary>
</details>
[CP-3143]: https://appnroll.atlassian.net/browse/CP-3143?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3143] Style the contacts list: Add remaining styles—spacing and borders

- libs/generic-view/feature/src/lib/seed-data/contacts-seed-data.ts
JIRA Reference: [CP-3147]
-
[CP-3147]: https://appnroll.atlassian.net/browse/CP-3147?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3147] Extended contact seed data with various fallback variants (company, email, address, phone number)

- libs/device/models/src/lib/feature/data-provider-config.test.ts
- libs/device/models/src/lib/feature/data-provider-config.ts
- libs/device/models/src/lib/feature/feature-config.test.ts
- libs/generic-view/feature/src/lib/setup-component.tsx
- libs/generic-view/feature/src/lib/use-dev-views/views/contacts-view.ts
- libs/generic-view/utils/src/lib/data-provider-helpers/data-provider-filter.test.ts
- libs/generic-view/utils/src/lib/data-provider-helpers/data-provider-filter.ts
- libs/generic-view/utils/src/lib/data-provider-helpers/data-provider-sort.test.ts
- libs/generic-view/utils/src/lib/data-provider-helpers/data-provider-sort.ts
-
[CP-2995]: https://appnroll.atlassian.net/browse/CP-2995?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2995] Refactored data provider

- libs/generic-view/feature/src/lib/seed-data/contacts-seed-data.ts
JIRA Reference: [CP-3147]
-
[CP-3147]: https://appnroll.atlassian.net/browse/CP-3147?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3147] Added different phone number formats

- libs/device/models/src/lib/feature/data-provider-config.ts
- libs/generic-view/feature/src/lib/setup-component.tsx
- libs/generic-view/feature/src/lib/use-dev-views/views/contacts-view.ts
- libs/generic-view/ui/src/lib/data-rows/badge.tsx
- libs/generic-view/ui/src/lib/interactive/tooltip/tooltip.tsx
JIRA Reference: [CP-3145]
<details>
</details>
[CP-3145]: https://appnroll.atlassian.net/browse/CP-3145?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3145] Implement a column displaying the number of phone numbers along with a details tooltip

- libs/generic-view/models/src/lib/entities-loader.ts
- libs/generic-view/store/src/lib/entities/reducer.ts
- libs/generic-view/store/src/lib/selectors/entities.ts
- libs/generic-view/ui/src/lib/entities/entities-loader.tsx
-
[CP-2995]: https://appnroll.atlassian.net/browse/CP-2995?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2995] Implemented progress bar for entities loader

- libs/core/__deprecated__/renderer/components/core/text/text.component.tsx
- libs/core/__deprecated__/renderer/components/rest/header/__snapshots__/header.test.tsx.snap
- libs/core/__deprecated__/renderer/components/rest/header/header.component.tsx
- libs/generic-view/feature/src/lib/use-dev-views/views/contacts-view.ts
- libs/generic-view/models/src/index.ts
- libs/generic-view/models/src/lib/app-portal.ts
- libs/generic-view/ui/src/lib/data-rows/app-portal.tsx
- libs/generic-view/ui/src/lib/data-rows/data-rows.ts
JIRA Reference: [CP-3004]
-
[CP-3004]: https://appnroll.atlassian.net/browse/CP-3004?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3004] Added app portal component

- libs/generic-view/feature/src/lib/use-dev-views/views/contacts-view.ts
- libs/generic-view/ui/src/lib/predefined/import-contacts/import-contacts-list.tsx
-
[CP-2995]: https://appnroll.atlassian.net/browse/CP-2995?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2995] Contacts import list style fix

- apps/mudita-center-e2e/src/page-objects/help-article.page.ts
- apps/mudita-center-e2e/src/specs/help/help-verify-feedback.ts
- apps/mudita-center-e2e/src/test-filenames/consts/test-filenames.const.ts
- apps/mudita-center-e2e/wdio.conf.ts
… updated wdio.conf.ts and test-filenames.const.ts
JIRA Reference: [CP-3182]
1. Open Article One 
2. Click Yes on “was this article helpful” question Verify Yes button background and state
3. Verify
4. Open Article Two
5. Click No on “was this article helpful” question Verify No button background and state
6. Verify 
-
[CP-3182]: https://appnroll.atlassian.net/browse/CP-3182?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-3182 Help Section - Was this article helpful (yes, no)

- apps/mudita-center-e2e/src/page-objects/help.page.ts
- apps/mudita-center-e2e/src/specs/help/help-section-search-noresults.e2e.ts
- apps/mudita-center-e2e/src/test-filenames/consts/test-filenames.const.ts
- apps/mudita-center-e2e/wdio.conf.ts
…updated wdio.conf.ts and test-filenames.const.ts
JIRA Reference: [CP-3181]
[CP-3181]: https://appnroll.atlassian.net/browse/CP-3181?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-3181 [Help Section] Example of no results in search bar of Help Section

- libs/core/__deprecated__/renderer/locales/default/en-US.json
> [CP-3208] Update warning message in MSC flash process

- .env.example
- libs/generic-view/feature/src/lib/use-dev-console.ts
JIRA Reference: [CP-3217]
-
[CP-3217]: https://appnroll.atlassian.net/browse/CP-3217?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3217] Enable useDevConsole for development, mock-development environments, and feature branches

- apps/mudita-center-e2e/src/page-objects/help.page.ts
- apps/mudita-center-e2e/src/page-objects/home.page.ts
- apps/mudita-center-e2e/src/page-objects/tabs.page.ts
- apps/mudita-center-e2e/src/specs/help/help-section-search-noresults.e2e.ts
JIRA Reference: [[CP-3204](https://appnroll.atlassian.net/browse/CP-3204)]
[CP-3204]: https://appnroll.atlassian.net/browse/CP-3204?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3204] [E2E] [HELP] Help Page and Home Page refactor

- apps/mudita-center-e2e/src/page-objects/help-article.page.ts
- apps/mudita-center-e2e/src/specs/help/help-link-inside-container.ts
- apps/mudita-center-e2e/src/test-filenames/consts/test-filenames.const.ts
- apps/mudita-center-e2e/wdio.conf.ts
…, updated wio.conf.ts and test-filenames.ts
JIRA Reference: [CP-3183]
Link inside container of How To delete files from Pure
-
[CP-3183]: https://appnroll.atlassian.net/browse/CP-3183?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-3183 Link inside container of How To delete files from Pure

- libs/generic-view/feature/src/lib/seed-data/contacts-seed-data.ts
> [CP-XXX] Extend Seed Data with Edge Cases: Long Names & Special Characters in Contact Fields

- libs/generic-view/feature/src/lib/seed-data/contacts-seed-data.ts
> [CP-XXX] Add Seed Data with Edge Cases: Emoji-Only Fields in Contact Entries

- libs/generic-view/utils/src/lib/data-sort/data-sort.test.ts
> [CP-XXX] Add test for alphanumeric sorting of numeric strings

- libs/core/data-sync/actions/read-all-indexes.action.test.ts
- libs/core/data-sync/actions/read-all-indexes.action.ts
- libs/core/data-sync/constants/index.constant.ts
- libs/core/data-sync/indexes/alarm-indexer.ts
- libs/core/data-sync/indexes/index.ts
- libs/core/data-sync/presenters/index.ts
- libs/core/data-sync/services/data-sync.service.ts
- libs/core/data-sync/types/all-indexes.type.ts
- libs/core/index-storage/constants/data-index.constant.ts
JIRA Reference: [CP-3251]
-
[CP-3251]: https://appnroll.atlassian.net/browse/CP-3251?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3251] Implement Alarm indexer for Mudita Pure

- libs/device/models/src/lib/data-transfer/data-transfer.test.ts
- libs/device/models/src/lib/data-transfer/data-transfer.ts
- libs/generic-view/store/src/lib/data-migration/transfer-migration-data.ts
- libs/generic-view/store/src/lib/data-transfer/transfer-data-to-device.action.ts
JIRA Reference: [CP-3253]
-
[CP-3253]: https://appnroll.atlassian.net/browse/CP-3253?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3253] Implement data transfer with configuration from Kompakt

- libs/generic-view/theme/src/lib/color.ts
- libs/generic-view/ui/src/lib/interactive/form/input/checkbox-input.tsx
- libs/generic-view/ui/src/lib/table/table.tsx
JIRA Reference: [CP-2997]
[CP-2997]: https://appnroll.atlassian.net/browse/CP-2997?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2997] Contact Details - row interactions

- libs/device/models/src/lib/feature/layout-config.ts
- libs/generic-view/feature/src/lib/setup-component.tsx
- libs/generic-view/feature/src/lib/use-dev-views/views/contacts-view.ts
- libs/generic-view/ui/src/lib/table/table.tsx
JIRA Reference: [CP-2997]
-
[CP-2997]: https://appnroll.atlassian.net/browse/CP-2997?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2997] Contact details improvements

- libs/device/feature/src/lib/api-config/api-config.service.ts
- libs/device/feature/src/lib/api-config/dev-api-config.adapter.ts
- libs/device/feature/src/lib/menu/dev-menu.adapter.ts
- libs/device/feature/src/lib/menu/menu.service.ts
- libs/generic-view/feature/src/lib/use-dev-views/views/contacts-view.ts
- libs/generic-view/feature/src/lib/use-dev-views/views/file-manager-view.ts
- libs/generic-view/feature/src/lib/use-dev-views/views/index.ts
- libs/generic-view/feature/src/lib/use-dev-views/views/mc-data-migration-view.ts
- libs/generic-view/models/src/index.ts
- libs/generic-view/models/src/lib/mc-file-manager-view.ts
- libs/generic-view/ui/src/lib/generated/index.ts
- libs/generic-view/ui/src/lib/generated/mc-file-manager-view.ts
- libs/generic-view/ui/src/lib/icon/get-icon.helper.tsx
- libs/generic-view/utils/src/lib/generate-menu/generate-menu.ts
- libs/generic-view/utils/src/lib/models/icons.types.ts
JIRA Reference: [CP-3289]
-
[CP-3289]: https://appnroll.atlassian.net/browse/CP-3289?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3289] Initialize - View Structure

- libs/core/__deprecated__/renderer/locales/default/en-US.json
- libs/device/models/src/lib/feature/data-provider-config.ts
- libs/generic-view/feature/src/lib/seed-data/contacts-seed-data.ts
- libs/generic-view/models/src/index.ts
- libs/generic-view/models/src/lib/form-search-input-results.ts
- libs/generic-view/models/src/lib/form-search-input.ts
- libs/generic-view/models/src/lib/highlight-text.ts
- libs/generic-view/models/src/lib/mc-contacts-search-results.ts
- libs/generic-view/ui/src/lib/generated/mc-contacts-view.ts
- libs/generic-view/ui/src/lib/interactive/form/input/search-input.tsx
- libs/generic-view/ui/src/lib/interactive/form/input/search-results.tsx
- libs/generic-view/ui/src/lib/predefined/contacts/mc-contacts-search-result.tsx
- libs/generic-view/ui/src/lib/predefined/predefined.ts
- libs/generic-view/ui/src/lib/texts/highlight-text.test.tsx
- libs/generic-view/ui/src/lib/texts/highlight-text.tsx
- libs/generic-view/ui/src/lib/texts/paragraphs.tsx
- libs/generic-view/utils/src/lib/data-search/data-search.ts
JIRA Reference: [CP-2996]
-
[CP-2996]: https://appnroll.atlassian.net/browse/CP-2996?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2996] Implemented search results for search component

- libs/device-manager/feature/src/hooks/use-device-manager-detached.ts
> [CP-XXX] Fix after develop rebase

- apps/mudita-center-e2e/src/specs/news/news-check-offline.e2e.ts
- apps/mudita-center-e2e/src/specs/news/news-check-online.e2e.ts
> skip news test - to revert

- libs/generic-view/models/src/lib/mc-file-manager-view.ts
- libs/generic-view/models/src/lib/segment-bar.ts
- libs/generic-view/store/src/lib/outbox/get-outbox-data.action.ts
- libs/generic-view/ui/src/lib/generated/mc-file-manager/color.ts
- libs/generic-view/ui/src/lib/generated/mc-file-manager/file-category-list.ts
- libs/generic-view/ui/src/lib/generated/mc-file-manager/mc-file-manager-data.ts
- libs/generic-view/ui/src/lib/generated/mc-file-manager/mc-file-manager-view.ts
- libs/generic-view/ui/src/lib/generated/mc-file-manager/storage-summary-bar.ts
- libs/generic-view/ui/src/lib/segment-bar/segment-bar-item.tsx
- libs/generic-view/ui/src/lib/segment-bar/segment-bar.tsx
JIRA Reference: [CP-3331]
-
[CP-3331]: https://appnroll.atlassian.net/browse/CP-3331?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3331] Handle real-time file refresh triggered by changes made directly on Kompakt (entity add/delete)

- libs/generic-view/models/src/lib/segment-bar.ts
- libs/generic-view/models/src/lib/tooltip.ts
- libs/generic-view/ui/src/lib/generated/mc-file-manager/mc-file-manager-data.ts
- libs/generic-view/ui/src/lib/generated/mc-file-manager/storage-summary-bar.ts
- libs/generic-view/ui/src/lib/interactive/tooltip/tooltip.tsx
- libs/generic-view/ui/src/lib/segment-bar/segment-bar-item.tsx
- libs/generic-view/ui/src/lib/segment-bar/segment-bar.tsx
JIRA Reference: [CP-3324]
-
[CP-3324]: https://appnroll.atlassian.net/browse/CP-3324?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3324] Implement Cursor-Based Tooltip Strategy

- .github/workflows/e2e-feature-branch.yml
- .github/workflows/e2e-mock-feature-branch.yml
- .github/workflows/nexus-feature-branch.yml
JIRA Reference: [CP-3344]
-
[CP-3344]: https://appnroll.atlassian.net/browse/CP-3344?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3344] Fixed GitHub Actions

- .github/workflows/nexus-feature-branch.yml
- scripts/notarize.js
> [CP-XXX] Handle skip macOS codesign & notarization for feature branch

- .github/workflows/e2e-development.yml
- .github/workflows/e2e-feature-branch.yml
- .github/workflows/e2e-mock-development.yml
- .github/workflows/e2e-mock-feature-branch.yml
- .github/workflows/e2e-mock-pre-production.yml
- .github/workflows/e2e-mock-production.yml
- .github/workflows/e2e-pre-production.yml
- .github/workflows/e2e-production.yml
- .github/workflows/nexus-feature-branch.yml
> Actions fixes

- .github/workflows/e2e-feature-branch.yml
- .github/workflows/e2e-mock-feature-branch.yml
- .github/workflows/nexus-feature-branch.yml
- scripts/notarize.js
> [CP-XXX] Update ref_name to github.head_ref

- .github/workflows/e2e-feature-branch.yml
> Adding macOS to workflow

- .github/workflows/e2e-feature-branch.yml
> Cp xxx openport test

- libs/generic-view/feature/src/lib/use-dev-views/views/file-manager-view.ts
- libs/generic-view/ui/src/lib/generated/mc-file-manager/delete-files.ts
- libs/generic-view/ui/src/lib/generated/mc-file-manager/file-category-list.ts
- libs/generic-view/ui/src/lib/generated/mc-file-manager/file-list.ts
- libs/generic-view/ui/src/lib/generated/mc-file-manager/storage-summary-bar.ts
- libs/generic-view/ui/src/lib/interactive/tooltip/tooltip.tsx
JIRA Reference: [CP-3218]
-
[CP-3218]: https://appnroll.atlassian.net/browse/CP-3218?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3218] Delete files

- libs/generic-view/ui/src/lib/generated/mc-file-manager/file-list.ts
JIRA Reference: [CP-3188]
-
[CP-3188]: https://appnroll.atlassian.net/browse/CP-3188?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3188] I want to open the category of ebooks files and see the list of available

- libs/generic-view/models/src/lib/mc-file-manager.ts
- libs/generic-view/ui/src/lib/generated/mc-file-manager/file-category-list.ts
- libs/generic-view/ui/src/lib/generated/mc-file-manager/mc-file-manager-data.ts
- libs/generic-view/ui/src/lib/generated/mc-file-manager/storage-page.ts
> [CP-XXX] New rounding strategy introduced

- libs/generic-view/store/src/lib/imports/start-contacts-import-to-device.ts
JIRA Reference: [CP-3400]
-
[CP-3400]: https://appnroll.atlassian.net/browse/CP-3400?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3400] Fixed not refreshing contacts after aborting import process

- libs/core/__deprecated__/renderer/utils/create-freshdesk-ticket/create-freshdesk-ticket.ts
- libs/core/__deprecated__/renderer/utils/create-freshdesk-ticket/create-freshdesk-ticket.types.ts
- libs/core/contact-support/actions/send-ticket.action.test.ts
- libs/core/contact-support/actions/send-ticket.action.ts
- libs/device/models/src/lib/api-config/api-config.ts
JIRA Reference: [CP-3352]
-
[CP-3352]: https://appnroll.atlassian.net/browse/CP-3352?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3352] Added DeviceID field on ticket sending

- libs/generic-view/ui/src/lib/buttons/button-base/use-upload-files-button-action.ts
- libs/generic-view/ui/src/lib/generated/mc-file-manager/mc-file-manager-data.ts
JIRA Reference: [CP-3412]
-
[CP-3412]: https://appnroll.atlassian.net/browse/CP-3412?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3412] RC: uploading files is failing, also free space is not sohwn properly but it is displayed as "NaN"

- libs/generic-view/ui/src/lib/interactive/toast/toast.tsx
JIRA Reference: [CP-3377]
-
[CP-3377]: https://appnroll.atlassian.net/browse/CP-3377?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
>  [CP-3377] Blinking tooltip after files deletion

- libs/generic-view/ui/src/lib/interactive/toast/toast.tsx
JIRA Reference: [[CP-3377]
-
[CP-3377]: https://appnroll.atlassian.net/browse/CP-3377?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
>  [CP-3377] Blinking tooltip after files deletion (#2302) - cherry-pick to 3.0.0

- libs/generic-view/ui/src/lib/buttons/button-base/use-upload-files-button-action.ts
- libs/generic-view/ui/src/lib/generated/mc-file-manager/mc-file-manager-data.ts
JIRA Reference: [CP-3412]
-
[CP-3412]: https://appnroll.atlassian.net/browse/CP-3412?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3412] cherry-pick to develop

- libs/e2e-mock/responses/src/lib/default-responses.ts
- libs/e2e-mock/responses/src/lib/feature-configuration-responses.ts
- libs/e2e-mock/responses/src/lib/overview-responses.ts
> [CP-XXX] E2E mock responses updated

- libs/generic-view/ui/src/lib/predefined/backup/backup-create.tsx
JIRA Reference: [CP-3444]
-
[CP-3444]: https://appnroll.atlassian.net/browse/CP-3444?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3444] RC: Overview: Create backup modal is not in proper size

- apps/mudita-center-e2e/src/specs/overview/e2e-mock-lock-sample.e2e.ts
- apps/mudita-center-e2e/src/specs/overview/e2e-mock-match.e2e.ts
- libs/device/feature/src/lib/api-config/dev-api-config.adapter.ts
- libs/device/feature/src/lib/menu/dev-menu.adapter.ts
- libs/e2e-mock/responses/src/lib/default-responses.ts
- libs/generic-view/ui/src/lib/buttons/button-base/use-upload-files-button-action.ts
- libs/generic-view/ui/src/lib/generated/index.ts
> [CP-XXX-api-update] Feature keys updated

- libs/generic-view/ui/src/lib/generated/mc-contacts-view/delete-modal.ts
JIRA Reference: [CP-3461]
-
[CP-3461]: https://appnroll.atlassian.net/browse/CP-3461?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3461] "Delete contact" vs "Delete contact?

- libs/core/__deprecated__/renderer/constants/menu-elements.ts
- libs/device/feature/src/lib/api-config/dev-api-config.adapter.ts
- libs/device/feature/src/lib/menu/dev-menu.adapter.ts
- libs/device/models/src/lib/menu/menu-config.ts
- libs/generic-view/feature/src/lib/use-dev-console.ts
- libs/generic-view/store/src/index.ts
- libs/generic-view/utils/src/lib/generate-menu/generate-menu.ts
JIRA Reference: [CP-3440]
-
[CP-3440]: https://appnroll.atlassian.net/browse/CP-3440?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3440] Implement changes for menu (center) for SD Card

- libs/generic-view/utils/src/lib/data-sort/data-sort.helpers.ts
- libs/generic-view/utils/src/lib/data-sort/data-sort.test.ts
JIRA Reference: [CP-3462]
-
[CP-3462]: https://appnroll.atlassian.net/browse/CP-3462?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3462] File manager: trim spaces at the begining and the end of a file name

- libs/core/contact-support/actions/send-ticket.action.ts
JIRA Reference: [CP-3472]
-
[CP-3472]: https://appnroll.atlassian.net/browse/CP-3472?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3472] RC6: Contact Support for Pure and Harmony does not work

- libs/generic-view/ui/src/lib/typography/typography.tsx
JIRA Reference: [CP-3474]
-
[CP-3474]: https://appnroll.atlassian.net/browse/CP-3474?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3474] add data-testids for typography

- libs/generic-view/store/src/lib/features/get-generic-config.actions.ts
- libs/generic-view/store/src/lib/features/transform-data-components.ts
- libs/generic-view/store/src/lib/features/transform-generic-components.ts
- libs/generic-view/store/src/lib/views/reducer.ts
- libs/generic-view/ui/src/lib/generated/index.ts
- libs/generic-view/ui/src/lib/generated/mc-file-manager/helpers.ts
- libs/generic-view/ui/src/lib/generated/mc-file-manager/mc-file-manager-data.ts
- libs/generic-view/ui/src/lib/generated/mc-file-manager/mc-file-manager-view.ts
- libs/generic-view/ui/src/lib/generated/mc-file-manager/storage-page.ts
- libs/generic-view/utils/src/lib/models/api-views.types.ts
JIRA Reference: [CP-3362]
-
[CP-3362]: https://appnroll.atlassian.net/browse/CP-3362?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3362] Added displaying files from SD card

- libs/device/models/src/lib/feature/data-provider-config.ts
- libs/generic-view/feature/src/lib/setup-component/with-data.tsx
- libs/generic-view/models/src/lib/common-validators.ts
- libs/generic-view/ui/src/lib/buttons/button-base/use-upload-files-button-action.ts
- libs/generic-view/ui/src/lib/generated/mc-file-manager/file-upload-button.ts
- libs/generic-view/ui/src/lib/generated/mc-file-manager/mc-file-manager-data.ts
- libs/generic-view/ui/src/lib/shared/validate-selected-files.ts
- libs/generic-view/utils/src/lib/are-all-files-duplicated.helper.test.ts
- libs/generic-view/utils/src/lib/are-all-files-duplicated.helper.ts
- libs/generic-view/utils/src/lib/forms-provider/forms-provider.tsx
JIRA Reference: [CP-3363]
-
[CP-3363]: https://appnroll.atlassian.net/browse/CP-3363?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3363] Fixed files uploading for SD card

- apps/mudita-center/package-lock.json
- apps/mudita-center/package.json
- libs/generic-view/ui/src/lib/interactive/toast/toast.tsx
- package-lock.json
> v3.0.0 rc.9

- libs/api-devices-testing/src/lib/data-transfer.spec.tsx
- libs/api-devices-testing/src/lib/helpers/file-transfer-data.ts
- libs/api-devices-testing/src/lib/helpers/protocol-validator.ts
- libs/api-devices-testing/src/lib/restore.spec.tsx
JIRA Reference: [CP-3476]
-
[CP-3476]: https://appnroll.atlassian.net/browse/CP-3476?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3476] api testing import contacts responses

- libs/e2e-test-ids/src/e2e-test-ids.ts
- libs/generic-view/ui/src/lib/interactive/form/input/search-input.tsx
- libs/generic-view/ui/src/lib/interactive/form/input/search-results.tsx
JIRA Reference: [CP-3503]
-
[CP-3503]: https://appnroll.atlassian.net/browse/CP-3503?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3503] Data test ids for search contacts

- libs/generic-view/store/src/lib/backup/actions.ts
- libs/generic-view/store/src/lib/backup/reducer.ts
- libs/generic-view/store/src/lib/backup/restore-backup.action.ts
- libs/generic-view/store/src/lib/selectors/backup-restore.ts
JIRA Reference: [CP-3376]
-
[CP-3376]: https://appnroll.atlassian.net/browse/CP-3376?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3376] Improved backup restore progress

- libs/device-manager/feature/src/hooks/use-device-manager-detached.ts
- libs/device/models/src/lib/backup/backup.ts
- libs/generic-view/store/src/lib/backup/actions.ts
- libs/generic-view/store/src/lib/backup/create-backup.action.ts
- libs/generic-view/store/src/lib/backup/reducer.ts
- libs/generic-view/store/src/lib/backup/restore-backup.action.ts
- libs/generic-view/store/src/lib/selectors/backup-progress.ts
- libs/generic-view/store/src/lib/selectors/backup-restore.ts
JIRA Reference: [CP-3376]
-
[CP-3376]: https://appnroll.atlassian.net/browse/CP-3376?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3376] Improved backup create progress

- libs/generic-view/ui/src/lib/predefined/import-contacts/import-contacts-list.tsx
- libs/generic-view/ui/src/lib/predefined/import-contacts/import-contacts.tsx
JIRA Reference: [CP-3500]
⚠️ I couldn't use `Table` component as it's designed for entities and contacts at this point are not entities yet.
⚠️ I couldn't use standard virtualization tools (which gives even better performance) as this lead to unexpected behavior regarding tooltip.
[CP-3500]: https://appnroll.atlassian.net/browse/CP-3500?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3500] Improved contacts import list scrolling experience

- apps/mudita-center/resources/license_en.txt
JIRA Reference: [CP-3506]
-
[CP-3506]: https://appnroll.atlassian.net/browse/CP-3506?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3506] Update the text in the Terms of Use modal

- apps/mudita-center/resources/license_en.txt
Reverts mudita/mudita-center#2356
> Revert "[CP-3506] Update the text in the Terms of Use modal"

- apps/mudita-center-e2e/src/specs/overview/kompakt-contacts-search.ts
JIRA Reference: [CP-3533]
- fix typo in CP-3175
[CP-3533]: https://appnroll.atlassian.net/browse/CP-3533?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-3533 - fixc 3175 typo line 202

- apps/mudita-center/resources/license_en.txt
JIRA Reference: [CP-3514]
-
[CP-3514]: https://appnroll.atlassian.net/browse/CP-3514?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3514] Terms of Service and Privacy Policy Update

- libs/core/__deprecated__/renderer/constants/external-urls.ts
- libs/core/settings/components/privacy-policy/privacy-policy-ui.component.tsx
- libs/core/settings/components/terms-of-service/terms-of-service-ui.component.tsx
- libs/core/settings/components/terms-of-service/terms-of-service-ui.test.tsx
JIRA Reference: [CP-3515] [CP-3516]
-
[CP-3515]: https://appnroll.atlassian.net/browse/CP-3515?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CP-3516]: https://appnroll.atlassian.net/browse/CP-3516?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3515] Update to Terms of Service and Privacy Policy

- apps/mudita-center-e2e/src/page-objects/modal-license.page.ts
- apps/mudita-center-e2e/src/page-objects/modal-privacy-policy.page.ts
- apps/mudita-center-e2e/src/page-objects/modal-terms-of-service.page.ts
- apps/mudita-center-e2e/src/specs/settings/license.e2e.ts
- apps/mudita-center-e2e/src/specs/settings/privacy-policy.e2e.ts
- apps/mudita-center-e2e/src/specs/settings/terms-of-service.e2e.ts
- libs/core/settings/components/license/license-ui.component.tsx
- libs/core/settings/components/license/license-ui.test.tsx
- libs/e2e-mock/server/src/lib/server.tsx
JIRA Reference: [CP-3520]
-
[CP-3520]: https://appnroll.atlassian.net/browse/CP-3520?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3520] Update license in settings

- libs/generic-view/ui/src/lib/generated/mc-file-manager/mc-file-manager-data.ts
- libs/generic-view/ui/src/lib/generated/mc-file-manager/mc-file-manager-view.ts
JIRA Reference: [CP-3521]
-
[CP-3521]: https://appnroll.atlassian.net/browse/CP-3521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3521] Removed Music Files - 3.0.0

- .github/workflows/e2e-mock-development.yml
JIRA Reference: [CP-3568]
-
[CP-3568]: https://appnroll.atlassian.net/browse/CP-3568?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3568] Add E2E mock test execution on the develop

- .github/workflows/e2e-mock-development.yml
- .github/workflows/e2e-mock-pre-production.yml
- .github/workflows/e2e-mock-production.yml
- .github/workflows/e2e-pre-production.yml
- .github/workflows/e2e-production.yml
JIRA Reference: [CP-3567]
-
[CP-3567]: https://appnroll.atlassian.net/browse/CP-3567?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3567] Fix E2E test execution on the main environment

- .github/workflows/e2e-development.yml
- .github/workflows/e2e-feature-branch.yml
- .github/workflows/e2e-mock-development.yml
- .github/workflows/e2e-mock-feature-branch.yml
- .github/workflows/e2e-mock-pre-production.yml
- .github/workflows/e2e-mock-production.yml
- .github/workflows/e2e-pre-production.yml
- .github/workflows/e2e-production.yml
- .github/workflows/nexus-development.yml
- .github/workflows/nexus-feature-branch.yml
- .github/workflows/nexus-mass-update.yml
- .github/workflows/nexus-mock-development.yml
- .github/workflows/nexus-mock-pre-production.yml
- .github/workflows/nexus-mock-production.yml
- .github/workflows/nexus-pre-production-latest.yml
- .github/workflows/nexus-pre-production.yml
- .github/workflows/nexus-production-with-os-rc.yml
- .github/workflows/nexus-production.yml
- apps/mudita-center-e2e/src/specs/help/help-section-check.e2e.ts
- apps/mudita-center/package-lock.json
- apps/mudita-center/package.json
- package-lock.json
JIRA Reference: [CP-3567]
[CP-3567]: https://appnroll.atlassian.net/browse/CP-3567?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3567] Fix E2E test execution on the main environment - final version

- apps/mudita-center-e2e/src/specs/overview/kompakt-backup-error-cancel.ts
- libs/core/contact-support/actions/send-ticket.action.test.ts
- libs/core/contact-support/reducers/contact-support.reducer.test.ts
- libs/core/contacts/actions/delete-contacts.action.test.ts
- libs/core/contacts/actions/import-contact.action.test.ts
- libs/generic-view/store/src/lib/features/get-generic-data.actions.ts
- libs/generic-view/ui/src/lib/buttons/button-base/use-button-action.test.ts
>  [CP-XXX] Checks fixed

- apps/mudita-center-e2e/package.json
- apps/mudita-center-e2e/scripts/run-wdio.ts
- apps/mudita-center-e2e/wdio.conf.ts
- package-lock.json
- package.json
JIRA Reference: [CP-3587]
-
[CP-3587]: https://appnroll.atlassian.net/browse/CP-3587?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3587] WDIO port fix

- apps/mudita-center-e2e/src/helpers/entity-fixtures.ts
- apps/mudita-center-e2e/src/specs/overview/e2e-mock-lock-sample.e2e.ts
- libs/e2e-mock/responses/src/lib/default-responses.ts
- libs/e2e-mock/responses/src/lib/entities-configuration-responses.ts
- libs/e2e-mock/responses/src/lib/feature-configuration-responses.ts
- libs/e2e-mock/server/src/lib/mock-device/mock-device.ts
- libs/generic-view/feature/src/lib/use-dev-views/views/file-manager-view.ts
- libs/generic-view/ui/src/lib/generated/mc-file-manager/mc-file-manager-data.ts
- libs/generic-view/ui/src/lib/generated/mc-file-manager/mc-file-manager-view.ts
JIRA Reference: [CP-3581]
-
[CP-3581]: https://appnroll.atlassian.net/browse/CP-3581?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
>  [CP-3581] Files manager - mocks for file manager features

- libs/app-mtp/src/lib/node-mtp/mtp-packet-definitions.ts
- libs/app-mtp/src/lib/node-mtp/node-mtp-device.ts
- libs/app-mtp/src/lib/node-mtp/node-mtp.ts
JIRA Reference: [CP-3566]
-
[CP-3566]: https://appnroll.atlassian.net/browse/CP-3566?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3566] Increase MTP transfer speed

- .github/workflows/e2e-development.yml
- .github/workflows/e2e-feature-branch.yml
- .github/workflows/e2e-mock-development.yml
- .github/workflows/e2e-mock-feature-branch.yml
- .github/workflows/e2e-mock-pre-production.yml
- .github/workflows/e2e-mock-production.yml
- .github/workflows/e2e-pre-production.yml
- .github/workflows/e2e-production.yml
- .github/workflows/nexus-development.yml
- .github/workflows/nexus-feature-branch.yml
- .github/workflows/nexus-mass-update.yml
- .github/workflows/nexus-mock-development.yml
- .github/workflows/nexus-mock-pre-production.yml
- .github/workflows/nexus-mock-production.yml
- .github/workflows/nexus-pre-production-latest.yml
- .github/workflows/nexus-pre-production.yml
- .github/workflows/nexus-production-with-os-rc.yml
- .github/workflows/nexus-production.yml
JIRA Reference: [CP-3587]
-
[CP-3587]: https://appnroll.atlassian.net/browse/CP-3587?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3587] Workflow improvements

- libs/app-theme/models/src/lib/components/button.ts
- libs/app-theme/ui/src/lib/button/button-text.styles.tsx
- libs/app-theme/ui/src/lib/button/button.stories.tsx
- libs/app-theme/ui/src/lib/icon/icon.tsx
> [CP-XXX] Improved Button component styling

- libs/generic-view/store/src/lib/file-transfer/send-files.action.ts
JIRA Reference: [CP-3529]
-
[CP-3529]: https://appnroll.atlassian.net/browse/CP-3529?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3529] Switched to MTP before sending files

- libs/generic-view/ui/src/lib/icon/get-icon.helper.tsx
- libs/generic-view/ui/src/lib/icon/svg/information-2.svg
- libs/generic-view/ui/src/lib/predefined/files-manager-upload/files-manager-upload-progress-warning.tsx
- libs/generic-view/utils/src/lib/models/icons.types.ts
JIRA Reference: [CP-3604]
[CP-3604]: https://appnroll.atlassian.net/browse/CP-3604?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3604] Update the copy for the MTP interrupted process popup and add list of the apps

- libs/app-mtp/src/lib/node-mtp/node-mtp-device.ts
- libs/app-mtp/src/lib/node-mtp/node-mtp.ts
JIRA Reference: [CP-3545]
-
[CP-3545]: https://appnroll.atlassian.net/browse/CP-3545?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3545] Handle Specific Errors During Upload File Processing (Duplicate Name)

- libs/generic-view/store/src/lib/action-names.ts
- libs/generic-view/store/src/lib/file-transfer/send-files.action.ts
- libs/generic-view/store/src/lib/hooks/use-outbox.ts
- libs/generic-view/store/src/lib/outbox/get-outbox-data.action.ts
- libs/generic-view/store/src/lib/selectors/select-last-outbox-data.ts
- libs/generic-view/store/src/lib/views/actions.ts
- libs/generic-view/store/src/lib/views/reducer.ts
JIRA Reference: [CP-3615]
-
[CP-3615]: https://appnroll.atlassian.net/browse/CP-3615?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3615] adding files in the background is delayed, they are not shown while files are progressing

- libs/generic-view/store/src/lib/file-transfer/pre-send-files-cleanup.ts
- libs/generic-view/store/src/lib/file-transfer/send-files.action.ts
JIRA Reference: [CP-3651]
-
[CP-3651]: https://appnroll.atlassian.net/browse/CP-3651?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3651] Ensure reliable MTP upload by resolving system-level conflicts on Linux

- libs/api-devices-testing/src/lib/entities.spec.tsx
- libs/device/feature/src/lib/api-entities/api-entities.service.ts
JIRA Reference: [CP-3628]
-
[CP-3628]: https://appnroll.atlassian.net/browse/CP-3628?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3628] Delete entities test cases for contacts

- package.json
- scripts/manage-test-files/clear-test-files.ts
- scripts/manage-test-files/generate-and-push-test-files.ts
- scripts/manage-test-files/generate-max-storage-load.ts
- scripts/manage-test-files/get-remote-paths.ts
- scripts/manage-test-files/helpers.ts
- scripts/manage-test-files/manage-test-files.const.ts
- scripts/manage-test-files/parse-target-arg.ts
> [CP-3547] Script added to generate max storage load test files

- apps/mudita-center-e2e/src/helpers/mock-backup.ts
- apps/mudita-center-e2e/src/specs/overview/kompakt-backup-error-cancel.ts
- apps/mudita-center-e2e/src/specs/overview/kompakt-backup-error-disconnect.ts
- libs/e2e-mock/responses/src/lib/default-responses.ts
- libs/e2e-mock/server/src/lib/mock-descriptor/mock-descriptor-validators.ts
- libs/e2e-mock/server/src/lib/mock-descriptor/mock-descriptor.test.ts
- libs/e2e-mock/server/src/lib/mock-descriptor/mock-descriptor.ts
- libs/e2e-mock/server/src/lib/mock-device/mock-device.ts
- libs/e2e-mock/server/src/lib/server.tsx
> [CP-2977] delay to mock responses

- apps/mudita-center-e2e/src/specs/overview/kompakt-manage-files-overall-check.ts
- libs/e2e-mock/responses/src/lib/default-responses.ts
JIRA Reference: [CP-3682]
-
[CP-3682]: https://appnroll.atlassian.net/browse/CP-3682?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3682] test files for mock responses

- libs/devices/common/models/src/index.ts
- libs/devices/common/models/src/lib/device-metadata.ts
- libs/devices/common/ui/src/index.ts
- libs/devices/common/ui/src/lib/devices-drawer/devices-drawer-card.tsx
- libs/devices/common/ui/src/lib/devices-drawer/devices-drawer.stories.tsx
- libs/devices/common/ui/src/lib/devices-drawer/devices-drawer.tsx
- libs/devices/common/ui/src/lib/devices-indicator/devices-indicator.tsx
- libs/devices/common/ui/src/lib/devices-selector/devices-selector-card.tsx
- libs/devices/common/ui/src/lib/devices-selector/devices-selector.stories.tsx
- libs/devices/common/ui/src/lib/devices-selector/devices-selector.tsx
> [CP-XXX] Improved UI components for devices drawer and selecting page

- apps/mudita-center/templates/index.html
JIRA Reference: [CP-3494]
-
[CP-3494]: https://appnroll.atlassian.net/browse/CP-3494?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3494] Updated app title

- libs/app-routing/feature/src/index.ts
- libs/app-routing/feature/src/lib/fullscreen-modal-layout/fullscreen-modal-layout.tsx
JIRA Reference: [CP-3622]
-
[CP-3622]: https://appnroll.atlassian.net/browse/CP-3622?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3622] Added new layout

- libs/app-serialport/main/src/lib/init-serialport.ts
- libs/app-settings/main/src/lib/init-app-settings.ts
- libs/app-sql/main/src/lib/init-sql.ts
- libs/app-utils/main/src/lib/app-actions/init-app-actions.ts
- libs/app-utils/main/src/lib/app-updater/init-app-updater.ts
- libs/news/main/src/lib/init-news.ts
> [CP-XXX] Variable types simplified by dropping null and casts

- libs/generic-view/ui/src/lib/generated/mc-file-manager/file-list.ts
JIRA Reference: [CP-3699]
-
[CP-3699]: https://appnroll.atlassian.net/browse/CP-3699?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3699] Updated Apps delete button text

- apps/mudita-center/package-lock.json
- apps/mudita-center/package.json
- libs/generic-view/ui/src/lib/generated/mc-file-manager/file-list.ts
- package-lock.json
> v3.1.0 rc.2

- apps/mudita-center/package-lock.json
- apps/mudita-center/package.json
- apps/mudita-center/templates/index.html
- libs/generic-view/ui/src/lib/generated/mc-file-manager/file-list.ts
- package-lock.json
> Release v3.1.0 - to stage

- apps/app/package.json
> [CP-XXX] e2e fixed

- libs/app-utils/main/src/lib/app-http/app-http.preload.ts
- libs/app-utils/main/src/lib/app-http/app-http.service.ts
- libs/app-utils/main/src/lib/app-http/init-app-http.ts
- libs/app-utils/models/src/index.ts
- libs/app-utils/models/src/lib/app-error.ts
- libs/app-utils/models/src/lib/app-http.ts
- libs/app-utils/models/src/lib/app-result.ts
- libs/app-utils/renderer/src/lib/analytics/analytics.ts
> [CP-3636] Implement AppResult for standardized response wrapping

- libs/app-utils/main/src/lib/app-http/app-http.service.ts
- libs/app-utils/models/src/lib/app-http.ts
- package-lock.json
- package.json
> [CP-3636] Implement multipart/form-data support in AppHttpService

- apps/app/src/main/init-app-libs.ts
- apps/app/src/preload/api.ts
- libs/app-utils/main/src/index.ts
- libs/app-utils/main/src/lib/app-file-system/app-file-system.preload.ts
- libs/app-utils/main/src/lib/app-file-system/app-file-system.service.ts
- libs/app-utils/main/src/lib/app-file-system/init-app-file-system.ts
- libs/app-utils/main/src/lib/app-http/app-http.service.ts
- libs/app-utils/models/src/index.ts
- libs/app-utils/models/src/lib/app-error.ts
- libs/app-utils/models/src/lib/app-file-system-ipc-events.ts
- libs/app-utils/models/src/lib/app-file-system.ts
- libs/app-utils/models/src/lib/app-result.ts
- libs/app-utils/renderer/src/lib/app-file-system.ts
> [CP-3636] AppFileSystemService implemented

- libs/app-theme/ui/src/lib/form/text-input/text-input-textarea.tsx
- libs/app-theme/ui/src/lib/form/text-input/text-input.stories.tsx
- libs/app-theme/ui/src/lib/form/text-input/text-input.tsx
> [CP-3636] `TextInputTextarea` implemented

- libs/app-utils/common/.babelrc
- libs/app-utils/common/README.md
- libs/app-utils/common/eslint.config.cjs
- libs/app-utils/common/jest.config.ts
- libs/app-utils/common/package.json
- libs/app-utils/common/project.json
- libs/app-utils/common/src/delay-until-at-least.ts
- libs/app-utils/common/src/delay.ts
- libs/app-utils/common/src/index.ts
- libs/app-utils/common/tsconfig.json
- libs/app-utils/common/tsconfig.lib.json
- libs/app-utils/common/tsconfig.spec.json
- libs/app-utils/common/vite.config.ts
- libs/app-utils/renderer/src/lib/analytics/analytics-cache.service.ts
- tsconfig.base.json
> [CP-3636] Added empty libs for app-utils/common (1) 

- libs/app-utils/main/src/lib/app-http/app-http.service.ts
- libs/app-utils/models/src/lib/app-http.ts
- libs/contact-support/feature/src/lib/use-contact-support.ts
> [CP-3636] Handle Sending data to support

- apps/app-e2e/src/helpers/contact-support.helper.ts
- apps/app-e2e/src/helpers/modal.ts
- apps/app-e2e/src/page-objects/app-init.page.ts
- apps/app-e2e/src/page-objects/contact-support.page.ts
- apps/app-e2e/src/page-objects/help.page.ts
- apps/app-e2e/src/page-objects/modal-page.ts
- apps/app-e2e/src/specs/contact-support-base.e2e.ts
- apps/app-e2e/src/specs/contact-support-failure-path.e2e.ts
- apps/app-e2e/src/specs/contact-support-happy-path.e2e.ts
- libs/app-localize/utils/src/index.ts
- libs/app-theme/models/src/lib/components/text-input.ts
- libs/app-theme/ui/src/lib/form/text-input/text-input.tsx
- libs/contact-support/models/src/lib/contact-support-testids.ts
- libs/contact-support/ui/src/lib/contact-support-error-modal.tsx
- libs/contact-support/ui/src/lib/contact-support-file-list.tsx
- libs/contact-support/ui/src/lib/contact-support-form-modal.tsx
- libs/contact-support/ui/src/lib/contact-support-input-label.tsx
- libs/contact-support/ui/src/lib/contact-support-sending-modal.tsx
- libs/contact-support/ui/src/lib/contact-support-success-modal.tsx
- libs/help/ui/src/help/help-footer.component.tsx
> [CP-3636] E2E tests for Contact Support base path were added

- libs/app-init/feature/src/lib/check-init-requirements.tsx
- libs/app-updater/feature/src/lib/app-update-flow.tsx
- libs/app-updater/feature/src/lib/store/app-updater.reducer.ts
- libs/app-updater/main/src/lib/app-updater.service.ts
- libs/app-updater/main/src/lib/init-app-updater.ts
- libs/app-updater/ui/src/index.ts
- libs/app-updater/ui/src/lib/app-update.stories.tsx
- libs/app-updater/ui/src/lib/update-checking-modal.tsx
JIRA Reference: [CP-3597]
-
[CP-3597]: https://appnroll.atlassian.net/browse/CP-3597?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3597] Review fixes (12)

- libs/app-routing/routes/src/lib/app-routes.tsx
- libs/devices/common/feature/src/lib/devices-initializer/devices-initializer.tsx
- libs/devices/common/ui/src/lib/devices-drawer/devices-drawer.tsx
- libs/devices/common/ui/src/lib/devices-indicator/devices-indicator.tsx
> [CP-XXX] Fixed a UI glitch when devices are connected

- libs/app-mtp/src/lib/dotnet-mtp/dotnet-mtp.ts
- libs/app-mtp/src/lib/node-mtp/node-mtp.ts
- libs/generic-view/store/src/lib/file-transfer/reducer.ts
- libs/generic-view/store/src/lib/file-transfer/send-files-transfer-analysis.action.ts
- libs/generic-view/store/src/lib/file-transfer/send-files.action.ts
- libs/generic-view/store/src/lib/selectors/file-transfer-sending.ts
- libs/generic-view/ui/src/lib/predefined/files-manager-transfer-files/files-manager-transfer-finished.tsx
JIRA Reference: [CP-3831]
-
[CP-3831]: https://appnroll.atlassian.net/browse/CP-3831?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3831] Fixed a bug that caused files to continue exporting after cancelation

- apps/app-e2e/src/consts/mock-based-spec-relative-paths.ts
- apps/app-e2e/src/helpers/contact-support.helper.ts
- apps/app-e2e/src/helpers/help-center.helper.ts
- apps/app-e2e/src/page-objects/help-article.page.ts
- apps/app-e2e/src/page-objects/help.page.ts
- apps/app-e2e/src/specs/help-center-feedback-flow.e2e.ts
- apps/app-e2e/src/specs/help-center-home-screen.e2e.ts
- apps/app-e2e/src/specs/help-center-link-navigation-flow.e2e.ts
- apps/app-e2e/src/specs/help-center-offline-mode.e2e.ts
- apps/app-e2e/src/specs/help-center-search-functionality.e2e.ts
- apps/app/src/main/init-app-libs.ts
- libs/app-theme/ui/src/lib/form/text-input/text-input-search.tsx
- libs/app-theme/ui/src/lib/icon/icon.tsx
- libs/app-utils/main/src/lib/json-store/init-json-store.ts
- libs/app-utils/models/src/lib/help-ipc-events.ts
- libs/help/feature/src/lib/help-page/help.tsx
- libs/help/main/src/index.ts
- libs/help/main/src/lib/app-help.service.ts
- libs/help/main/src/lib/init-app-help.ts
- libs/help/models/src/lib/help-data.ts
- libs/help/models/src/lib/help-paths.ts
- libs/help/routes/src/lib/router.tsx
- libs/help/ui/src/article/article-content.component.tsx
- libs/help/ui/src/article/article-header.component.tsx
- libs/help/ui/src/help/articles-list.component.tsx
- libs/help/ui/src/help/category-tabs.components.tsx
- libs/help/ui/src/help/search.component.tsx
JIRA Reference: [CP-3828]
e2e + clear feature fixed
[CP-3828]: https://appnroll.atlassian.net/browse/CP-3828?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3828] [App refactor] Improve UI/UX for help section -> E2E

- .env.example
- .github/workflows/e2e-development.yml
- .github/workflows/e2e-feature-branch.yml
- .github/workflows/nexus-development.yml
- .github/workflows/nexus-feature-branch.yml
- libs/app-updater/main/src/lib/app-updater.service.ts
- scripts/download-fonts.ts
JIRA Reference: [CP-3839]
-
[CP-3839]: https://appnroll.atlassian.net/browse/CP-3839?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3839] Security update: GitHub token split - develop-next

- libs/device/models/src/lib/feature/data-provider-config.ts
- libs/generic-view/ui/src/lib/generated/mc-file-manager/file-list.ts
- libs/generic-view/utils/src/lib/data-sort/data-sort.helpers.ts
- libs/generic-view/utils/src/lib/data-sort/data-sort.ts
JIRA Reference: [CP-3840]
-
[CP-3840]: https://appnroll.atlassian.net/browse/CP-3840?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3840] Changed sort order in files manager

- libs/core/device-file-system/services/device-file-system.service.ts
JIRA Reference: [CP-3841]
-
[CP-3841]: https://appnroll.atlassian.net/browse/CP-3841?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3841] - Data migration freeze

- libs/generic-view/ui/src/lib/predefined/file-preview/file-preview.tsx
JIRA Reference: [CP-3863]
-
[CP-3863]: https://appnroll.atlassian.net/browse/CP-3863?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3863] Update entitiesIds on items change

- apps/mudita-center/package.json
- libs/generic-view/ui/src/lib/predefined/backup-restore/backup-restore-select.tsx
JIRA Reference: [CP-3889]
-
[CP-3889]: https://appnroll.atlassian.net/browse/CP-3889?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3889] cant restore single backup

- libs/devices/harmony/routes/src/lib/screens/overview/harmony-overview-os-section.tsx
- libs/devices/harmony/routes/src/lib/screens/overview/harmony-overview.screen.tsx
JIRA Reference: [CP-3670]
-
[CP-3670]: https://appnroll.atlassian.net/browse/CP-3670?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3670] Implemented Harmony OS update flow (13)

- apps/app/package.json
JIRA Reference: [CP-3670]
-
[CP-3670]: https://appnroll.atlassian.net/browse/CP-3670?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3670] Changed name of app package

- libs/app-localize/utils/src/lib/locales/en-US.json
- libs/devices/common/feature/src/lib/devices-initializer/use-harmony-initializer.ts
- libs/devices/harmony/feature/src/lib/hooks/use-harmony-os-update-info.query.ts
- libs/devices/harmony/routes/src/lib/screens/overview/harmony-overview-os-section.messages.ts
- libs/devices/harmony/routes/src/lib/screens/overview/harmony-overview-os-section.tsx
- libs/devices/harmony/ui/src/lib/os-update/harmony-update-available-modal.tsx
- libs/devices/harmony/ui/src/lib/os-update/harmony-update-downloaded-modal.tsx
- libs/devices/harmony/ui/src/lib/os-update/harmony-update-error-modal.tsx
JIRA Reference: [CP-3679]
-
[CP-3679]: https://appnroll.atlassian.net/browse/CP-3679?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3679][App Refactor] [Harmony] OS update - force

- libs/app-utils/main/src/lib/app-file-system/app-file-system.preload.ts
- libs/app-utils/main/src/lib/app-file-system/app-file-system.service.ts
- libs/app-utils/main/src/lib/app-file-system/init-app-file-system.ts
- libs/app-utils/models/src/lib/app-file-system-ipc-events.ts
- libs/app-utils/models/src/lib/app-file-system.ts
- libs/app-utils/renderer/src/lib/app-file-system.ts
- package-lock.json
- package.json
JIRA Reference: [CP-3672]
-
[CP-3672]: https://appnroll.atlassian.net/browse/CP-3672?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3672] AppFileSystem API extended with readFile, writeFileChunk, and extract
