- packages/app/src/messages/components/messages/messages-test-ids.enum.ts
- packages/app/src/messages/components/messages/messages.component.tsx
- packages/app/src/messages/components/messages/messages.test.tsx
- packages/app/src/messages/components/thread-list.component.tsx
- packages/app/src/renderer/locales/default/en-US.json
Jira: [CP-827]
EmptyState component added to Messages Page when threads length size is equal 0
[CP-827]: https://appnroll.atlassian.net/browse/CP-827?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-827] The no result state isn't display when user doesn't have messages

- packages/app/src/device/actions/disconnect-device.action.test.ts
- packages/app/src/device/actions/disconnect-device.action.ts
- packages/app/src/overview/components/backup-device-flow/backup-device-flow.component.tsx
- packages/app/src/overview/components/overview/overview.component.tsx
- packages/app/src/overview/components/restore-device-flow/restore-device-flow.component.tsx
Jira: [CP-801]
Rendering Screen Component fixed by moving outside from the Overview Component. This PR handles two bugs:
- [CP-801 - "Go to support" after failed OS update doesn't work](https://appnroll.atlassian.net/browse/CP-801)
- [CP-821 - Restore confirmation window disappears automatically](https://appnroll.atlassian.net/browse/CP-821)
[CP-801]: https://appnroll.atlassian.net/browse/CP-801?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CP-801]: https://appnroll.atlassian.net/browse/CP-801?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CP-821]: https://appnroll.atlassian.net/browse/CP-821?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1c …
> [CP-801][CP-821] Rendering Screen Component fixed by move outside from the Overview

- packages/app/src/messages/actions/base.action.test.ts
- packages/app/src/messages/actions/base.action.ts
- packages/app/src/messages/actions/load-threads.action.test.ts
- packages/app/src/messages/actions/load-threads.action.ts
- packages/app/src/messages/constants/event.enum.ts
- packages/app/src/messages/reducers/messages.reducer.test.ts
- packages/app/src/messages/reducers/messages.reducer.ts
- packages/app/src/renderer/register-app-context-menu.ts
Jira: [CP-827]
`LoadThreads` action extended by `clearAllThreads` action to handle empty state in UI.
[CP-827]: https://appnroll.atlassian.net/browse/CP-827?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-827] The no result state isn't display when user doesn't have messages {2}

- packages/app/src/contacts/components/contact-list/contact-list.component.tsx
Jira: [CP-708]
InitialsAvatar styled fixed in active row state for contacts
<details>
**Before:**
after saving the edited contact, the problem of the avatar color of the active contact returns (It has the wrong color)
</details>
[CP-708]: https://appnroll.atlassian.net/browse/CP-708?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-708] Fixes after the design review 

- packages/app/src/crash-dump/actions/send-crash-dump-data.action.ts
Jira: [CP-899]
- `removeFile` dispatching modified to handle passed property dynamically https://github.com/mudita/mudita-center/commit/9a18ab492eb6acf9fc47fec8bb3c3fe56aa228d5
[CP-899]: https://appnroll.atlassian.net/browse/CP-899?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-899] Crash Dump Modal is displaying even when crash dumps were sent

- packages/app/src/main/utils/logger.ts
Jira: [CP-940]
Logs were limited to 3 files and 1MB per file and this limit was reached after less than hour, then it crashed. I increase files and size limit. 
<details>
</details>
[CP-940]: https://appnroll.atlassian.net/browse/CP-940?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-940] Mudita Center shut down after a certain time of inactivity

- packages/app/src/messages/components/messages-panel.component.tsx
- packages/app/src/renderer/locales/default/en-US.json
Jira: [CP-1312]
Fix after tests form CP-1122.
Fix text in conversations Selection Manager
<details>
</details>
[CP-1312]: https://appnroll.atlassian.net/browse/CP-1312?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1312] Incorrect string for marked Conversations counter in Selection Manager

- packages/app/src/messages/actions/base.action.test.ts
- packages/app/src/messages/actions/base.action.ts
- packages/app/src/messages/actions/toggle-threads-read-status.action.ts
- packages/app/src/messages/components/messages/messages.component.tsx
- packages/app/src/messages/components/thread-details-messages.component.tsx
- packages/app/src/messages/components/thread-list.component.tsx
- packages/app/src/messages/components/thread-row.component.tsx
- packages/app/src/messages/constants/errors.enum.ts
- packages/app/src/messages/constants/event.enum.ts
- packages/app/src/messages/controllers/thread.controller.ts
- packages/app/src/messages/errors/mark-threads-read-status.error.ts
- packages/app/src/messages/errors/toggle-threads-read-status.error.ts
- packages/app/src/messages/messages.container.tsx
- packages/app/src/messages/reducers/messages-reducer.helpers.test.ts
- packages/app/src/messages/reducers/messages-reducer.helpers.ts
- packages/app/src/messages/reducers/messages.interface.ts
- packages/app/src/messages/reducers/messages.reducer.test.ts
- packages/app/src/messages/reducers/messages.reducer.ts
- packages/app/src/messages/services/thread.service.test.ts
- packages/app/src/messages/services/thread.service.ts
Jira: [CP-1141]
This PR is a part of the improvements to  👉  https://github.com/mudita/mudita-center/pull/743
- [Revert "CP-1141 set unread status on thread"](https://github.com/mudita/mudita-center/pull/753/commits/99ca6cd2d4871bc90cb8bb9a32a69420e499458b)
- handle the events emitted by `messages.observer`
- workaround to handle a "redux lag" by duplicate redux logic in both states in pending and fulfilled
[CP-1141]: https://appnroll.atlassian.net/browse/CP-1141?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1141] Fix deleting notification from the main menu after read message vol.2

- packages/app/src/templates/components/templates-select-modal/templates-select-modal.component.tsx
- packages/app/src/templates/components/templates-select-modal/templates-select-modal.styled.tsx
Jira: [CP-1440]
Fix styles for long template on attach template modal
<details>
</details>
[CP-1440]: https://appnroll.atlassian.net/browse/CP-1440?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1440] fix styles for long template on template list modal

- packages/pure/src/logger/log-decorator.ts
Jira: [CP-1557]
Log decorator returns different of type stringified JSON. This PR changes a returned type from `T` & `T[]` to `T[]`.
[CP-1557]: https://appnroll.atlassian.net/browse/CP-1557?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1557] Scrub log data for errors

- packages/app/src/contacts/components/contact-panel/contact-panel.component.tsx
- packages/app/src/contacts/components/contact-panel/contact-panel.styled.tsx
- packages/app/src/contacts/components/contact-panel/contact-panel.test.tsx
- packages/app/src/contacts/components/contacts/contacts.component.tsx
Jira: [CP-1576]
Changed design. Now there are no import and new contact buttons when selection manager is visible. 
<details>
</details>
[CP-1576]: https://appnroll.atlassian.net/browse/CP-1576?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1576] Remove contact panel buttons when selection manager is open

- packages/app/src/messages/components/thread-details-messages.component.tsx
- packages/app/src/messages/components/thread-details.styled.tsx
Jira: [CP-1620]
Scope:
* add missing gap between last message and messages input (it was visible before)
* improve a little bit scrolling experience (scrolling to last sent message, detecting when to show new message notification)
<details>
</details>
[CP-1620]: https://appnroll.atlassian.net/browse/CP-1620?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1620] improve scroll to message experience

- packages/app/src/messages/components/messages-search-results/messages-search-results.component.tsx
Jira: [CP-1621]
Fix to long query in the search result
<details>
</details>
[CP-1621]: https://appnroll.atlassian.net/browse/CP-1621?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1621] Fix to long search query

- packages/app/src/__deprecated__/backend/device-service.ts
- packages/app/src/__deprecated__/renderer/locales/default/en-US.json
- packages/app/src/core/types/request-response.interface.ts
- packages/app/src/device-file-system/commands/file-upload.command.test.ts
- packages/app/src/device-file-system/commands/file-upload.command.ts
- packages/app/src/device-file-system/constants/error.enum.ts
- packages/app/src/files-manager/components/files-manager/files-manager.component.tsx
- packages/app/src/files-manager/components/files-manager/files-manager.interface.tsx
- packages/app/src/files-manager/components/files-manager/files-manager.test.tsx
- packages/app/src/files-manager/components/upload-files-modals/upload-files-modals.component.tsx
- packages/app/src/files-manager/components/upload-files-modals/upload-files-modals.interface.ts
- packages/app/src/files-manager/components/upload-files-modals/upload-files-modals.test.tsx
- packages/app/src/files-manager/constants/errors.enum.ts
- packages/app/src/files-manager/files-manager.container.tsx
- packages/app/src/files-manager/services/file-manager.service.test.ts
- packages/app/src/files-manager/services/file-manager.service.ts
- packages/e2e/src/pure/types/device.types.ts
- packages/pure/src/device/device.types.ts
Jira: [CP-1605]
Implementing `NoSpaceLeft` error
<details>
</details>
[CP-1605]: https://appnroll.atlassian.net/browse/CP-1605?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1605] Adding `NoSpaceError` to files manager

- packages/app/src/files-manager/components/files-manager/files-manager.component.tsx
- packages/app/src/files-manager/components/files-manager/get-spaces.helper.test.ts
- packages/app/src/files-manager/components/files-manager/get-spaces.helper.ts
Jira: [CP-1634]
- Handled the case when the size on the os side is corrupted. Sometimes OS logic returns a total size higher than is it. The OS buffer logic isn't perfect and will be handled in the a new issue 👇 
- https://appnroll.atlassian.net/browse/MOS-744
- Added disabled state to upload button when free size is equal 0 (or less 😱 ) 😉 
[CP-1634]: https://appnroll.atlassian.net/browse/CP-1634?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1634][Files manager] reaching the free space limit on upload sometimes is displayed as NaN undefined

- packages/app/jest.config.js
Scope:
* code coverage now depends on static values rather than dynamic values of `jest.coverage.json`
> Update test coverage config

- packages/app/src/overview/components/overview-screens/harmony-overview/harmony-overview.component.tsx
- packages/app/src/overview/components/overview-screens/pure-overview/pure-overview.component.tsx
- packages/app/src/update/controllers/releases.controller.ts
- packages/app/src/update/services/releases.service.ts
> Workaround to fetch Harmony 1.6.0 release in dev mode

- packages/app/src/__deprecated__/renderer/components/core/button-toggler/button-toggler.component.tsx
- packages/app/src/__deprecated__/renderer/components/core/button-toggler/button-toggler.interface.tsx
- packages/app/src/__deprecated__/renderer/components/core/button-toggler/button-toggler.stories.tsx
- packages/app/src/__deprecated__/renderer/components/core/button/button.component.tsx
- packages/app/src/__deprecated__/renderer/components/core/button/button.stories.tsx
- packages/app/src/__deprecated__/renderer/components/core/button/button.styled.elements.tsx
- packages/app/src/overview/components/system/system.component.tsx
Jira: [CP-1742]
Scope:
* added loading button to pure and harmony overview views (see attached movie)
Awaiting for https://github.com/mudita/mudita-center/pull/1082 to be merged
<details>
https://user-images.githubusercontent.com/41268731/211549209-eb6787e1-af5f-446f-8645-34741dc0c00d.mov
</details>
[CP-1742]: https://appnroll.atlassian.net/browse/CP-1742?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1742] add loading button to pure and harmony overview

- packages/app/src/overview/components/overview-screens/harmony-overview/harmony-overview.component.interface.ts
- packages/app/src/overview/components/overview-screens/harmony-overview/harmony-overview.component.test.tsx
- packages/app/src/overview/components/overview-screens/harmony-overview/harmony-overview.component.tsx
- packages/app/src/overview/components/overview-screens/pure-overview/pure-overview.component.test.tsx
- packages/app/src/overview/components/overview-screens/pure-overview/pure-overview.component.tsx
- packages/app/src/overview/components/overview-screens/pure-overview/pure-overview.interface.ts
- packages/app/src/overview/components/overview/overview.test.tsx
- packages/app/src/overview/components/system/system.component.tsx
- packages/app/src/overview/overview.container.tsx
- packages/app/src/update/actions/base.action.ts
- packages/app/src/update/constants/download-state.constant.ts
- packages/app/src/update/constants/event.constant.ts
- packages/app/src/update/constants/silent-check-for-update.constant.ts
- packages/app/src/update/reducers/update-os.reducer.test.ts
- packages/app/src/update/reducers/update-os.reducer.ts
Jira: [CP-1742]
Scope:
* "Download now" button now opens "check for update" modal (see attached video)
<details>
https://user-images.githubusercontent.com/41268731/211777578-ce53f61b-a814-43f4-b33b-948bb6524f8b.mov
</details>
[CP-1742]: https://appnroll.atlassian.net/browse/CP-1742?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1742] download now button opens check for update modal

- packages/app/src/update/reducers/update-os.reducer.test.ts
- packages/app/src/update/reducers/update-os.reducer.ts
Jira: [CP-1742][CP-1796]
Scope:
* this PR solves problem described in https://appnroll.atlassian.net/browse/CP-1796 (invalid button state and label after successful update) - see attached movie with mocked update process
* another problem solved (not reported by QA) - handling situation when one of the updates succeeds but the next one fails. Previously restarting the process would cause to start installation of already installed update - see attached movie with mocked update process
<details>
https://user-images.githubusercontent.com/41268731/213662771-27e0c415-ca8a-454a-9e05-d281ab3a512b.mov
https://user-images.githubusercontent.com/41268731/213663035-c72e66b1-0adb-4ef5-99fa-367e14c8c64d.mov
</details>
[CP-1742]: …
> [CP-1742] show label and button proper state after update os process

- packages/app/src/device/actions/locked-device.action.test.ts
- packages/app/src/device/actions/locked-device.action.ts
- packages/app/src/device/modules/device.ts
- packages/app/src/device/requests/unlock-device-status.request.ts
- packages/app/src/device/services/device.service.ts
- packages/app/src/device/strategies/pure.strategy.ts
Jira: [CP-1755]
Scope:
* eula modal now appears (see attached video)
<details>
https://user-images.githubusercontent.com/41268731/214333444-a08fc4ea-b52c-4965-a575-f95eeec2775e.mov
</details>
[CP-1755]: https://appnroll.atlassian.net/browse/CP-1755?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1755] fix problem with eula modal

- packages/app/src/__deprecated__/passcode-modal/passcode-modal-ui.component.tsx
- packages/app/src/__deprecated__/passcode-modal/passcode-modal.component.tsx
- packages/app/src/__deprecated__/passcode-modal/passcode-modal.test.tsx
- packages/app/src/__deprecated__/renderer/wrappers/layout-blank-wrapper.tsx
- packages/app/src/connecting/components/connecting.component.tsx
- packages/app/src/connecting/components/connecting.test.tsx
- packages/app/src/connecting/connecting.container.ts
Jira: [CP-1804] [CP-1806]
Scope:
* do not allow to turn off passcode modal during update or when force update is needed
* do not allow to turn off loading layout during update or when force update is needed
See attached movie
<details>
https://user-images.githubusercontent.com/41268731/214862308-bbcd2920-1f1e-4640-a7a0-7b9068440197.mov
</details>
[CP-1804]: https://appnroll.atlassian.net/browse/CP-1804?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CP-1806]: https://appnroll.atlassian.net/browse/CP-1806?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1804] disallow to turn off passcode modal during force update

- packages/app/src/__deprecated__/renderer/components/rest/menu/menu.container.tsx
- packages/app/src/device/reducers/device.reducer.test.ts
- packages/app/src/device/reducers/device.reducer.ts
- packages/app/src/update/reducers/update-os.interface.ts
- packages/app/src/update/reducers/update-os.reducer.test.ts
- packages/app/src/update/reducers/update-os.reducer.ts
Jira: [CP-1804]
Scope:
* do not allow to exit force update feature with unlock phone feature (see movie attached to the task)
See attached movie
<details>
https://user-images.githubusercontent.com/41268731/215456928-ce66e25e-b3f2-4782-8c58-09bc3f24b98e.mov
</details>
[CP-1804]: https://appnroll.atlassian.net/browse/CP-1804?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1804] do not allow to exit force update with unlock feature

- packages/app/src/update/actions/handle-device-attached/handle-device-attached.action.ts
- packages/app/src/update/reducers/update-os.reducer.test.ts
- packages/app/src/update/reducers/update-os.reducer.ts
Jira: [CP-1809]
Scope:
* quick switching between tabs do not display "check for update failed" modal - see attached video
* update state is not reseted during backup or restore process (those processes restarts the device) - see attached video
<details>
https://user-images.githubusercontent.com/41268731/216267864-b22b16e9-fb15-4002-85e7-735e35766fa1.mov
https://user-images.githubusercontent.com/41268731/216279319-c1dacb73-9958-4b3f-9ebc-6e6913e05fd7.mov
</details>
[CP-1809]: https://appnroll.atlassian.net/browse/CP-1809?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1809] fixes

- packages/app/src/contacts/components/contacts/contacts.component.test.tsx
- packages/app/src/contacts/components/contacts/contacts.component.tsx
- packages/app/src/messages/components/messages/messages.component.tsx
- packages/app/src/messages/components/messages/messages.interface.ts
- packages/app/src/messages/components/messages/messages.stories.tsx
- packages/app/src/messages/components/messages/messages.test.tsx
- packages/app/src/messages/messages.container.tsx
- packages/app/src/messages/reducers/messages.interface.ts
- packages/app/src/messages/reducers/messages.reducer.test.ts
- packages/app/src/messages/reducers/messages.reducer.ts
- packages/app/src/messages/selectors/get-active-messages-by-thread-id.selector.test.ts
- packages/app/src/messages/selectors/get-thread-draft-message.selector.test.ts
- packages/app/src/search/actions/search.action.ts
- packages/app/src/search/constants/event.constant.ts
Jira: [CP-1714]
split search results from search preview for contacts and messages view
<details>
</details>
[CP-1714]: https://appnroll.atlassian.net/browse/CP-1714?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP -1714] Search different behaviour for result display 

- packages/app/src/contacts/components/contact-panel/contact-panel.component.tsx
- packages/app/src/contacts/components/contact-panel/contact-panel.test.tsx
- packages/app/src/contacts/components/contacts/contacts.component.tsx
- packages/app/src/messages/components/messages/messages.component.tsx
Jira: [CP-1714]
- display correct text in the search title
- blur event in the search input does not have an impact on search results
<details>
</details>
[CP-1714]: https://appnroll.atlassian.net/browse/CP-1714?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1714] show correct search title for messages and contacts

- packages/app/src/feature-flags/features/index.ts
- packages/app/src/update/services/releases.service.ts
- `MuditaCenterPrereleaseEnabled` feature flag updated
- remove tmp solution in `ReleaseService`
> Fix after merge 1.7.0

- packages/app/src/__deprecated__/calendar/components/events-list-date/events-list-date.test.tsx
- packages/app/src/__deprecated__/main/functions/register-news-listener/get-updated-news.test.ts
- packages/app/src/__deprecated__/main/functions/register-news-listener/get-updated-news.ts
- packages/app/src/news/helpers/sort-by-creation-date-in-descending-order/sort-by-creation-date-in-descending-order.helper.test.ts
- packages/app/src/news/helpers/sort-by-creation-date-in-descending-order/sort-by-creation-date-in-descending-order.helper.ts
- packages/app/src/news/selectors/news-sorted-by-creation-date/news-sorted-by-creation-date.selector.test.ts
- packages/app/src/news/selectors/news-sorted-by-creation-date/news-sorted-by-creation-date.selector.ts
Jira: [CP-1846]
- changed sorting news, now are sorted by date (date that is shown to the user)
- added new check for updating news from online source - if news' dates are different then local data is not valid and we update it :)
- some refactoring
[CP-1846]: https://appnroll.atlassian.net/browse/CP-1846?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1846] [News] Random latest News dates

- packages/app/src/messages/components/messages/messages.component.tsx
Jira: [CP-1921]
Covered in e2e test "New thread creation scenarios - no contacts & no threads"
<details>
</details>
[CP-1921]: https://appnroll.atlassian.net/browse/CP-1921?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1921] [Messages] lack of empty messages screen when deleting empty thread

- packages/app/src/messages/components/messages/messages.component.tsx
Jira: [CP-1877]
<details>
</details>
[CP-1877]: https://appnroll.atlassian.net/browse/CP-1877?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1877] [Messages] selected contact name isn't displayed above conversation window until message is sent

- packages/app/test-envs.js
Jira: [CP-1932]
overwrite FEATURE_TOGGLE_ENVIRONMENT env variable for unit tests
<details>
</details>
[CP-1932]: https://appnroll.atlassian.net/browse/CP-1932?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1932] [Tech] All unit tests should run with the development flag

- .env.example
- packages/app/src/update/services/releases.service.ts
Jira: [CP-1957]
- added toggle for latest release
- wondering about naming this feature toggle differently? Any ideas? Maybe 'FEATURE_TOGGLE_ENV_LATEST_RELEASE'?
[CP-1957]: https://appnroll.atlassian.net/browse/CP-1957?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1957] [Center] [Tech] Add feature toggle to .env to set releases environment

- packages/app/src/overview/components/overview-screens/helpers/use-update-flow-state.hook.tsx
- packages/app/src/update/actions/base.action.ts
- packages/app/src/update/actions/download-updates/download-updates.action.test.ts
- packages/app/src/update/actions/download-updates/download-updates.action.ts
- packages/app/src/update/actions/handle-device-detached/handle-device-detached.action.ts
- packages/app/src/update/constants/event.constant.ts
- packages/app/src/update/reducers/update-os.interface.ts
- packages/app/src/update/reducers/update-os.reducer.test.ts
- packages/app/src/update/reducers/update-os.reducer.ts
Jira: [CP-1861]
** Fix for update not aborting after device was unplugged during sequential update first completed os download **
[CP-1861]: https://appnroll.atlassian.net/browse/CP-1861?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-1861][Sequential update] Disconnected device at 100% of first OS download does not interupt the force update process

- .github/auto_assign.yml
- .github/pull_request_template.md
- packages/app/src/__deprecated__/main/main.ts
- packages/app/src/overview/components/overview-screens/pure-overview/pure-overview.component.tsx
- packages/app/src/update/actions/download-updates/download-updates.action.ts
- packages/app/src/update/actions/force-update/force-update.action.ts
- packages/app/src/update/actions/start-update-os/start-update-os.action.ts
Jira: [CP-2016]
[CP-2016]: https://appnroll.atlassian.net/browse/CP-2016?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2016] [SOSU] Sequential update for Harmony displays download progress while for Pure doesn't

- packages/app/src/device-manager/actions/get-current-device.action.ts
- packages/app/src/device/actions/base.action.ts
- packages/app/src/device/actions/connect-device.action.ts
- packages/app/src/device/actions/load-device-data.action.test.ts
- packages/app/src/device/actions/load-device-data.action.ts
- packages/app/src/device/actions/unlock-device.action.ts
- packages/app/src/device/reducers/device.interface.ts
- packages/app/src/device/reducers/device.reducer.test.ts
- packages/app/src/device/reducers/device.reducer.ts
Jira: [CP-2094]
<details>
</details>
[CP-2094]: https://appnroll.atlassian.net/browse/CP-2094?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2094] No Events about Harmony 1.5.1, 1.8.2, 1.9.0 and 2.0.0 are sent to Matomo.

- packages/app/src/__deprecated__/main/utils/logger.ts
Jira: [CP-2005]
<details>
</details>
[CP-2005]: https://appnroll.atlassian.net/browse/CP-2005?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2005] MC Update interupted by force OS update creates a huge log input

- packages/app/src/files-manager/actions/upload-file.action.ts
- packages/app/src/files-manager/reducers/files-manager.reducer.ts
Jira: [CP-2085]
<details>
</details>
[CP-2085]: https://appnroll.atlassian.net/browse/CP-2085?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2085] Uploading file larger than 2GB displays an error - instead of message "The file is too large for upload - max size is 2gb"

- packages/app/src/settings/components/about/about-ui.component.tsx
- packages/app/src/settings/components/about/about.component.tsx
- packages/app/src/settings/components/about/about.container.tsx
- packages/app/src/settings/hooks/use-online-checker.ts
Jira: [CP-2131]
<details>
</details>
[CP-2131]: https://appnroll.atlassian.net/browse/CP-2131?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2131] [Settings] [About] Switching to online causes out-of-date modals and wrong badges statuses

- packages/app/src/__deprecated__/main/main.ts
Jira: [CP-2110]
<details>
</details>
[CP-2110]: https://appnroll.atlassian.net/browse/CP-2110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2110] Window toolbar is displayed when left ALT key is pressed 

- packages/app/src/overview/components/backup-set-secret-key-modal-dialog/backup-set-secret-key-modal-dialog.component.tsx
Jira: [CP-2134]
<details>
</details>
[CP-2134]: https://appnroll.atlassian.net/browse/CP-2134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2134] [backup] password validation fails to indicate password mismatch in certain scenario

- packages/app/src/__deprecated__/renderer/utils/create-freshdesk-ticket/create-freshdesk-ticket.ts
Jira: No jira
- removed freshdesk mock usage for non-production build
- should we add something to default .env or quickstart.md?
> Remove Freshdesk mock for development

- packages/app/src/files-manager/actions/get-files.action.ts
- packages/app/src/files-manager/actions/upload-file.action.test.ts
- packages/app/src/files-manager/actions/upload-file.action.ts
- packages/app/src/files-manager/components/files-manager/files-manager.component.tsx
- packages/app/src/files-manager/constants/eligible-format.constant.ts
- packages/app/src/files-manager/helpers/check-files-extensions.helper.test.ts
- packages/app/src/files-manager/helpers/check-files-extensions.helper.ts
Jira: [CP-2132]
<details>
</details>
[CP-2132]: https://appnroll.atlassian.net/browse/CP-2132?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2132] It is possible to open multiple File Explorer windows during adding files to Harmony from the center

- packages/app/src/templates/components/templates/templates.component.tsx
Jira: [CP-2185]
<details>
</details>
[CP-2185]: https://appnroll.atlassian.net/browse/CP-2185?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2185] [Messages][Templates] Center displays a newly added template on 2nd position (after deleting other template) 

- packages/app/src/__deprecated__/renderer/locales/default/en-US.json
- packages/app/src/messages/messages.container.tsx
Jira: [CP-2186]
<details>
</details>
[CP-2186]: https://appnroll.atlassian.net/browse/CP-2186?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2186] [Messages][Templates] Templates order is reversed on attach template window in conversation

- packages/app/src/templates/components/templates/templates.component.tsx
Jira: [CP-2188]
<details>
</details>
[CP-2188]: https://appnroll.atlassian.net/browse/CP-2188?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2188] [Messages][Templates] change order success status popup appears even without changing template order

- packages/app/src/device/types/mudita-os/serialport-request.type.ts
- packages/app/src/templates/components/templates/templates.component.tsx
- packages/app/src/templates/presenters/template.presenter.test.ts
- packages/app/src/templates/presenters/template.presenter.ts
- packages/app/src/templates/services/template.service.test.ts
- packages/app/src/templates/services/template.service.ts
Jira: [CP-2185]
<details>
</details>
[CP-2185]: https://appnroll.atlassian.net/browse/CP-2185?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2185][2] [Messages][Templates] Center displays a newly added template on 2nd position (after deleting other template) 

- .env.example
- packages/app/src/__deprecated__/main/autoupdate.ts
- packages/app/src/feature-flags/constants/feature.enum.ts
- packages/app/src/feature-flags/features/index.ts
Jira: [CP-XXX]
In this pull request, the following changes have been made:
1. Removed the feature flag associated with `MuditaCenterPrereleaseEnabled`.
2. Eliminated the pre-release logic from the application update process.
3. Added a new environment variable named `RELEASES_REPOSITORY_NAME` to handle both production and stage environments, including release candidates.
Additionally,
-  a team has been added to the [mudita-center-internal-releases](https://github.com/mudita/mudita-center-internal-releases), to manage and store necessary updates for pre-release testing.
- changes have been tested with the new repository by self.
After merging this pull request, the following actions are planned:
1. Update environment variables in [Bitwarden](https://bitwarden.com/).
2. …
> [CP-XXX] Enhancements for Mudita Center Release Process

- libs/core/discovery-device/components/available-device-list.component.tsx
- libs/core/discovery-device/components/configured-devices-discovery.tsx
JIRA Reference: [CP-2337]
-
[CP-2337]: https://appnroll.atlassian.net/browse/CP-2337?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2337] Decomposition: Create  Discovery Device Lib

- libs/core/discovery-device/components/device-list-item.component.tsx
JIRA Reference: [CP-2377]
-
[CP-2377]: https://appnroll.atlassian.net/browse/CP-2377?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2377][Multidevice] Harmony 2 is visible on the list as Harmony 1 

- libs/core/__deprecated__/renderer/locales/default/en-US.json
- libs/core/discovery-device/components/device-list-item.component.tsx
- libs/core/overview/components/device-preview/device-preview.component.tsx
- libs/core/utils/get-serial-number-value.ts
JIRA Reference: [CP-2383]
-
[CP-2383]: https://appnroll.atlassian.net/browse/CP-2383?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2383][Multidevice] Incorect serial number display for Harmony with OS below 1.8.0

- libs/core/__deprecated__/renderer/locales/default/en-US.json
- libs/core/discovery-device/components/device-list-item.component.tsx
- libs/core/overview/components/card.elements.tsx
- libs/core/overview/components/device-preview/device-preview.component.tsx
- libs/core/overview/components/device-preview/device-preview.styled.tsx
- libs/core/utils/get-serial-number-value.ts
JIRA Reference: [CP-2371]
-
[CP-2371]: https://appnroll.atlassian.net/browse/CP-2371?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2371][Multidevice] Overview UI is a bit missaligned due to device image change

- libs/core/device-initialization/actions/start-initializing-device/initialize-mudita-pure.ts
JIRA Reference: [CP-2379]
-
[CP-2379]: https://appnroll.atlassian.net/browse/CP-2379?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2379] Handle Battery Critical Level as an initializing step

- libs/core/__deprecated__/renderer/wrappers/layout-blank-wrapper.tsx
JIRA Reference: [CP-2391]
-
[CP-2391]: https://appnroll.atlassian.net/browse/CP-2391?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2391][Multidevice] After closing device selection modal, single device isn't automatically connected

- libs/core/data-sync/actions/update-all-indexes.action.ts
JIRA Reference: [CP-2389]
-
[CP-2389]: https://appnroll.atlassian.net/browse/CP-2389?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2389][Multidevice] User must press Try again on Sync failed modal in order to make a sync

- libs/core/update/actions/check-for-force-update-need/check-for-force-update-need.action.ts
- libs/core/update/actions/check-for-update/check-for-update.action.test.ts
- libs/core/update/actions/check-for-update/check-for-update.action.ts
- libs/core/update/actions/download-updates/download-updates.action.ts
- libs/core/update/actions/start-update-os/start-update-os.action.ts
- libs/core/update/constants/errors.constant.ts
- libs/core/update/reducers/update-os.reducer.ts
JIRA Reference: [CP-2372]
-
[CP-2372]: https://appnroll.atlassian.net/browse/CP-2372?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2372][Multidevice] OS update information is globally set - v3

- libs/core/overview/components/device-preview/device-preview.component.tsx
- libs/core/overview/components/device-preview/device-preview.styled.tsx
JIRA Reference: [CP-2371]
-
[CP-2371]: https://appnroll.atlassian.net/browse/CP-2371?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2371][Multidevice] Overview UI is a bit missaligned due to device image change - v2

- libs/core/contacts/actions/delete-contacts.action.test.ts
- libs/core/contacts/actions/delete-contacts.action.ts
JIRA Reference: [CP-2393]
-
[CP-2393]: https://appnroll.atlassian.net/browse/CP-2393?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2393][Multidevice] Deleting modal does not disappear on reconnecting USB while deleting contacts - v3

- libs/core/contacts/actions/delete-contacts.action.test.ts
- libs/core/contacts/actions/delete-contacts.action.ts
- libs/core/core/components/base-app.component.tsx
JIRA Reference: [CP-2399]
-
[CP-2399]: https://appnroll.atlassian.net/browse/CP-2399?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2399][Multidevice] Selection manager once triggered remains set after switching app sections

- libs/core/device-initialization/actions/start-initializing-device/initialize-mudita-pure.ts
- libs/core/settings/actions/load-settings.action.ts
JIRA Reference: [CP-2392]
-
[CP-2392]: https://appnroll.atlassian.net/browse/CP-2392?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2392][Multidevice] After reopening the app it does not see existing backups 

- libs/core/device-manager/actions/handle-device-detached.action.ts
- libs/core/device-manager/selectors/is-active-device-attached.selector.ts
- libs/core/update/actions/base.action.ts
- libs/core/update/actions/download-updates/download-updates.action.test.ts
- libs/core/update/actions/download-updates/download-updates.action.ts
- libs/core/update/components/update-os-interrupted-flow/update-os-interrupted-flow.component.tsx
- libs/core/update/components/update-os-interrupted-flow/update-os-interrupted-flow.container.tsx
- libs/core/update/components/update-os-interrupted-flow/update-os-interrupted-flow.interface.ts
- libs/core/update/components/update-os-interrupted-flow/update-os-interrupted-flow.test.tsx
- libs/core/update/constants/event.constant.ts
- libs/core/update/reducers/update-os.interface.ts
- libs/core/update/reducers/update-os.reducer.test.ts
- libs/core/update/reducers/update-os.reducer.ts
JIRA Reference: [CP-2400]
-
[CP-2400]: https://appnroll.atlassian.net/browse/CP-2400?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2400][Multidevice] Disconnected device during OS update - after failed modal, Center acts like device was connected

- libs/core/overview/components/card.elements.tsx
- libs/core/overview/components/device-preview/device-preview.component.tsx
- libs/core/overview/components/device-preview/device-preview.test.tsx
JIRA Reference: [CP-2384] [CP-2167]
-
[CP-2384]: https://appnroll.atlassian.net/browse/CP-2384?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CP-2167]: https://appnroll.atlassian.net/browse/CP-2167?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2384][CP-2167] [Multidevice] Disconnect button does not disconnect the device (single device scenario) 

- libs/core/contacts/services/contact.service.ts
- libs/core/device-initialization/components/passcode-modal/passcode-modal.container.tsx
JIRA Reference: [CP-2419]
-
[CP-2419]: https://appnroll.atlassian.net/browse/CP-2419?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2419][Multidevice] Locking Pure does not seem to interupt the ongoing operation

- libs/core/device-manager/actions/handle-device-detached.action.ts
- libs/core/device/actions/get-onboarding-status.action.ts
- libs/core/overview/components/overview-screens/pure-overview/pure-overview.component.tsx
- libs/core/overview/components/overview-screens/pure-overview/use-handle-device-detached.hook.ts
- libs/core/update/components/update-os-interrupted-flow/update-os-interrupted-flow.component.tsx
- libs/core/update/components/update-os-interrupted-flow/update-os-interrupted-flow.container.tsx
- libs/core/update/components/update-os-interrupted-flow/update-os-interrupted-flow.test.tsx
JIRA Reference: [CP-2421]
-
[CP-2421]: https://appnroll.atlassian.net/browse/CP-2421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2421][Multidevice] switching Pure during restore operation - Center keeps displaying first one

- libs/core/contacts/actions/import-contact.action.ts
- libs/core/contacts/components/contacts/contacts.component.tsx
- libs/core/contacts/services/contact.service.ts
JIRA Reference: [CP-2419]
-
[CP-2419]: https://appnroll.atlassian.net/browse/CP-2419?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2419][Multidevice] Locking Pure does not seem to interupt the ongoing operation - v2

- libs/core/eula-agreement/components/agreement-modal/agreement-modal.component.tsx
JIRA Reference: [CP-2434]
-
[CP-2434]: https://appnroll.atlassian.net/browse/CP-2434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2434][Multidevice] Icon on the EULA prompt is inconsistent with the design

- libs/core/files-manager/actions/delete-files.action.test.ts
- libs/core/files-manager/actions/delete-files.action.ts
- libs/core/files-manager/actions/get-files.action.test.ts
- libs/core/files-manager/actions/get-files.action.ts
- libs/core/files-manager/actions/upload-file.action.test.ts
- libs/core/files-manager/components/files-manager/files-manager.component.tsx
- libs/core/files-manager/components/files-manager/get-spaces.helper.test.ts
- libs/core/files-manager/components/files-manager/use-disk-space-categories.hook.ts
- libs/core/files-manager/components/files-manager/use-spaces/get-spaces.helper.ts
- libs/core/files-manager/components/files-manager/use-spaces/spaces.interface.ts
- libs/core/files-manager/components/files-manager/use-spaces/use-spaces.hook.ts
- libs/core/files-manager/components/files-summary/files-summary.component.tsx
- libs/core/files-manager/reducers/files-manager.reducer.ts
JIRA Reference: [CP-2430]
[CP-2430]: https://appnroll.atlassian.net/browse/CP-2430?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2430][Multidevice] File manager memory usage is incorrectly calculated / no update

- libs/generic-view/store/src/lib/hooks/use-api-serial-port-listeners.ts
- Fixed "Cannot read properties of undefined (reading 'apiConfig')" by add conditions with `deviceType 
> [CP-XXX] Fixed issue with lack handling device type in API listener

- libs/core/__deprecated__/renderer/constants/urls.ts
- libs/core/__deprecated__/renderer/wrappers/layout-blank-wrapper.tsx
- libs/core/core/components/apps/base-app/base-app-routes.tsx
- libs/core/core/hooks/use-device-detached-effect.ts
- libs/core/core/hooks/use-discovery-redirect-effect.ts
- libs/core/device-initialization/actions/initialize-mudita-pure.action.ts
- libs/core/device-initialization/constants/errors.enum.ts
- libs/core/device-manager/actions/deactivate-device.action.ts
- libs/core/device-manager/reducers/device-manager.reducer.ts
- libs/core/discovery-device/components/available-device-list.component.tsx
- libs/core/discovery-device/components/available-device-list.container.tsx
- libs/core/overview/components/overview-screens/pure-overview/pure-overview.component.tsx
- libs/core/overview/components/overview-screens/pure-overview/use-deactivate-device-and-redirect.hook.ts
- libs/core/overview/components/overview-screens/pure-overview/use-handle-active-device-aborted.hook.ts
- libs/core/overview/components/overview-screens/pure-overview/use-redirect-on-active-device-detached.hook.ts
JIRA Reference: [CP-2163]
- Enhanced the application's functionality so that when a user cancels the initialization process, the application correctly redirects to the news view.
- Improved the process of entering discovery mode, activated when a user manually checks the app version in settings.
- Fixed an issue with an endless loader that occurred when a user disconnects and reconnects the device.
- Resolved an issue with the 'disconnect' button, which did not function correctly in the previous version.
[CP-2163]: …
> [CP-2163] Fix for Initialization Abort Process and Enhancement of Discovery Mode Logic

- libs/core/core/hooks/use-device-connected-effect.ts
- libs/core/core/hooks/use-device-detached-effect.ts
- libs/core/overview/components/overview-screens/pure-overview/use-deactivate-device-and-redirect.hook.ts
JIRA Reference: [CP-2476]
The change removes automatic device connection when a dialog is open in the app, regardless of whether the device is being disconnected or connected. Users gain full control over the connection process, avoiding unwanted redirections.
[CP-2476]: https://appnroll.atlassian.net/browse/CP-2476?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2476][Multidevice] quick reconnect (or lose USB socket) during file upload and Center keep showing device

- libs/core/app-initialization/components/app-initialization-flow.component.tsx
- libs/core/core/hooks/use-discovery-redirect-effect.ts
- libs/core/desktop/desktop.constants.ts
- libs/core/desktop/desktop.controller.ts
- libs/core/desktop/desktop.service.test.tsx
- libs/core/desktop/desktop.service.ts
- libs/core/desktop/requests/is-user-in-serial-port-group.request.ts
- libs/core/modals-manager/actions/check-app-requires-serial-port-group-to-show.action.ts
- libs/core/modals-manager/selectors/modals-manager-state.selector.ts
- libs/core/overview/components/overview-screens/pure-overview/use-handle-active-device-aborted.hook.ts
- libs/core/settings/components/usb-access/usb-access-flow.container.tsx
- libs/core/settings/reducers/settings.reducer.ts
- libs/core/settings/selectors/is-usb-access-restart.selector.ts
JIRA Reference: [CP-2216]
- Updated serial port access check: Shifted from device path checking to verifying group membership.
- Implemented auto-connect prevention without permissions: Now preventing automatic connection when access permissions are lacking.
- Created an access management guide: Developed "How to Manage Serial Port Access Permissions on Linux" documentation, available [here](https://appnroll.atlassian.net/wiki/spaces/CP/pages/2178285882/How+to+Manage+Serial+Port+Access+Permissions+on+Linux).
[CP-2216]: …
> [CP-2216] Implement Group Membership Check for Serial Port Access and Prevent Auto-Connect When Disabled

- libs/core/core/decorators/log.decorator.ts
- libs/core/device-manager/services/device-manager.service.ts
Enhanced the @log decorator to allow specifying the spacing in structured log output. This tweak helps in maintaining concise and readable logs, especially in environments where space conservation is essential. The update is fully backward compatible, promoting a seamless transition.
- Introduced a `space` parameter to control JSON formatting in logs.
- Default behavior remains unchanged for existing implementations.
> [CP-XXX] Improve log readability by adding customizable spacing

- libs/core/settings/reducers/settings.reducer.ts
JIRA Reference: [CP-2703]
This PR fixes a regression bug related to the handling of the collectingData field, which has been identified as deprecated but is still present in the system. The issue was detected as a regression compared to the production version. The collectingData field has been marked for removal in a dedicated task ([CP-2711](https://appnroll.atlassian.net/browse/CP-2711)).
[CP-2703]: https://appnroll.atlassian.net/browse/CP-2703?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU …
> [CP-2703] Latest dev-554 + build is showing a unexpected Privacy Policy popup

- libs/core/modals-manager/actions/check-app-requires-serial-port-group-to-show.action.ts
JIRA Reference: [CP-2292]
Temporarily bypass USB group check in CI until DevOps updates the runner setup.
[CP-2292]: https://appnroll.atlassian.net/browse/CP-2292?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2292] Skip USB Access Validation in CI

- apps/mudita-center-e2e/src/page-objects/modal.page.ts
- apps/mudita-center-e2e/src/specs/settings/terms-of-service.e2e.ts
- apps/mudita-center-e2e/wdio.conf.ts
- libs/core/core/hooks/use-application-update-effects.ts
JIRA Reference: [CP-2295]
This PR fixes a timeout issue where the auto-update process gets stuck in E2E testing environments on Linux, due to improper dependency handling. It also prevents a potential problem in production environments should the checking process stall.
[CP-2295]: https://appnroll.atlassian.net/browse/CP-2295?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2295] handle autoupdate timeout

- libs/device/feature/src/lib/data-transfer/data-transfer.service.ts
- libs/device/models/src/lib/data-transfer/data-transfer.test.ts
- libs/device/models/src/lib/data-transfer/data-transfer.ts
JIRA Reference: [CP-2733]
-
[CP-2733]: https://appnroll.atlassian.net/browse/CP-2733?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2733] add data transfer validators

- libs/core/__deprecated__/renderer/wrappers/app-update-step-modal/app-update-step-modal.component.tsx
- libs/core/app-initialization/selectors/is-app-update-process-passed.selector.ts
- libs/core/app-initialization/selectors/should-app-update-flow-visible.selector.ts
- libs/core/settings/actions/base.action.ts
- libs/core/settings/actions/load-settings.action.test.ts
- libs/core/settings/actions/load-settings.action.ts
JIRA Reference: [CP-2798] [CP-2799] [CP-2800] [CP-2805]
-
[CP-2798]: https://appnroll.atlassian.net/browse/CP-2798?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CP-2799]: https://appnroll.atlassian.net/browse/CP-2799?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CP-2800]: https://appnroll.atlassian.net/browse/CP-2800?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CP-2805]: …
> [CP-2798][CP-2799][CP-2800][CP-2805]

- libs/core/settings/components/backup/__snapshots__/backup-ui.test.tsx.snap
- libs/core/settings/components/backup/backup-ui.component.tsx
- libs/core/settings/components/backup/settings-backup-test-ids.enum.ts
JIRA Reference: [CP-2820]
-
[CP-2820]: https://appnroll.atlassian.net/browse/CP-2820?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2820] Add data-testid selector to "Change Backup location" button

- libs/core/device-initialization/actions/initialize-mudita-pure.action.ts
- libs/core/device/actions/get-unlock-status.action.ts
- libs/core/device/reducers/device.reducer.ts
JIRA Reference: [CP-2797] [CP-2804] [CP-2813]
-
[CP-2813]: https://appnroll.atlassian.net/browse/CP-2813?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CP-2797]: https://appnroll.atlassian.net/browse/CP-2797?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CP-2804]: https://appnroll.atlassian.net/browse/CP-2804?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2813] Stress test - sometimes "Unfortunately, synchronization failed" error appears and passcode modal appears for a second

- libs/core/app-initialization/selectors/is-app-update-process-passed.selector.ts
JIRA Reference: [CP-2831]
-
[CP-2831]: https://appnroll.atlassian.net/browse/CP-2831?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2831] Download failed modal is not displayed after disconnecting the internet while updating 

- libs/core/analytic-data-tracker/services/analytic-data-tracker.service.ts
JIRA Reference: [CP-2817]
-
[CP-2817]: https://appnroll.atlassian.net/browse/CP-2817?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2817] Empty settings page after unsuccessful force update on 0.0.1-qa-2.3.0-rc3

- package-lock.json
- package.json
This PR downgrades `node-ipc` to version `10.1.0` to address the issue of the unwanted creation of the `WITH-LOVE-FROM-AMERICA.txt` file, as recommended by the library's author in https://github.com/RIAEvangelist/node-ipc/issues/3. The change includes updating `package.json` and appropriately modifying `package-lock.json`."
> [CP-XXX] Downgrade `node-ipc` to v10.1.0 for Compatibility

- apps/mudita-center-e2e/src/specs/help/help-window-check-offline.e2e.ts
- apps/mudita-center-e2e/src/test-filenames/consts/test-filenames.const.ts
- apps/mudita-center-e2e/wdio.conf.ts
JIRA Reference: [CP-2748](https://appnroll.atlassian.net/browse/CP-2748)
- Go Offline
- Check if new window shows up
- Check contents of Mudita Help (header, search, contact support button, accordion)
- Open first question in accordion - check content
- Click Back icon
- Search for questions - check search results
- Click Contact Support 
- Close Contact Support, Close Mudita Help, verify result
[CP-2748]: https://appnroll.atlassian.net/browse/CP-2748?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNv …
> [CP-2748] [E2E][Help] Verify Help Contents, Search and Contact button (offline)

- libs/generic-view/store/src/lib/selectors/data-migration-devices.ts
JIRA Reference: [CP-2894]
-
[CP-2894]: https://appnroll.atlassian.net/browse/CP-2894?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2894] Fixed Pure device name on data migration tab

- libs/core/__deprecated__/renderer/wrappers/layout-blank-wrapper.tsx
- libs/core/connecting/components/connecting-content.component.tsx
- libs/core/core/components/apps/base-app/base-app-routes.tsx
- libs/core/device-initialization/components/devices-initialization-modal-flows/api-device-initialization-modal-flow.tsx
- libs/core/device-initialization/components/devices-initialization.component.tsx
- libs/core/device-initialization/components/passcode-modal/passcode-modal-ui.component.tsx
- libs/core/ui/components/modal-dialog/get-modal-dialog-style.helper.ts
- libs/core/ui/components/modal-dialog/modal-dialog.component.tsx
- libs/core/ui/components/modal-dialog/modal-dialog.interface.ts
JIRA Reference: [CP-2845]
-
[CP-2845]: https://appnroll.atlassian.net/browse/CP-2845?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2845] Kompakt's loader after selection Pure or Harmony as an active device

- libs/core/device-select/components/device-select-drawer.component.tsx
JIRA Reference: [CP-2953]
-
[CP-2953]: https://appnroll.atlassian.net/browse/CP-2953?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2953] Empty device selection drawer appears during connect/disconnect stress tests

- libs/e2e-mock/server/README.md
- libs/e2e-mock/server/src/lib/mock-updater-state.service.ts
- libs/electron/application-updater/src/lib/mock-application-updater.service.ts
JIRA Reference: [CP-2749]
-
[CP-2749]: https://appnroll.atlassian.net/browse/CP-2749?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2749] Extended `MockUpdaterStateService` to handle downloaded state

- libs/core/device-select/components/device-select-drawer.component.tsx
- libs/core/device-select/components/drawer-device.component.tsx
JIRA Reference: [CP-2980]
[CP-2981]
[CP-2982]
[CP-2983]
[CP-2984]
-
[CP-2980]: https://appnroll.atlassian.net/browse/CP-2980?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CP-2981]: https://appnroll.atlassian.net/browse/CP-2981?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CP-2982]: https://appnroll.atlassian.net/browse/CP-2982?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CP-2983]: …
> [CP-2980] add data-testids for select device

- libs/core/contacts/components/contact-search-results/contact-search-results.component.tsx
JIRA Reference: [CP-2949]
[CP-2949]: https://appnroll.atlassian.net/browse/CP-2949?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2949] Contacts > Search - layout is broken

- libs/core/settings/actions/load-settings.action.ts
- libs/core/utils/get-base-bersion.ts
JIRA Reference: [CP-3095]
-
[CP-3095]: https://appnroll.atlassian.net/browse/CP-3095?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3095] 2.3.1-mockdev.70 requests not existing app update

- libs/generic-view/ui/src/lib/predefined/backup/backup-password.tsx
JIRA Reference: [CP-3096]
-
[CP-3096]: https://appnroll.atlassian.net/browse/CP-3096?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3096] "Skip password" is not possible if user will activate "Repeat password" but doesn't type any char for any field for backup creation

- libs/core/device-initialization/components/passcode-modal/passcode-modal.component.tsx
JIRA Reference: [CP-2870]
-
[CP-2870]: https://appnroll.atlassian.net/browse/CP-2870?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2870] Improper handling of an incorrectly entered passcode

- apps/mudita-center-e2e/src/specs/stress-tests/device-drawer-stress-test.ts
JIRA Reference: [CP-3068]
Test fixes the device-drawer stress test. Now only device drawer is displayed instead of select device modal
-
[CP-3068]: https://appnroll.atlassian.net/browse/CP-3068?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-2919-pause-fix added loop and pause

- libs/core/contact-support/containers/contact-support-flow.container.test.tsx
- libs/e2e-test-ids/src/e2e-test-ids.ts
- libs/generic-view/ui/src/lib/interactive/modal/modal.tsx
- libs/generic-view/ui/src/lib/predefined/backup/backup-features.tsx
JIRA Reference: [CP-3119] [CP-3122]
-
[CP-3119]: https://appnroll.atlassian.net/browse/CP-3119?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CP-3122]: https://appnroll.atlassian.net/browse/CP-3122?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3119] [CP-3122] Added data-testid to Backup Modal

- libs/msc-flash/msc-flash-harmony/src/lib/services/device-flash/linux-device-flash.service.ts
- libs/msc-flash/msc-flash-harmony/src/lib/services/device-flash/linux-partition-parser.test.ts
- libs/msc-flash/msc-flash-harmony/src/lib/services/device-flash/linux-partition-parser.ts
- libs/shared/utils/src/lib/exec-command-with-sudo.ts
JIRA Reference: [CP-2914]
-
[CP-2914]: https://appnroll.atlassian.net/browse/CP-2914?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2914] Device flashing workaround added for Linux - vol.2

- apps/mudita-center-e2e/src/page-objects/contacts.page.ts
- apps/mudita-center-e2e/src/page-objects/help-modal.page.ts
- apps/mudita-center-e2e/src/page-objects/help.page.ts
- apps/mudita-center-e2e/src/page-objects/messages-browse-contacts-modal.page.ts
- apps/mudita-center-e2e/src/page-objects/messages-conversation.page.ts
- apps/mudita-center-e2e/src/page-objects/messages-templates.page.ts
- apps/mudita-center-e2e/src/page-objects/messages.page.ts
- apps/mudita-center-e2e/src/page-objects/modal-backup-restore.page.ts
- apps/mudita-center-e2e/src/page-objects/modal-contacts.page.ts
- apps/mudita-center-e2e/src/page-objects/modal-general.page.ts
- apps/mudita-center-e2e/src/page-objects/modal-messages.page.ts
- apps/mudita-center-e2e/src/page-objects/news.page.ts
- apps/mudita-center-e2e/src/page-objects/tabs.page.ts
- apps/mudita-center-e2e/src/specs/stress-tests/connected-devices-stress-test.ts
- apps/mudita-center-e2e/tsconfig.json
- apps/mudita-center-e2e/wdio.conf.ts
- package-lock.json
- package.json
JIRA Reference: [CP-2634]
- Implemented a workaround for geckodriver versioning issues following a WebdriverIO update. Refer to the original issue and workaround here: https://github.com/webdriverio/webdriverio/issues/13550.
- Uninstalled wdio/allure-reporter as the package was not used.
- Fixed broken tests caused by the WebdriverIO upgrade, including iterating over available devices.
- Installed @types/fs-extra to handle unchanged files with check annotations.
- Note: A newer version of WebdriverIO is available (9+), which will require upgrading Node.js and, consequently, Electron.
- translations are updated in dedicated …
> [CP-2634] Update webdriverIO from 7.16 to 8.6+

- libs/generic-view/feature/src/lib/setup-component.tsx
- libs/generic-view/feature/src/lib/use-dev-views/views/contacts-view.ts
-
[CP-2995]: https://appnroll.atlassian.net/browse/CP-2995?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2995] Contacts Panel added (wrapper)

- libs/generic-view/feature/src/lib/seed-data/contacts-seed-data.ts
- libs/generic-view/feature/src/lib/use-dev-console.ts
JIRA Reference: [CP-3147]
This PR adds seed data via the global _seedDataMap and introduces _createMultipleEntities for bulk entity insertion. Seed data can be listed or accessed directly from the console.
```ts
// Insert multiple entities
await global._createMultipleEntities("contacts", global._seedDataMap.contacts);
// List all seed data for contacts
console.log(global._seedDataMap.contacts);
// Retrieve a single seed record
console.log(global._seedDataMap.contacts[0]);
```
[CP-3147]: …
> [CP-3147] Prepare input data that covers the scope of requirements related to sorting

- apps/mudita-center-e2e/src/helpers/index.ts
- apps/mudita-center-e2e/src/helpers/testid.helper.ts
- libs/core/contact-support/components/contact-support-modal.component.test.tsx
- libs/core/contact-support/components/contact-support-modal.component.tsx
- libs/core/contact-support/containers/contact-support-flow.container.test.tsx
- libs/e2e-test-ids/src/e2e-test-ids.ts
- libs/generic-view/ui/src/lib/buttons/button-primary.tsx
JIRA Reference: [CP-3153]
-
[CP-3153]: https://appnroll.atlassian.net/browse/CP-3153?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3153] Added test ids to start backup action and contact support modal

- apps/mudita-center-e2e/src/page-objects/modal-backup-kompakt.page.ts
- apps/mudita-center-e2e/src/page-objects/overview-kompakt.page.ts
- apps/mudita-center-e2e/src/page-objects/overview.page.ts
…ted backupInfo selector for kompakt-overview test and kompakt-backup-getting-initial-info
JIRA Reference: [CP-3154]
fix selector and tests for "Create backup"  and "backupInfo" on overview - Kompakt
-
[CP-3154]: https://appnroll.atlassian.net/browse/CP-3154?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-3154 fix selector and tests for "Create backup"  and "backupInfo" on overview - Kompakt

- libs/device/models/src/lib/feature/extra-config.ts
- libs/generic-view/feature/src/lib/setup-component.tsx
- libs/generic-view/ui/src/lib/interactive/tooltip/tooltip.tsx
JIRA Reference: [CP-3145]
<details>
</details>
[CP-3145]: https://appnroll.atlassian.net/browse/CP-3145?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3145] Add Bottom-Left Position for Tooltip

- libs/device/models/src/lib/feature/extra-config.ts
- libs/generic-view/ui/src/lib/interactive/tooltip/tooltip-helpers.tsx
- libs/generic-view/ui/src/lib/interactive/tooltip/tooltip.tsx
JIRA Reference: [CP-3146]
Tooltip flipping logic has been implemented to prevent tooltips from overflowing the viewport boundaries.
<details>
</details>
[CP-3146]: https://appnroll.atlassian.net/browse/CP-3146?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3146] Implemented Tooltip Flipping to Maintain Viewport Visibility

- libs/generic-view/ui/src/lib/interactive/tooltip/tooltip-helpers.tsx
- libs/generic-view/ui/src/lib/interactive/tooltip/tooltip.tsx
Refactor tooltip positioning logic by introducing adjustedOffset to handle flipping adjustments for more consistent and maintainable offset calculations.
```
// @ts-ignore
const view: View = {
phoneDropdownCounterBadge: {
component: "button-text",
config: {
actions: [],
modifiers: ["hover-background"],
},
layout: {
padding: "2px 5px",
},
dataProvider: {
source: "entities-field",
entitiesType: "contacts",
fields: [
{
slice: [1],
flat: "phoneNumber",
providerField: "phoneNumbers",
componentField: "extra-data.tooltip.contentList",
},
],
},
extra: {
tooltip: {
placement: "bottom-left",
offset: {
x: 0,
y: 15,
},
},
},
childrenKeys: ["phoneDropdownCounterBadgeText"],
},
columnCheckbox: {
component: "table.cell",
config: {
width: "74",
},
layout: {
padding: "0 0 0 …
```
> [CP-2995] Introduce adjustedOffset logic to handle tooltip flipping adjustments

- libs/core/core/components/apps/base-app/base-app.component.tsx
- libs/core/core/hooks/use-abort-flashing-on-device-detached.ts
- libs/core/core/hooks/use-device-detached-effect.ts
- libs/generic-view/store/src/lib/action-names.ts
- libs/msc-flash/msc-flash-harmony/src/lib/actions/abort-msc-flashing.ts
- libs/msc-flash/msc-flash-harmony/src/lib/actions/actions.ts
- libs/msc-flash/msc-flash-harmony/src/lib/actions/index.ts
- libs/msc-flash/msc-flash-harmony/src/lib/constants/flashing-process-state.enum.ts
- libs/msc-flash/msc-flash-harmony/src/lib/reducers/flashing.interface.ts
- libs/msc-flash/msc-flash-harmony/src/lib/reducers/flashing.reducer.ts
- libs/msc-flash/msc-flash-harmony/src/lib/selectors/flashing-state.selector.ts
- libs/msc-flash/msc-flash-harmony/src/lib/selectors/index.ts
- libs/msc-flash/msc-flash-harmony/src/lib/selectors/select-flashing-abort-controller.ts
- libs/msc-flash/msc-flash-harmony/src/lib/selectors/select-flashing-process-state.ts
- libs/msc-flash/msc-flash-harmony/src/lib/services/device-flash/device-flash.factory.ts
- libs/msc-flash/msc-flash-harmony/src/lib/services/device-flash/device-flash.interface.ts
- libs/msc-flash/msc-flash-harmony/src/lib/services/device-flash/linux/linux-device-flash.service.ts
- libs/msc-flash/msc-flash-harmony/src/lib/services/device-flash/macos/macos-device-flash-service.ts
- libs/msc-flash/msc-flash-harmony/src/lib/services/flash-msc-device.service.ts
- libs/msc-flash/msc-flash-harmony/src/lib/ui/mac-terminal-info-modal/mac-terminal-info-modal.component.tsx
- libs/msc-flash/msc-flash-harmony/src/lib/ui/recovery-mode.tsx
JIRA Reference: [CP-3128]
-
[CP-3128]: https://appnroll.atlassian.net/browse/CP-3128?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3128] Improve Flashing Process to Handle macOS Specific Path and Flash Completion

- libs/msc-flash/msc-flash-harmony/src/lib/ui/restarting-device-modal/restarting-device-modal.component.tsx
JIRA Reference: [CP-3135]
-
[CP-3135]: https://appnroll.atlassian.net/browse/CP-3135?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3135] Infinite loop after flashing - MC not aware that flashed device is actually ready to use

- libs/help/feature/src/lib/helpers/use-help-search.ts
- libs/help/ui/src/lib/components/search-results.tsx
- libs/help/ui/src/lib/components/search.tsx
JIRA Reference: [CP-3191] 
-
[CP-3191]: https://appnroll.atlassian.net/browse/CP-3191?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3191] Fix for displaying search results in help

- libs/device/models/src/lib/data-transfer/data-transfer.test.ts
- libs/device/models/src/lib/data-transfer/data-transfer.ts
- libs/device/models/src/lib/unified-entities/index.ts
- libs/device/models/src/lib/unified-entities/unified-message.ts
- libs/generic-view/store/src/lib/data-migration/data-migration-mappers/pure-to-unified-contact.ts
- libs/generic-view/store/src/lib/data-migration/data-migration-mappers/pure-to-unified-message.test.ts
- libs/generic-view/store/src/lib/data-migration/data-migration-mappers/pure-to-unified-message.ts
- libs/generic-view/store/src/lib/data-migration/transfer-migration-data.ts
- libs/generic-view/store/src/lib/data-transfer/transfer-data-to-device.action.ts
JIRA Reference: [CP-3211]
-
[CP-3211]: https://appnroll.atlassian.net/browse/CP-3211?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3211][Mudita Center] Process Messages from Pure to Kompakt

- libs/core/device-select/selectors/is-select-device-drawer-open.selector.ts
JIRA Reference: [CP-3227]
-
[CP-3227]: https://appnroll.atlassian.net/browse/CP-3227?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3227] Button "Show Connected Devices" Does Not Open the Side Drawer

- libs/generic-view/ui/src/lib/predefined/backup/backup-features.tsx
JIRA Reference: [CP-3114]
-
[CP-3114]: https://appnroll.atlassian.net/browse/CP-3114?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3114] Implement handling for 'coming soon' feature copy using configuration provided by Kompakt for Backup

- .github/workflows/nexus-development.yml
- .github/workflows/nexus-feature-branch.yml
- .github/workflows/nexus-mock-development.yml
- .github/workflows/nexus-mock-pre-production.yml
- .github/workflows/nexus-mock-production.yml
- .github/workflows/nexus-pre-production-latest.yml
- .github/workflows/nexus-pre-production.yml
JIRA Reference: [CP-3277]
-
[CP-3277]: https://appnroll.atlassian.net/browse/CP-3277?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
>  [CP-3277] Disable Code Signing for Applications on Non-Production Environments in Windows

- .github/workflows/nexus-mock-pre-production.yml
- .github/workflows/nexus-pre-production-latest.yml
- .github/workflows/nexus-pre-production.yml
JIRA Reference: [CP-3277]
-
[CP-3277]: https://appnroll.atlassian.net/browse/CP-3277?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3277] Disable Code Signing for Applications on Non-Production Environments in Windows - vol.2

- libs/generic-view/models/src/lib/common-text-validators.ts
- libs/generic-view/ui/src/lib/generated/mc-file-manager-view.ts
- libs/generic-view/ui/src/lib/texts/common-text-styles.ts
- libs/generic-view/ui/src/lib/texts/paragraphs.tsx
JIRA Reference: [CP-3293]
<details>
</details
[CP-3293]: https://appnroll.atlassian.net/browse/CP-3293?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3293] Implementation of File List View (Empty State) 

- libs/generic-view/store/src/lib/entities/load-entities.action.ts
- libs/generic-view/ui/src/lib/entities/entities-loader.tsx
- libs/generic-view/ui/src/lib/generated/mc-file-manager-view.ts
JIRA Reference: [CP-3290]
video link: https://fileport.io/3ZYZAqQxUYUc
-  **Initialization of default values in `progress`** – Added a default value of `0` for each `entitiesType` to avoid `undefined`.
- **Handling NaN in average progress** – Secured calculations against division by `0`, eliminating `NaN` errors.
- **`fetchEntityData` as a `useCallback`** – Extracted data-fetching logic into a separate callback, improving readability and performance.
- **Fixing `loadEntities` collision issues** – Resolved race conditions during entity reloading, enhancing application stability."
- translations are updated in dedicated …
> [CP-3290] Data Fetching from API

- libs/e2e-test-ids/src/e2e-test-ids.ts
- libs/generic-view/ui/src/lib/interactive/progress-bar/progress-bar.tsx
- libs/generic-view/ui/src/lib/predefined/backup/backup-progress.tsx
JIRA Reference: [CP-3338]
-
[CP-3338]: https://appnroll.atlassian.net/browse/CP-3338?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3338] Add data-testid for create backup progress

- apps/mudita-center-e2e/src/page-objects/contacts-kompakt.ts
- apps/mudita-center-e2e/src/specs/overview/kompakt-contacts-viewing.ts
JIRA Reference: [CP-3372]
-
[CP-3372]: https://appnroll.atlassian.net/browse/CP-3372?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3372] Create selectors based on existing data-testid attributes for contacts preview

- libs/device/models/src/lib/overview/overview-data.ts
- libs/generic-view/models/src/lib/icon-text.ts
- libs/generic-view/ui/src/lib/data-rows/icon-text/icon-text.test.tsx
- libs/generic-view/ui/src/lib/data-rows/icon-text/icon-text.tsx
JIRA Reference: [CP-3420]
-
[CP-3420]: https://appnroll.atlassian.net/browse/CP-3420?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3420] Fixed displaying airplane mode

- apps/mudita-center-e2e/src/helpers/mock-entity-delete-process.ts
- apps/mudita-center-e2e/src/helpers/mock-entity-download-process.helper.ts
- apps/mudita-center-e2e/src/helpers/mock-prebackup.ts
- apps/mudita-center-e2e/src/specs/overview/e2e-mock-lock-sample.e2e.ts
- apps/mudita-center-e2e/src/specs/overview/e2e-mock-match.e2e.ts
- apps/mudita-center-e2e/src/specs/overview/e2e-mock-sample.e2e.ts
- apps/mudita-center-e2e/src/specs/overview/e2e-reset-mock-overview.e2e.ts
- apps/mudita-center-e2e/src/specs/overview/e2e-reset-mock-sample.e2e.ts
- apps/mudita-center-e2e/src/specs/overview/kompakt-about.ts
- apps/mudita-center-e2e/src/specs/overview/kompakt-backup-getting-initial-info.ts
- apps/mudita-center-e2e/src/specs/overview/kompakt-overview.ts
- apps/mudita-center-e2e/src/specs/overview/kompakt-prebackup-api.ts
- apps/mudita-center-e2e/src/specs/overview/kompakt-switching-devices.ts
- apps/mudita-center-e2e/src/specs/stress-tests/connected-devices-stress-test.ts
- apps/mudita-center-e2e/src/specs/stress-tests/device-drawer-stress-test.ts
- libs/e2e-mock/client/src/lib/e2e-mock-client.ts
- libs/e2e-mock/server/src/lib/mock-descriptor/mock-descriptor-validators.ts
- libs/e2e-mock/server/src/lib/mock-descriptor/mock-descriptor.test.ts
- libs/e2e-mock/server/src/lib/mock-descriptor/mock-descriptor.ts
- libs/e2e-mock/server/src/lib/server.tsx
JIRA Reference: [CP-2976]
-
[CP-2976]: https://appnroll.atlassian.net/browse/CP-2976?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2976] Extension of the mocking mechanism from per item to per list to avoid race conditions.

- libs/api-devices-testing/src/lib/connection.spec.tsx
- libs/api-devices-testing/src/lib/helpers/set-connection.ts
- libs/core/device/constants/product-identifier.constant.ts
- libs/e2e-mock/responses/src/lib/api-config-responses.ts
- libs/e2e-mock/responses/src/lib/default-responses.ts
- libs/e2e-mock/server/src/lib/mock-descriptor/mock-descriptor.ts
- libs/generic-view/store/src/lib/selectors/data-migration-devices.ts
JIRA Reference: [CP-3479]
-
[CP-3479]: https://appnroll.atlassian.net/browse/CP-3479?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3479] Update VendorID to new values

- apps/mudita-center-e2e/src/specs/overview/kompakt-connecting-2nd-kompakt-while-in-news.ts
- apps/mudita-center-e2e/src/specs/overview/kompakt-connecting-second-kompakt-while-in-news.ts
- apps/mudita-center-e2e/src/test-filenames/consts/test-filenames.const.ts
- apps/mudita-center-e2e/wdio.conf.ts
JIRA Reference: [CP-2922]
- Open App
Connect 1st Kompakt
Verify Overview Page 
Click News tab
Connect 2nd Kompakt
Click 2nd Kompakt
Overview should show up. Verify
Disconnect any devices
[CP-2922]: https://appnroll.atlassian.net/browse/CP-2922?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-2922] [API Device][Multidevice] Connecting 2nd Kompakt while in News

- apps/mudita-center-e2e/src/page-objects/locked-page-kompakt.ts
- apps/mudita-center-e2e/src/specs/overview/kompakt-passcode-close.ts
- apps/mudita-center-e2e/src/test-filenames/consts/test-filenames.const.ts
- apps/mudita-center-e2e/wdio.conf.ts
- libs/e2e-mock/responses/src/lib/overview-responses.ts
…cts)
JIRA Reference: [CP-2752]
- Open App
Homescreen (Onboarding screen) should show up
Wait until Overview screen loads
Popup about password should show up
Close modal without providing a password, Kompakt password screen should “disconnect” (dissapear)
Actual Behavior: NEWS        news page is opened after closing passcode modal, as on mockdevice we need to connect the 2nd device to trigger connection, we add a 2nd device to the test (also passcode locked) and news page is still displayed and 2 devices connected are displayed on the connected devices button    (as user has closed passcode modal, then it suggests MC that user is not interested in viewing device options now so we don’t interrupt with select device modal after connecting second device)*
Previously Expected: Verify you are …
> [CP-2752] [API Device][Kompakt] Passcode - Close modal without providing a password

- libs/app-serialport/devices/src/lib/serial-port-device.ts
- libs/app-serialport/main/src/lib/app-serial-port.preload.ts
- libs/app-serialport/main/src/lib/app-serial-port.ts
- libs/app-serialport/main/src/lib/init-serialport.ts
- libs/app-serialport/models/src/lib/serial-port-ipc-events.ts
- libs/app-serialport/renderer/src/lib/app-serial-port.ts
- libs/devices/api-device/adapters/src/lib/api-device-serial-port.ts
- libs/devices/api-device/models/src/lib/api-device.ts
> [CP-XXX] Added `getCurrentDevices` method to app-serialport

- libs/core/__deprecated__/renderer/locales/default/en-US.json
- libs/generic-view/ui/src/lib/predefined/file-preview/file-preview-error.types.ts
- libs/generic-view/ui/src/lib/predefined/file-preview/file-preview.tsx
- libs/generic-view/ui/src/lib/predefined/file-preview/image-preview.tsx
- libs/generic-view/ui/src/lib/predefined/file-preview/use-files-preview.tsx
JIRA Reference: [CP-3663]
-
[CP-3663]: https://appnroll.atlassian.net/browse/CP-3663?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CP-3663] Added files preview error handling
